---
title: "Pseudobulk Seurat 5 AverageExpression()"
output:
  html_document:
    df_print: paged
    code_folding: hide
  pdf_document: default
  toc: TRUE
---


```{r setup, include=T} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(fig.width = 10, fig.height = 8) 
```

```{r}
library(Seurat)
library(patchwork)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
library(ggplot2)
library(SeuratData)
library(cowplot)
library(SeuratWrappers)
library(RColorBrewer)
library(enrichR)
library(data.table)
library(EnhancedVolcano)

```

```{r}
integrated.TB_DCremoved <- readRDS("robjects/reanalysis_TB_DCremoved_reintegrated_onlyhuman_cellbender.rds")
```

### SPZ vs RBC activated monocytes
```{r}
# SPZ vs RBC only activated monocytes

SPZ_RBC_act.mono_seurat <- subset(integrated.TB_DCremoved, 
                                  subset = (Group %in% c("sporozoite_infected",
                                                         "sporozoite_bystander",
                                                         "RBC_infected",
                                                         "RBC_bystander") &
                                            celltype %in% c("Activated monocytes (NFkb)",
                                                            "Activated non-classical monocytes",
                                                             "Activated monocytes (NFkb + IFN-I)",
                                                            "Activated monocytes (IFN-I)" )))

table(SPZ_RBC_act.mono_seurat$Group, 
      SPZ_RBC_act.mono_seurat$celltype)
```

```{r}
# group together the SPZ conditions and the RBC conditions

SPZ_RBC_act.mono_seurat@meta.data <- SPZ_RBC_act.mono_seurat@meta.data %>% 
  mutate(Stage = case_when(
    Group %in% c("sporozoite_infected", "sporozoite_bystander") ~ "SPZ",
    Group %in% c("RBC_infected", "RBC_bystander") ~ "RBC",
    .default = Group
  ))

table(SPZ_RBC_act.mono_seurat$Stage)

table(SPZ_RBC_act.mono_seurat$Stage, 
      SPZ_RBC_act.mono_seurat$Donorid)
```

```{r}
# first get average expression
pseudo_SPZ_RBC_act.mono <- AggregateExpression(
  SPZ_RBC_act.mono_seurat, 
  assays = "RNA", 
  return.seurat = T, 
  group.by = c("Stage", "Donorid"))

tail(Cells(pseudo_SPZ_RBC_act.mono))

# then, pseudobulk
Idents(pseudo_SPZ_RBC_act.mono) <- "Stage"

pseudo_SPZ_RBC_act.mono.de <- FindMarkers(
   object = pseudo_SPZ_RBC_act.mono, 
   ident.1 = "SPZ", 
   ident.2 = "RBC",
   test.use = "DESeq2",
   only.pos = F)

pseudo_SPZ_RBC_act.mono.de <- pseudo_SPZ_RBC_act.mono.de %>% 
  rownames_to_column("gene")

write.table(pseudo_SPZ_RBC_act.mono.de, 
            "reanalysis_pseudo_SPZ_RBC_act.mono.de.pos.neg_before_removing_DCs.txt", 
            quote = F, 
            row.names = F)
```

```{r}
pseudo_SPZ_RBC_act.mono.de <- na.omit(pseudo_SPZ_RBC_act.mono.de)

svg("reanalysis_SPZ_vs_RBC_act.mono.de.volcano.svg", height = 8, width = 7)
EnhancedVolcano(pseudo_SPZ_RBC_act.mono.de,
  lab = NA,
  x = 'avg_log2FC',
  y = 'p_val_adj',
  ylab = bquote(~-Log[10]~ 'adjusted p-value'),
  #pCutoff = 10e-5,
  #FCcutoff = 1.5,
  pointSize = 3.0,
  boxedLabels = F,
  labSize = NA,
  col=c('grey48', 'grey48', 'grey48', 'red3'),
  colAlpha = 0.7,
  xlim = c(-3.5,3.5),
  title = 'Activated monocytes: iRBC <- vs -> SPZ',
  gridlines.major = FALSE,
  gridlines.minor = FALSE)
dev.off()
```


### SPZ activated vs unactivated monocytes

```{r}
# SPZ monocytes

SPZ_seurat <- subset(integrated.TBremoved, 
                     subset = Group %in% c("sporozoite_infected",
                                           "sporozoite_bystander",
                                           "control"))

table(SPZ_seurat$Group, 
      SPZ_seurat$celltype)
```

```{r}
# group together the SPZ conditions and the celltypes

SPZ_seurat@meta.data <- SPZ_seurat@meta.data %>% 
  mutate(Stage = case_when(
    Group %in% c("sporozoite_infected",
                 "sporozoite_bystander") ~ "SPZ_inf",
    Group %in% c("control") ~ "control",
    .default = Group
  )) %>% 
  mutate(Act_unact = case_when(
    grepl(pattern = "Activated", celltype) ~ "Activated",
    .default = "Unactivated"
  ))

SPZ_seurat <- subset(SPZ_seurat,
                     subset = celltype %in% c("Activated DCs", "DCs"), 
                     invert = T)

table(SPZ_seurat$Stage, 
      SPZ_seurat$Act_unact)

table(SPZ_seurat$Stage, 
      SPZ_seurat$Donorid)
```

```{r}
# first get average expression
pseudo_SPZ <- AggregateExpression(SPZ_seurat, 
                                  assays = "RNA", 
                                  return.seurat = T, 
                                  group.by = c("Stage", "Donorid"))
tail(Cells(pseudo_SPZ))

# then, pseudobulk
Idents(pseudo_SPZ) <- "Stage"

pseudo_SPZ.de <- FindMarkers(object = pseudo_SPZ, 
                         ident.1 = "SPZ-inf", 
                         ident.2 = "control",
                         test.use = "DESeq2",
                         only.pos = F)


pseudo_SPZ.de <- pseudo_SPZ.de %>% 
  rownames_to_column("gene")

write.table(pseudo_SPZ.de, "reanalysis_pseudo_SPZ.de.txt", quote = F, row.names = F)

```

```{r}
# volcano plot

pseudo_SPZ.de <- na.omit(pseudo_SPZ.de)

 svg("reanalysis_pseudo_SPZ.de.volcano.svg", height = 8, width = 7)
 EnhancedVolcano(pseudo_SPZ.de,
    lab = NA,
    x = 'avg_log2FC',
    y = 'p_val_adj',
    ylab = bquote(~-Log[10]~ 'adjusted p-value'),
    #pCutoff = 10e-5,
    #FCcutoff = 1.5,
    pointSize = 3.0,
    boxedLabels = F,
    labSize = NA,
    col=c('grey48', 'grey48', 'grey48', 'red3'),
    colAlpha = 0.7,
    xlim = c(-3.5,3.5),
    title = 'Control <- vs -> Sporozoites',
    gridlines.major = FALSE,
    gridlines.minor = FALSE)
 dev.off()
```

### SPZ infected vs bystander monocytes

```{r}
# SPZ monocytes

SPZinf_seurat <- subset(integrated.TBremoved, 
                        subset = Group %in% c("sporozoite_infected",
                                              "sporozoite_bystander"))

SPZinf_seurat <- subset(SPZinf_seurat, 
                        subset = Celltype %in% c("Activated DCs", "DCs", 
                                                 "Non-classical monocytes", "Classical monocytes",
                                                 "Intermediate/non-classical monocytes",
                                                 "Intermediate monocytes"), 
                        invert = T)


table(SPZinf_seurat$Group, 
      SPZinf_seurat$Celltype)
```

```{r}
# first get average expression
pseudo_SPZinf <- AggregateExpression(SPZinf_seurat, 
                                     assays = "RNA", 
                                     return.seurat = T, 
                                     group.by = c("Group", "Donorid"))
tail(Cells(pseudo_SPZinf))

# then, pseudobulk
Idents(pseudo_SPZinf) <- "Group"

pseudo_SPZinf.de <- FindMarkers(object = pseudo_SPZinf, 
                         ident.1 = "sporozoite-infected", 
                         ident.2 = "sporozoite-bystander",
                         test.use = "DESeq2",
                         only.pos = F)


pseudo_SPZinf.de <- pseudo_SPZinf.de %>% 
  rownames_to_column("gene")

write.table(pseudo_SPZinf.de, 
            "reanalysis_pseudo_SPZ_ActivatedMonocytes_GFPpos_GFPneg.de.txt", 
            quote = F, 
            row.names = F)

```

### RBC unactivated vs activated monocytes

```{r}
# RBC  monocytes

RBC_seurat <- subset(integrated.TBremoved, 
                     subset = Group %in% c("RBC_infected",
                                           "RBC_bystander",
                                           "RBC_control"))

table(RBC_seurat$Group, 
      RBC_seurat$celltype)
```

```{r}
# group together the RBC conditions and the celltypes

RBC_seurat@meta.data <- RBC_seurat@meta.data %>% 
  mutate(Stage = case_when(
    Group %in% c("RBC_infected", 
                 "RBC_bystander") ~ "RBC_inf",
    Group %in% c("RBC_control") ~ "RBC_control",
    .default = Group
  )) %>% 
  mutate(Act_unact = case_when(
    grepl(pattern = "Activated", celltype) ~ "Activated",
    .default = "Unactivated"
  ))

RBC_seurat <- subset(RBC_seurat, 
                     subset = celltype %in% c("Activated DCs", "DCs"), 
                     invert = T)

table(RBC_seurat$Stage, 
      RBC_seurat$Act_unact)

table(RBC_seurat$Stage, 
      RBC_seurat$Donorid)
```

```{r}
# first get average expression
pseudo_RBC <- AggregateExpression(RBC_seurat, 
                                  assays = "RNA", 
                                  return.seurat = T, 
                                  group.by = c("Stage", "Donorid"))
tail(Cells(pseudo_RBC))

# then, pseudobulk
Idents(pseudo_RBC) <- "Stage"

pseudo_RBC.de <- FindMarkers(object = pseudo_RBC, 
                         ident.1 = "RBC-inf", 
                         ident.2 = "RBC-control",
                         test.use = "DESeq2",
                         only.pos = F)

pseudo_RBC.de <- pseudo_RBC.de %>% 
  rownames_to_column("gene")

write.table(pseudo_RBC.de, "reanalysis_pseudo_RBC.de.txt", quote = F, row.names = F)
```

```{r}
# volcano plot
pseudo_RBC.de <- na.omit(pseudo_RBC.de)

svg("reanalysis_pseudo_iRBC_vs_RBC.de.volcano.svg", height = 8, width = 7)
EnhancedVolcano(pseudo_RBC.de,
  lab = NA,
  x = 'avg_log2FC',
  y = 'p_val_adj',
  ylab = bquote(~-Log[10]~ 'adjusted p-value'),
  #pCutoff = 10e-5,
  #FCcutoff = 1.5,
  pointSize = 3.0,
  boxedLabels = F,
  labSize = NA,
  col=c('grey48', 'grey48', 'grey48', 'red3'),
  colAlpha = 0.7,
  xlim = c(-3.5,3.5),
  title = 'RBC <- vs -> iRBC',
  gridlines.major = FALSE,
  gridlines.minor = FALSE)
dev.off()
```


### GFP+ vs GFP- blood stage activated monocytes
```{r}
# GFP+ vs GFP- blood stage activated monocytes

GFPpos_GFPneg_RBC_act.mono_seurat <- subset(integrated.TB_DCremoved, 
                                  subset = (Group %in% c("RBC_infected",
                                                         "RBC_bystander") &
                                            celltype %in% c("Activated monocytes (NFkb)",
                                                            "Activated non-classical monocytes",
                                                             "Activated monocytes (NFkb + IFN-I)",
                                                            "Activated monocytes (IFN-I)" )))

table(GFPpos_GFPneg_RBC_act.mono_seurat$Group, 
      GFPpos_GFPneg_RBC_act.mono_seurat$celltype)
```

```{r}
table(GFPpos_GFPneg_RBC_act.mono_seurat$Group, 
      GFPpos_GFPneg_RBC_act.mono_seurat$Donorid)
```

```{r}
# first get average expression
pseudo_GFPpos_GFPneg_RBC_act.mono <- AggregateExpression(
  GFPpos_GFPneg_RBC_act.mono_seurat, 
  assays = "RNA", 
  return.seurat = T, 
  group.by = c("Group", "Donorid"))

tail(Cells(pseudo_GFPpos_GFPneg_RBC_act.mono))

# then, pseudobulk
Idents(pseudo_GFPpos_GFPneg_RBC_act.mono) <- "Group"

pseudo_GFPpos_GFPneg_RBC_act.mono.de <- FindMarkers(
   object = pseudo_GFPpos_GFPneg_RBC_act.mono, 
   ident.1 = "RBC-infected", 
   ident.2 = "RBC-bystander",
   test.use = "DESeq2",
   only.pos = F)

pseudo_GFPpos_GFPneg_RBC_act.mono.de <- pseudo_GFPpos_GFPneg_RBC_act.mono.de %>% 
  rownames_to_column("gene")

write.table(pseudo_GFPpos_GFPneg_RBC_act.mono.de, 
            "reanalysis_pseudo_GFPpos_GFPneg_RBC_act.mono.de.txt", 
            quote = F, 
            row.names = F)
```
