---
title: "Comparison with mouse data after removing T and B cells"
output:
  html_document:
    df_print: paged
    code_folding: hide
  pdf_document: default
  toc: TRUE
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(fig.width = 10, fig.height = 8) 
```

```{r}
library(Seurat)
library(patchwork)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
library(ggplot2)
library(SeuratData)
#library(celldex)
#install.packages("cowplot")
library(cowplot)
#devtools::install_github('cole-trapnell-lab/monocle3')
library(monocle3)
#remotes::install_github('satijalab/seurat-wrappers')
library(SeuratWrappers)
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(ggrepel)
library(data.table)
library(ComplexHeatmap)
library(msigdbr)
library(heatmap3)
library(presto)
library(fgsea)
library(topGO)
# install.packages("devtools")
# devtools::install_github("saeyslab/nichenetr")
#library(nichenetr)
# mulattoes::install('multtest')
# install.packages('metap')
#library(metap)
#remotes::install_github("satijalab/seurat-data")
```


```{r}
immune.combined <- readRDS("robjects/immune.combined_all_libs_preprocessed.rds")
#immune.combined@assays[["integrated"]]@counts <- immune.combined@assays[["RNA"]]@counts

immune.combined@meta.data <- immune.combined@meta.data %>% 
  mutate(Donorid = case_when(
    orig.ident %in% c("EXP1_l2", "EXP1_l1") & donor_id == "donor0" ~ "D1",
    orig.ident %in% c("EXP1_l2", "EXP1_l1") & donor_id == "donor1" ~ "D2",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor0" ~ "D3",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor1" ~ "D4",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor2" ~ "D5"
  ))
  

immune.combined@meta.data <- immune.combined@meta.data %>% 
  mutate(cellID = "Cell")

immune.combined.TBremoved <- subset(immune.combined, subset = predicted.celltype == "(CD8?) T cells", invert = T)
immune.combined.TBremoved <- subset(immune.combined.TBremoved, subset = predicted.celltype == "(CD8?) T cells II", invert = T)
immune.combined.TBremoved <- subset(immune.combined.TBremoved, subset = predicted.celltype == "(CD8?) T cells III", invert = T)
immune.combined.TBremoved <- subset(immune.combined.TBremoved, subset = predicted.celltype == "B cells", invert = T)

saveRDS(immune.combined.TBremoved, "robjects/immune.combined.TBremoved.human.rds")
```

```{r}

DefaultAssay(immune.combined.TBremoved) <- "RNA"

immune.combined.TBremoved.list <- SplitObject(immune.combined.TBremoved, split.by = "orig.ident")
immune.combined.TBremoved.list <- lapply(X = immune.combined.TBremoved.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
features <- SelectIntegrationFeatures(object.list = immune.combined.TBremoved.list)
anchors <- FindIntegrationAnchors(object.list = immune.combined.TBremoved.list, anchor.features = features)

# set k.weight so that it is not larger than the number of cells in the smallest dataset
# https://github.com/satijalab/seurat/issues/3936
immune.combined.TBremoved <- IntegrateData(anchorset = anchors, k.weight = 46)
DefaultAssay(immune.combined.TBremoved) <- "integrated"

immune.combined.TBremoved <- ScaleData(immune.combined.TBremoved, verbose = FALSE)
immune.combined.TBremoved <- RunPCA(immune.combined.TBremoved, npcs = 30, verbose = FALSE)
immune.combined.TBremoved <- RunUMAP(immune.combined.TBremoved, reduction = "pca", dims = 1:10)
immune.combined.TBremoved <- FindNeighbors(immune.combined.TBremoved, reduction = "pca", dims = 1:10)
immune.combined.TBremoved <- FindClusters(immune.combined.TBremoved, resolution = 0.5)


```

<!-- ```{r} -->
<!-- immune.combined.TBremoved <- immune.combined.TBremoved %>%  -->
<!--   NormalizeData(., normalization.method = "LogNormalize", scale.factor = 2000) %>%  -->
<!--   FindVariableFeatures(., selection.method = "vst", nfeatures = 2000) %>%  -->
<!--   ScaleData(., features = rownames(.)) %>%  -->
<!--   RunPCA(., features = VariableFeatures(object = .)) %>%  -->
<!--   RunUMAP(., dims = 1:20) %>%  -->
<!--   FindNeighbors(., dims = 1:20) %>%  -->
<!--   FindClusters(., resolution = 0.9) -->

<!-- ``` -->
# Experiment
```{r}
DefaultAssay(immune.combined.TBremoved) <- "RNA"
DimPlot(immune.combined.TBremoved, group.by = "orig.ident", reduction = "umap", label = "F")#
```

# Tagged antibody distribution
```{r}
DimPlot(immune.combined.TBremoved, group.by = "HTO_classification", reduction = "umap", label = "T")#
```

# donor ID
```{r}
DimPlot(immune.combined.TBremoved, group.by = "Donorid",reduction = "umap", label = "F")
```

# XIST gene distribution - showing separation based on sex. XIST is not expressed in males.
```{r}
DefaultAssay(immune.combined.TBremoved) <- "RNA"
FeaturePlot(immune.combined.TBremoved, features = c("XIST"))
```

# CD14 and FCGR3A
```{r}
FeaturePlot(immune.combined.TBremoved, features = c("CD14", "FCGR3A"))
```

# KLF4, IRF4, BATF3
```{r}
p1 <- FeaturePlot(immune.combined.TBremoved, features = c("KLF4", "BATF3", "IRF4"), combine = F)
fix.sc <- scale_color_gradientn( colours = c('lightgrey', 'blue'),  limits = c(0, 3))

p2 <- lapply(p1, function (x) x + fix.sc)
CombinePlots(p2)
```

# Condition
```{r}
#DimPlot(immune.combined.TBremoved, group.by = "Group",reduction = "umap", label = "F", cols = viridis_pal(option = "D")(length(unique(immune.combined.TBremoved$Group))))

group_cols = c('control' = '#e6af2e', 'RBC_bystander' = '#f7a78d', 'RBC_control' = '#ef4f1a', 'RBC_infected' = '#6b0504', 'sporozoite_bystander' = '#c2fff0', 'sporozoite_infected' = '#00a39b')

#pdf("Conditions_col.pdf", width = 12, height = 12)
DimPlot(immune.combined.TBremoved, group.by = "Group",reduction = "umap", label = "F", cols = group_cols) + ggtitle("Conditions")
#dev.off()

Idents(immune.combined.TBremoved) <- "Group"
# spz_inf <- CellsByIdentities(immune.combined.TBremoved, idents = "sporozoite_infected")
# spz_bys <- CellsByIdentities(immune.combined.TBremoved, idents = "sporozoite_bystander")
# control <- CellsByIdentities(immune.combined.TBremoved, idents = "control")

spz_inf <- WhichCells(immune.combined.TBremoved, idents = "sporozoite_infected")
spz_bys <- WhichCells(immune.combined.TBremoved, idents = "sporozoite_bystander")
control <- WhichCells(immune.combined.TBremoved, idents = "control")

p1 <- DimPlot(immune.combined.TBremoved, label = F, pt.size = 0.01,
              group.by = "Group",
        cells.highlight = list(spz_inf, spz_bys, control), 
        sizes.highlight = 0.01,
        cols.highlight = c("yellow2", "black", "green"), cols = "gray80") +
  ggtitle("Sporozoite conditions")

rbc_inf <- WhichCells(immune.combined.TBremoved, idents = "RBC_infected")
rbc_bys <- WhichCells(immune.combined.TBremoved, idents = "RBC_bystander")
rbc_control <- WhichCells(immune.combined.TBremoved, idents = "RBC_control")

p2 <- DimPlot(immune.combined.TBremoved, label = F, pt.size = 0.01,
              group.by = "Group",
        cells.highlight = list(rbc_inf, rbc_bys, rbc_control), 
        sizes.highlight = 0.01,
        cols.highlight = c("yellow2", "black", "green"), cols = "gray80") +
  ggtitle("RBC conditions")

pdf("conditions_separated_SPZ_RBC.pdf")
p1 / p2
dev.off()
```

# Clusters
```{r}
#svg("Seurat_clusters_number_celltype.svg", width = 12, height = 12)
DimPlot(immune.combined.TBremoved, group.by = "seurat_clusters",reduction = "umap", label = "T")
#dev.off()
```

# Celltype
```{r}
immune.combined.TBremoved@meta.data <- immune.combined.TBremoved@meta.data %>% 
  dplyr::select(-contains("predicted.celltype"))
immune.combined.TBremoved[["prediction.score.celltype.l1"]] <- NULL
immune.combined.TBremoved[["prediction.score.celltype.l2"]] <- NULL
immune.combined.TBremoved[["prediction.score.celltype.l3"]] <- NULL
Idents(immune.combined.TBremoved) <- "seurat_clusters"

immune.combined.TBremoved <- RenameIdents(immune.combined.TBremoved, 
                                `0` = "Classical Monocytes I (FOS)", 
                                `1` = "Activated Monocytes I (IL1B, CXCL1/2)", 
                                `2` = "Classical Monocytes II (STAT1)",
                                `3` = "Activated Monocytes II (ISGs)",
                                `4` = "Classical Monocytes III", 
                                `5` = "Activates Monocytes III (IL12, CD40, TNF)",
                                `6` = "Classical Monocytes IV (CCL24)",
                                `7` = "Classical Monocytes V (LGMN)",
                                `8` = "Non-classical Monocytes",
                                `9` = "cDC1",
                                `10` = "Intermediate Monocytes", 
                                `11` = "Activated Intermediate Monocytes"
                                )

immune.combined.TBremoved@active.ident <- Idents(immune.combined.TBremoved)

immune.combined.TBremoved@meta.data$predicted.celltype <- immune.combined.TBremoved@active.ident

DimPlot(immune.combined.TBremoved, label = TRUE)
svg("Celltypes.svg", width = 12, height = 12)
DimPlot(immune.combined.TBremoved, group.by = "predicted.celltype",reduction = "umap", label = "T")
dev.off()
```


# Top 10 markers in each cluster
```{r}
imm.comb.markers <- FindAllMarkers(immune.combined.TBremoved, only.pos = F, min.pct = 0.25, logfc.threshold = 0.25)
imm.comb.markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = avg_log2FC) -> top10

DT::datatable(top10)

#write.csv2(top10, "integrated_data_noTBcells_cluster_markers.csv", row.names = F, quote = F)
DefaultAssay(immune.combined.TBremoved) <- "integrated"
#pdf("Heatmap_gene_expr_integrated_data_noTBcells.pdf")
DoHeatmap(immune.combined.TBremoved, features = top10$gene) + NoLegend() + theme(text = element_text(size = 6.5))
#dev.off()

top10 %>%
    group_by(cluster) %>%
    top_n(n = 5, wt = avg_log2FC) -> top5
myDotPlot(immune.combined.TBremoved, features = unique(top5$gene),  dot.scale = 5, text.size = 7) + RotatedAxis()


```

# Percentage celltype in different conditions
```{r}
immune.combined.TBremoved@meta.data <- immune.combined.TBremoved@meta.data %>% 
  mutate(condition_donor = paste(Group, Donorid, sep = "_"))

celltype_condition_percent <- immune.combined.TBremoved@meta.data %>% 
  group_by(Group, predicted.celltype) %>% 
  summarise(n = n()) %>% 
  mutate(freq = 100*n/sum(n)) %>% 
  dplyr::select(-n) %>% 
  pivot_wider(names_from = Group, values_from = freq) %>% 
  column_to_rownames("predicted.celltype")

DT::datatable(celltype_condition_percent)

write.csv2(celltype_condition_percent, "Condition_celltype_percent.csv", row.names = T, quote = F)

celltype_condition_donor_percent <- immune.combined.TBremoved@meta.data %>% 
  group_by(condition_donor, predicted.celltype) %>% 
  summarise(n = n()) %>% 
  mutate(freq = 100*n/sum(n)) %>% 
  dplyr::select(-n) %>% 
  pivot_wider(names_from = condition_donor, values_from = freq) %>% 
  column_to_rownames("predicted.celltype")

write.csv2(celltype_condition_donor_percent, "Condition_donor_celltype_percent.csv", row.names = T, quote = F)
```

<!-- ```{r} -->

<!-- immune.combined.TBremoved@meta.data$cond_group <- paste(immune.combined.TBremoved@meta.data$Group, -->
<!--                                                immune.combined.TBremoved@meta.data$Donorid, -->
<!--                                                sep = "") -->

<!-- cts <- AggregateExpression(immune.combined.TBremoved, -->
<!--               group.by = c("cellID", "cond_group"), -->
<!--               assays = "RNA", -->
<!--               slot = "counts", -->
<!--               return.seurat = F) -->
<!-- cts <- cts$RNA -->


<!-- ``` -->


<!-- ```{r} -->

<!-- # Monocytes activated (type I IFN signature) -->
<!-- # Run DE analysis -->
<!-- # 1. Get counts matrix -->

<!-- de_function <- function(condition1, condition2, padj_thr_sc) -->
<!-- { -->
<!--   padj_thr_sc <- padj_thr_sc -->

<!--   counts_classmonocytes <- cts %>%  -->
<!--   as.data.frame() %>%  -->
<!--   dplyr::select(c(starts_with(condition1), starts_with(condition2))) -->

<!--   # 2 Generate metadata -->
<!--   colData <- data.frame(sample = colnames(counts_classmonocytes)) -->
<!--   colData$condition = sapply(str_split(colData$sample, "D"), function(x) x[1]) -->
<!--   colData <- colData %>%  -->
<!--     tibble::column_to_rownames("sample") -->

<!--   # more info for metadata -->

<!--   # DEseq2 object -->
<!--   dds <- DESeqDataSetFromMatrix(countData = counts_classmonocytes, -->
<!--                                colData = colData, -->
<!--                                design = ~condition) -->


<!--   # filter dds -->
<!--   keep <- rowSums(counts(dds)) >= 10 -->
<!--   dds <- dds[keep,] -->

<!--   dds$condition <- relevel(dds$condition, ref = condition1) -->

<!--   dds <- DESeq(dds) -->

<!--   comparison <- resultsNames(dds)[2] -->

<!--   res <- results(dds, name = comparison, alpha = padj_thr_sc) -->

<!--   # Turn the DESeq2 results object into a tibble for use with tidyverse functions -->
<!--   res_tbl <- res %>% -->
<!--     data.frame() %>% -->
<!--     rownames_to_column(var = "gene") %>% -->
<!--     as_tibble() %>% -->
<!--     dplyr::arrange(pvalue) -->


<!--   #### -->

<!--   # Subset the significant results -->
<!--   sig_res <- dplyr::filter(res_tbl, padj <= padj_thr_sc) %>% -->
<!--     dplyr::arrange(padj) -->

<!--   # Check significant genes output -->
<!--   sig_res -->

<!--   ## Extract normalized counts from dds object -->
<!--   normalized_counts <- counts(dds, normalized = TRUE) -->

<!--   ## Extract normalized counts for significant genes only -->
<!--   sig_counts <- normalized_counts[rownames(normalized_counts) %in% sig_res$gene, ] -->


<!--   return(list(dds,sig_counts, sig_res)) -->

<!-- } -->

<!-- convertMouseGeneList <- function(x){ -->
<!-- require("biomaRt") -->
<!-- human = useMart("ensembl", dataset = "hsapiens_gene_ensembl", host = "dec2021.archive.ensembl.org") -->
<!-- mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl", host = "dec2021.archive.ensembl.org") -->
<!-- genesV2 = getLDS(attributes = c("mgi_symbol"), filters = "mgi_symbol", values = x , mart = mouse, attributesL = c("hgnc_symbol"), martL = human, uniqueRows=T) -->
<!-- humanx <- unique(genesV2[, 2]) -->
<!-- return(humanx) -->
<!-- } -->

<!-- bulkRNAseq_comparison <- function(file, condition1, condition2, padj_thr_bulk, padj_thr_sc, logFC_thr) -->
<!-- { -->
<!--   # bulk -->
<!--   bulk_table <- read.csv(paste0("../Data/", file, collapse = '')) -->
<!--   table_genes <- bulk_table %>%  -->
<!--     filter(abs(log2FoldChange) >= logFC_thr) %>%  -->
<!--     filter(padj <= padj_thr_bulk)  -->

<!--   bulk_pos <- table_genes %>%  -->
<!--     filter(log2FoldChange >= 0) -->

<!--   bulk_neg <- table_genes %>%  -->
<!--     filter(log2FoldChange < 0) -->

<!--   table_genes_pos <- bulk_pos %>%  -->
<!--     pull(GeneSymbol) -->

<!--   table_genes_neg <- bulk_neg %>%  -->
<!--     pull(GeneSymbol) -->

<!--   humangenes_pos <- convertMouseGeneList(table_genes_pos) -->

<!--   humangenes_neg <- convertMouseGeneList(table_genes_neg) -->


<!--   # scRNAseq -->
<!--   scRNA_pseudobulk_list <- de_function(condition1 = condition1,  -->
<!--                                         condition2 = condition2, -->
<!--                                        padj_thr_sc = padj_thr_sc -->
<!--                                         #celltype = celltype, -->
<!--                                         #geneset = table_genes_v -->
<!--                                        ) -->

<!--   dds <- scRNA_pseudobulk_list[[1]] -->
<!--   sig.genes_table <- scRNA_pseudobulk_list[[2]] -->

<!--   sig.genes_pvalue_pos <- scRNA_pseudobulk_list[[3]] %>%  -->
<!--     filter(log2FoldChange >= 0) %>%  -->
<!--     left_join(data.frame(gene = humangenes_pos),.) %>%  -->
<!--     na.omit() %>%  -->
<!--     arrange(padj) -->

<!--   sig.genes_pvalue_neg <- scRNA_pseudobulk_list[[3]] %>%  -->
<!--     filter(log2FoldChange < 0) %>%  -->
<!--     left_join(data.frame(gene = humangenes_neg),.) %>%  -->
<!--     na.omit()%>%  -->
<!--     arrange(padj) -->

<!--   # getting genes common to bulk data -->
<!--   sig.genes_table_pos <- sig.genes_table %>%  -->
<!--     as.data.frame() %>%  -->
<!--     rownames_to_column("Gene") %>%  -->
<!--     filter(Gene %in% sig.genes_pvalue_pos$gene) %>%  -->
<!--     column_to_rownames("Gene") -->

<!--   sig.genes_table_neg <- sig.genes_table %>%  -->
<!--     as.data.frame() %>%  -->
<!--     rownames_to_column("Gene") %>%  -->
<!--     filter(Gene %in% sig.genes_pvalue_neg$gene) %>%  -->
<!--     column_to_rownames("Gene") -->


<!--   vsd <- assay(vst(dds,  -->
<!--            nsub = sum( rowMeans( counts(dds, normalized=TRUE)) > 5 ))) -->
<!--   z <- t(scale(t(vsd))) -->
<!--   z_pos <- z[rownames(z) %in% rownames(sig.genes_table_pos),] -->
<!--   z_neg <- z[rownames(z) %in% rownames(sig.genes_table_neg),] -->

<!--   #return(list(bulktable_genes = table_genes, z = z, sig.genes_exp = sig.genes_table, sig_genes_pvalue = sig.genes_pvalue)) -->

<!--   return(list(bulktable_genes = table_genes, z_pos = z_pos, z_neg = z_neg, sig.genes_exp_pos = sig.genes_table_pos, sig.genes_exp_neg = sig.genes_table_neg, sig_genes_pvalue_pos = sig.genes_pvalue_pos, sig_genes_pvalue_neg = sig.genes_pvalue_neg)) -->
<!-- } -->

<!-- heat_colors <- rev(brewer.pal(11, "PuOr")) -->

<!-- gsea <- function(category, deg) -->
<!-- { -->
<!--   m_df<- msigdbr(species = "Homo sapiens", category = category) -->
<!--   fgsea_sets<- m_df %>% split(x = .$gene_symbol, f = .$gs_name) -->

<!--   gene_logFC_rank <- deg[,c("gene", "log2FoldChange")] %>%  -->
<!--     arrange(-log2FoldChange) %>%  -->
<!--     deframe(.) -->

<!--   fgseaRes<- fgsea(fgsea_sets, stats = gene_logFC_rank, nperm = 1000) -->

<!--   fgseaResTidy <- fgseaRes %>% -->
<!--   as_tibble() %>% -->
<!--   arrange(desc(NES)) -->

<!--   return(list(fgsea_sets = fgsea_sets, gene_logFC_rank = gene_logFC_rank, fgseaResTidy = fgseaResTidy)) -->
<!-- } -->

<!-- ``` -->

<!-- # All cells -->

<!-- ## Sporozoite_infected vs control (base) -->

<!-- ```{r} -->

<!-- SPZ_GFPpos_vs_untr <- bulkRNAseq_comparison(file = "SPZ-GFPpos_untr_df_4h.csv", -->
<!--                                             condition1 = "control", -->
<!--                                             condition2 = "sporozoite_infected", -->
<!--                                             #celltype = "Activated monocytes", -->
<!--                                             padj_thr_bulk = 0.1, -->
<!--                                             padj_thr_sc = 0.1, -->
<!--                                             logFC_thr = 2) -->
<!-- DT::datatable(SPZ_GFPpos_vs_untr[["bulktable_genes"]]) -->

<!-- DT::datatable(SPZ_GFPpos_vs_untr[["sig_genes_pvalue_pos"]])   -->

<!-- DT::datatable(SPZ_GFPpos_vs_untr[["sig_genes_pvalue_neg"]])   -->


<!-- z_pos <- SPZ_GFPpos_vs_untr[["z_pos"]] %>%  -->
<!--   as.data.frame() %>%  -->
<!--   tibble::rownames_to_column("gene") %>% -->
<!--   left_join(data.frame(gene = SPZ_GFPpos_vs_untr[["sig_genes_pvalue_pos"]][,"gene"]),.) %>% -->
<!--   tibble::column_to_rownames("gene") -->

<!-- z_neg <- SPZ_GFPpos_vs_untr[["z_neg"]] %>%  -->
<!--   as.data.frame() %>%  -->
<!--   tibble::rownames_to_column("gene") %>% -->
<!--   left_join(data.frame(gene = SPZ_GFPpos_vs_untr[["sig_genes_pvalue_neg"]][,"gene"]),.) %>% -->
<!--   tibble::column_to_rownames("gene") -->

<!-- png("SPZpos_vs_untr_heatmap_up.png", res = 300, width = 15, height = 20, units = "cm") -->
<!-- Heatmap(z_pos[1:60,], name = "z-score",  -->
<!--         width = ncol(z_pos)*unit(5, "mm"),  -->
<!--         height = 60*unit(2.5, "mm"), -->
<!--         col = heat_colors,  -->
<!--         cluster_rows= T, cluster_columns = T,  -->
<!--         show_column_dend = T, show_row_dend = F,  -->
<!--         show_row_names = T,  -->
<!--         row_names_gp = gpar(fontsize = 5), -->
<!--         column_names_side = "top", column_names_rot = 45,  -->
<!--         column_names_gp = gpar(fontsize = 6), -->
<!--         #row_km = 2,  -->
<!--         column_km = 2, border = TRUE,  -->
<!--         column_title = NULL, row_title = NULL,  -->
<!--         border_gp = gpar(col = "darkgrey")) -->
<!-- dev.off() -->

<!-- png("SPZpos_vs_untr_heatmap_dn.png", res = 300, width = 15, height = 20, units = "cm") -->
<!-- Heatmap(z_neg, name = "z-score",  -->
<!--         width = ncol(z_neg)*unit(5, "mm"),  -->
<!--         height = nrow(z_neg)*unit(2.5, "mm"), -->
<!--         col = heat_colors,  -->
<!--         cluster_rows= T, cluster_columns = T,  -->
<!--         show_column_dend = T, show_row_dend = F,  -->
<!--         show_row_names = T,  -->
<!--         row_names_gp = gpar(fontsize = 5), -->
<!--         column_names_side = "top", column_names_rot = 45,  -->
<!--         column_names_gp = gpar(fontsize = 6), -->
<!--         #row_km = 2,  -->
<!--         column_km = 2, border = TRUE,  -->
<!--         column_title = NULL, row_title = NULL,  -->
<!--         border_gp = gpar(col = "darkgrey")) -->
<!-- dev.off() -->

<!-- ## fgsea -->

<!-- # C2 -->

<!-- fgsea_SPZ_GFPpos_vs_untr_C2 <- gsea(category = "C2", deg = rbind(SPZ_GFPpos_vs_untr[["sig_genes_pvalue_pos"]], SPZ_GFPpos_vs_untr[["sig_genes_pvalue_neg"]])) -->

<!-- DT::datatable(fgsea_SPZ_GFPpos_vs_untr_C2[["fgseaResTidy"]]) -->

<!-- ggplot(fgsea_SPZ_GFPpos_vs_untr_C2[["fgseaResTidy"]] %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) + -->
<!--   geom_col(aes(fill= NES)) + -->
<!--   coord_flip() + -->
<!--   labs(x="Pathway", y="Normalized Enrichment Score", -->
<!--        title="Hallmark pathways NES from GSEA") + -->
<!--   theme_minimal() -->

<!-- plotEnrichment(fgsea_SPZ_GFPpos_vs_untr_C2[["fgsea_sets"]][["REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN"]], -->
<!--                fgsea_SPZ_GFPpos_vs_untr_C2[["gene_logFC_rank"]]) + labs(title="REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN") -->

<!-- plotEnrichment(fgsea_SPZ_GFPpos_vs_untr_C2[["fgsea_sets"]][["REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON"]], -->
<!--                fgsea_SPZ_GFPpos_vs_untr_C2[["gene_logFC_rank"]]) + labs(title="REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON") -->

<!-- # C5 -->

<!-- fgsea_SPZ_GFPpos_vs_untr_C5 <- gsea(category = "C5", deg = rbind(SPZ_GFPpos_vs_untr[["sig_genes_pvalue_pos"]], SPZ_GFPpos_vs_untr[["sig_genes_pvalue_neg"]])) -->

<!-- DT::datatable(fgsea_SPZ_GFPpos_vs_untr_C5[["fgseaResTidy"]]) -->

<!-- ggplot(fgsea_SPZ_GFPpos_vs_untr_C5[["fgseaResTidy"]] %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) + -->
<!--   geom_col(aes(fill= NES)) + -->
<!--   coord_flip() + -->
<!--   labs(x="Pathway", y="Normalized Enrichment Score", -->
<!--        title="Hallmark pathways NES from GSEA") + -->
<!--   theme_minimal() -->

<!-- plotEnrichment(fgsea_SPZ_GFPpos_vs_untr_C5[["fgsea_sets"]][["GOBP_RESPONSE_TO_WOUNDING"]], -->
<!--                fgsea_SPZ_GFPpos_vs_untr_C5[["gene_logFC_rank"]]) + labs(title="GOBP_RESPONSE_TO_WOUNDING") -->


<!-- ``` -->

<!-- # Sporozoite bystander vs untreated -->

<!-- ```{r} -->

<!-- SPZ_GFPneg_vs_untr <- bulkRNAseq_comparison(file = "SPZ-GFPneg_untr_df_4h.csv", -->
<!--                                             condition1 = "control", -->
<!--                                             condition2 = "sporozoite_bystander", -->
<!--                                             #celltype = "Activated monocytes", -->
<!--                                             padj_thr_bulk = 0.1, -->
<!--                                             padj_thr_sc = 0.1, -->
<!--                                             logFC_thr = 2) -->

<!-- DT::datatable(SPZ_GFPneg_vs_untr[["bulktable_genes"]]) -->

<!-- DT::datatable(SPZ_GFPneg_vs_untr[["sig_genes_pvalue_pos"]])   -->

<!-- DT::datatable(SPZ_GFPneg_vs_untr[["sig_genes_pvalue_neg"]])   -->


<!-- z_pos <- SPZ_GFPneg_vs_untr[["z_pos"]] %>%  -->
<!--   as.data.frame() %>%  -->
<!--   tibble::rownames_to_column("gene") %>% -->
<!--   left_join(data.frame(gene = SPZ_GFPneg_vs_untr[["sig_genes_pvalue_pos"]][,"gene"]),.) %>% -->
<!--   tibble::column_to_rownames("gene") -->

<!-- z_neg <- SPZ_GFPneg_vs_untr[["z_neg"]] %>%  -->
<!--   as.data.frame() %>%  -->
<!--   tibble::rownames_to_column("gene") %>% -->
<!--   left_join(data.frame(gene = SPZ_GFPneg_vs_untr[["sig_genes_pvalue_neg"]][,"gene"]),.) %>% -->
<!--   tibble::column_to_rownames("gene") -->

<!-- png("SPZneg_vs_untr_heatmap_up.png", res = 300, width = 15, height = 20, units = "cm") -->
<!-- Heatmap(z_pos[1:60,], name = "z-score",  -->
<!--         width = ncol(z_pos)*unit(5, "mm"),  -->
<!--         height = 60*unit(2.5, "mm"), -->
<!--         col = heat_colors,  -->
<!--         cluster_rows= T, cluster_columns = T,  -->
<!--         show_column_dend = T, show_row_dend = F,  -->
<!--         show_row_names = T,  -->
<!--         row_names_gp = gpar(fontsize = 5), -->
<!--         column_names_side = "top", column_names_rot = 45,  -->
<!--         column_names_gp = gpar(fontsize = 6), -->
<!--         #row_km = 2,  -->
<!--         column_km = 2, border = TRUE,  -->
<!--         column_title = NULL, row_title = NULL,  -->
<!--         border_gp = gpar(col = "darkgrey")) -->
<!-- dev.off() -->

<!-- png("SPZneg_vs_untr_heatmap_dn.png", res = 300, width = 15, height = 20, units = "cm") -->
<!-- Heatmap(z_neg, name = "z-score",  -->
<!--         width = ncol(z_neg)*unit(5, "mm"),  -->
<!--         height = nrow(z_neg)*unit(2.5, "mm"), -->
<!--         col = heat_colors,  -->
<!--         cluster_rows= T, cluster_columns = T,  -->
<!--         show_column_dend = T, show_row_dend = F,  -->
<!--         show_row_names = T,  -->
<!--         row_names_gp = gpar(fontsize = 5), -->
<!--         column_names_side = "top", column_names_rot = 45,  -->
<!--         column_names_gp = gpar(fontsize = 6), -->
<!--         #row_km = 2,  -->
<!--         column_km = 2, border = TRUE,  -->
<!--         column_title = NULL, row_title = NULL,  -->
<!--         border_gp = gpar(col = "darkgrey")) -->
<!-- dev.off() -->

<!-- ## fgsea -->

<!-- # C2 -->

<!-- fgsea_SPZ_GFPneg_vs_untr_C2 <- gsea(category = "C2", deg = rbind(SPZ_GFPneg_vs_untr[["sig_genes_pvalue_pos"]], SPZ_GFPneg_vs_untr[["sig_genes_pvalue_neg"]])) -->

<!-- DT::datatable(fgsea_SPZ_GFPneg_vs_untr_C2[["fgseaResTidy"]]) -->

<!-- ggplot(fgsea_SPZ_GFPneg_vs_untr_C2[["fgseaResTidy"]] %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) + -->
<!--   geom_col(aes(fill= NES)) + -->
<!--   coord_flip() + -->
<!--   labs(x="Pathway", y="Normalized Enrichment Score", -->
<!--        title="Hallmark pathways NES from GSEA") + -->
<!--   theme_minimal() -->

<!-- plotEnrichment(fgsea_SPZ_GFPneg_vs_untr_C2[["fgsea_sets"]][["REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN"]], -->
<!--                fgsea_SPZ_GFPneg_vs_untr_C2[["gene_logFC_rank"]]) + labs(title="REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN") -->

<!-- plotEnrichment(fgsea_SPZ_GFPneg_vs_untr_C2[["fgsea_sets"]][["REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON"]], -->
<!--                fgsea_SPZ_GFPneg_vs_untr_C2[["gene_logFC_rank"]]) + labs(title="REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON") -->

<!-- # C5 -->

<!-- fgsea_SPZ_GFPneg_vs_untr_C5 <- gsea(category = "C5", deg = rbind(SPZ_GFPneg_vs_untr[["sig_genes_pvalue_pos"]], SPZ_GFPneg_vs_untr[["sig_genes_pvalue_neg"]])) -->

<!-- DT::datatable(fgsea_SPZ_GFPneg_vs_untr_C5[["fgseaResTidy"]]) -->

<!-- ggplot(fgsea_SPZ_GFPneg_vs_untr_C5[["fgseaResTidy"]] %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) + -->
<!--   geom_col(aes(fill= NES)) + -->
<!--   coord_flip() + -->
<!--   labs(x="Pathway", y="Normalized Enrichment Score", -->
<!--        title="Hallmark pathways NES from GSEA") + -->
<!--   theme_minimal() -->

<!-- plotEnrichment(fgsea_SPZ_GFPneg_vs_untr_C5[["fgsea_sets"]][["GOBP_RESPONSE_TO_WOUNDING"]], -->
<!--                fgsea_SPZ_GFPneg_vs_untr_C5[["gene_logFC_rank"]]) + labs(title="GOBP_RESPONSE_TO_WOUNDING") -->
<!-- ``` -->

<!-- # SPZ vs iRBC -->

<!-- ```{r} -->
<!-- SPZ_vs_iRBC <- bulkRNAseq_comparison(file = "SPZ-iRBC_df_4h.csv", -->
<!--                                             condition1 = "RBC_infected", -->
<!--                                             condition2 = "sporozoite_infected", -->
<!--                                             #celltype = "Activated monocytes", -->
<!--                                             padj_thr_bulk = 0.1, -->
<!--                                             padj_thr_sc = 0.1, -->
<!--                                             logFC_thr = 1.5) -->

<!-- DT::datatable(SPZ_vs_iRBC[["bulktable_genes"]]) -->

<!-- DT::datatable(SPZ_vs_iRBC[["sig_genes_pvalue_pos"]])   -->

<!-- DT::datatable(SPZ_vs_iRBC[["sig_genes_pvalue_neg"]])   -->


<!-- z_pos <- SPZ_vs_iRBC[["z_pos"]] %>%  -->
<!--   as.data.frame() %>%  -->
<!--   tibble::rownames_to_column("gene") %>% -->
<!--   left_join(data.frame(gene = SPZ_vs_iRBC[["sig_genes_pvalue_pos"]][,"gene"]),.) %>% -->
<!--   tibble::column_to_rownames("gene") -->

<!-- z_neg <- SPZ_vs_iRBC[["z_neg"]] %>%  -->
<!--   as.data.frame() %>%  -->
<!--   tibble::rownames_to_column("gene") %>% -->
<!--   left_join(data.frame(gene = SPZ_vs_iRBC[["sig_genes_pvalue_neg"]][,"gene"]),.) %>% -->
<!--   tibble::column_to_rownames("gene") -->

<!-- png("SPZ_vs_iRBC_heatmap_up.png", res = 300, width = 15, height = 20, units = "cm") -->
<!-- Heatmap(z_pos, name = "z-score",  -->
<!--         width = ncol(z_pos)*unit(5, "mm"),  -->
<!--         height = 60*unit(2.5, "mm"), -->
<!--         col = heat_colors,  -->
<!--         cluster_rows= T, cluster_columns = T,  -->
<!--         show_column_dend = T, show_row_dend = F,  -->
<!--         show_row_names = T,  -->
<!--         row_names_gp = gpar(fontsize = 8), -->
<!--         column_names_side = "top", column_names_rot = 45,  -->
<!--         column_names_gp = gpar(fontsize = 6), -->
<!--         #row_km = 2,  -->
<!--         column_km = 2, border = TRUE,  -->
<!--         column_title = NULL, row_title = NULL,  -->
<!--         border_gp = gpar(col = "darkgrey")) -->
<!-- dev.off() -->

<!-- png("SPZ_vs_iRBC_heatmap_dn.png", res = 300, width = 15, height = 20, units = "cm") -->
<!-- Heatmap(z_neg, name = "z-score",  -->
<!--         width = ncol(z_neg)*unit(5, "mm"),  -->
<!--         height = nrow(z_neg)*unit(2.5, "mm"), -->
<!--         col = heat_colors,  -->
<!--         cluster_rows= T, cluster_columns = T,  -->
<!--         show_column_dend = T, show_row_dend = F,  -->
<!--         show_row_names = T,  -->
<!--         row_names_gp = gpar(fontsize = 5), -->
<!--         column_names_side = "top", column_names_rot = 45,  -->
<!--         column_names_gp = gpar(fontsize = 6), -->
<!--         #row_km = 2,  -->
<!--         column_km = 2, border = TRUE,  -->
<!--         column_title = NULL, row_title = NULL,  -->
<!--         border_gp = gpar(col = "darkgrey")) -->
<!-- dev.off() -->
<!-- # C2 -->

<!-- fgsea_SPZ_vs_iRBC_C2 <- gsea(category = "C2", deg = rbind(SPZ_vs_iRBC[["sig_genes_pvalue_pos"]], SPZ_vs_iRBC[["sig_genes_pvalue_neg"]])) -->

<!-- DT::datatable(fgsea_SPZ_vs_iRBC_C2[["fgseaResTidy"]]) -->

<!-- ggplot(fgsea_SPZ_vs_iRBC_C2[["fgseaResTidy"]] %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) + -->
<!--   geom_col(aes(fill= NES)) + -->
<!--   coord_flip() + -->
<!--   labs(x="Pathway", y="Normalized Enrichment Score", -->
<!--        title="Hallmark pathways NES from GSEA") + -->
<!--   theme_minimal() -->

<!-- plotEnrichment(fgsea_SPZ_vs_iRBC_C2[["fgsea_sets"]][["REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN"]], -->
<!--                fgsea_SPZ_vs_iRBC_C2[["gene_logFC_rank"]]) + labs(title="REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN") -->

<!-- plotEnrichment(fgsea_SPZ_vs_iRBC_C2[["fgsea_sets"]][["REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON"]], -->
<!--                fgsea_SPZ_vs_iRBC_C2[["gene_logFC_rank"]]) + labs(title="REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON") -->

<!-- # C5 -->

<!-- fgsea_SPZ_vs_iRBC_C5 <- gsea(category = "C5", deg = rbind(SPZ_vs_iRBC[["sig_genes_pvalue_pos"]], SPZ_vs_iRBC[["sig_genes_pvalue_neg"]])) -->

<!-- DT::datatable(fgsea_SPZ_vs_iRBC_C5[["fgseaResTidy"]]) -->

<!-- ggplot(fgsea_SPZ_vs_iRBC_C5[["fgseaResTidy"]] %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) + -->
<!--   geom_col(aes(fill= NES)) + -->
<!--   coord_flip() + -->
<!--   labs(x="Pathway", y="Normalized Enrichment Score", -->
<!--        title="Hallmark pathways NES from GSEA") + -->
<!--   theme_minimal() -->

<!-- plotEnrichment(fgsea_SPZ_vs_iRBC_C5[["fgsea_sets"]][["GOBP_RESPONSE_TO_WOUNDING"]], -->
<!--                fgsea_SPZ_vs_iRBC_C5[["gene_logFC_rank"]]) + labs(title="GOBP_RESPONSE_TO_WOUNDING") -->

<!-- ``` -->