---
title: "Single cell RNA-seq of Plasmodium sporozoite-infected monocytes - dimensionality reduction"
output:
  pdf_document: default
  html_document:
    df_print: paged
  toc: TRUE
---

<!-- ```{r, echo = F} -->
<!-- # knitr::opts_chunk$set(warning = F, message = F) -->
<!-- # knitr::opts_chunk$set(fig.pos = "!H", out.extra = "") -->
<!-- #knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE) -->

<!-- ``` -->

```{r load_libraries, echo = F, message = F, warning = F}
library(Seurat)
library(patchwork)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
remotes::install_github('chris-mcginnis-ucsf/DoubletFinder')
library(DoubletFinder)
# devtools::install_github('satijalab/seurat-data')
# library(SeuratData)
# remotes::install_github("mojaveazure/seurat-disk")
# library(SeuratDisk)
# 
# devtools::install_github('cole-trapnell-lab/monocle3')
# remotes::install_github("scfurl/m3addon")
```

```{r}
load("malaria_monocyte_DimRed_umap.RData")
```

```{r}
# Doublet filtering using DoubletFinder

# pK indentification (no ground truth)
mono.res.list <- paramSweep_v3(mono, PCs = 1:15, sct = FALSE)
mono.stats <- summarizeSweep(mono.res.list, GT = FALSE)
mono.pk <- find.pK(mono.stats)

ggplot(mono.pk, aes(pK, BCmetric, group = 1)) +
  geom_point() +
  geom_line()

pK <- mono.pk %>% 
  filter(BCmetric == max(BCmetric)) %>% 
  select(pK)

```

```{r}

## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
annotations <- mono@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)           ## ex: annotations <- seu_kidney@meta.data$ClusteringResults
nExp_poi <- round(0.075*nrow(mono@meta.data))  ## Assuming 7.5% doublet formation rate - tailor for your dataset
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))

```

```{r}
## Run DoubletFinder with varying classification stringencies ----------------------------------------------------------------
mono.doublet <- doubletFinder_v3(mono, 
                         PCs = 1:15, 
                         pN = 0.25, 
                         pK = 0.03, ##pK 0.005 gives an error
                         nExp = nExp_poi, 
                         reuse.pANN = FALSE, 
                         sct = FALSE)

mono.doublet <- doubletFinder_v3(mono,
                                 PCs = 1:15, 
                                 pN = 0.25, 
                                 pK = pK, 
                                 nExp = nExp_poi.adj, 
                                 reuse.pANN = "pANN_0.25_0.09_913", 
                                 sct = FALSE)

save.image("malaria.monocyte.doublet.RData")

```

```{r}
SaveH5Seurat(mono, filename = "mono.h5Seurat")
Convert("mono.h5Seurat", dest = "h5ad")
```