---
title: "Gene sets from bulk RNA-seq"
output:
  html_document:
    df_print: paged
    code_folding: hide
  pdf_document: default
  toc: TRUE
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(fig.width = 10, fig.height = 8) 
```

```{r}
library(Seurat)
library(patchwork)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
library(ggplot2)
library(SeuratData)
#library(celldex)
#install.packages("cowplot")
library(cowplot)
#devtools::install_github('cole-trapnell-lab/monocle3')
library(monocle3)
#remotes::install_github('satijalab/seurat-wrappers')
library(SeuratWrappers)
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(ggrepel)
library(data.table)
library(ComplexHeatmap)
library(msigdbr)
library(heatmap3)
library(presto)
library(fgsea)
library(topGO)
# install.packages("devtools")
# devtools::install_github("saeyslab/nichenetr")
#library(nichenetr)
# mulattoes::install('multtest')
# install.packages('metap')
#library(metap)
#remotes::install_github("satijalab/seurat-data")
```

```{r}
immune.combined <- readRDS("immune.combined.TBremoved.rds")

DefaultAssay(immune.combined) <- "RNA"

# immune.combined@meta.data <- immune.combined@meta.data %>% 
#   mutate(Donorid = case_when(
#     orig.ident %in% c("EXP1_l2", "EXP1_l1") & donor_id == "donor0" ~ "D1",
#     orig.ident %in% c("EXP1_l2", "EXP1_l1") & donor_id == "donor1" ~ "D2",
#     orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor0" ~ "D3",
#     orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor1" ~ "D4",
#     orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor2" ~ "D5"
#   ))
  

# immune.combined@meta.data <- immune.combined@meta.data %>% 
#   mutate(cellID = "Cell")

table(immune.combined$Donorid, immune.combined$orig.ident)
immune.combined@meta.data$cond_group <- paste(immune.combined@meta.data$Group,
                                               immune.combined@meta.data$Donorid,
                                               sep = "")

cts <- AggregateExpression(immune.combined,
              group.by = c("cellID", "cond_group"),
              assays = "RNA",
              slot = "counts",
              return.seurat = F)
cts <- cts$RNA

# transpose
# cts.t <- as.data.frame(t(cts))
#
# # split.data.frame
# splitRows <- gsub('_.*', '', rownames(cts.t))
# #splitRows <- sapply(strsplit(rownames(cts.t), split = "D"), function(x) x[1])
# cts.split <- split.data.frame(cts.t,
#                  f = factor(splitRows))
# 
# # fix colnames and transpose
# cts.modified <- lapply(cts.split, function(x){
#   rownames(x) <- gsub("(.+?)(\\_.*)", "\\2", rownames(x))
#   rownames(x) <- gsub("^_", "\\1", rownames(x))
#   t(x)
# })
```

```{r}

# Monocytes activated (type I IFN signature)
# Run DE analysis
# 1. Get counts matrix

de_function <- function(condition1, condition2, padj_thr_sc)
{
  padj_thr_sc <- padj_thr_sc
  
  counts <- cts %>% 
  as.data.frame() %>% 
  dplyr::select(c(starts_with(condition1), starts_with(condition2)))

  # 2 Generate metadata
  colData <- data.frame(sample = colnames(counts))
  colData$condition = sapply(str_split(colData$sample, "D"), function(x) x[1])
  colData <- colData %>% 
    tibble::column_to_rownames("sample")
  
  # more info for metadata
  
  # DEseq2 object
  dds <- DESeqDataSetFromMatrix(countData = counts,
                               colData = colData,
                               design = ~condition)
  
  
  # filter dds
  keep <- rowSums(counts(dds)) >= 10
  dds <- dds[keep,]
  
  dds$condition <- relevel(dds$condition, ref = condition1)
  
  dds <- DESeq(dds)
  
  comparison <- resultsNames(dds)[2]

  res <- results(dds, name = comparison, alpha = padj_thr_sc)
  
  # Turn the DESeq2 results object into a tibble for use with tidyverse functions
  res_tbl <- res %>%
    data.frame() %>%
    rownames_to_column(var = "gene") %>%
    as_tibble() %>%
    dplyr::arrange(pvalue)
  
  
  ####
  
  # Subset the significant results
  sig_res <- dplyr::filter(res_tbl, padj <= padj_thr_sc) %>%
    dplyr::arrange(padj)
  
  # Check significant genes output
  sig_res
  
  ## Extract normalized counts from dds object
  normalized_counts <- counts(dds, normalized = TRUE)
  
  ## Extract normalized counts for significant genes only
  sig_counts <- normalized_counts[rownames(normalized_counts) %in% sig_res$gene, ]
  
  
  return(list(dds,sig_counts, sig_res))
  
}

convertMouseGeneList <- function(x){
require("biomaRt")
human = useMart("ensembl", dataset = "hsapiens_gene_ensembl", host = "dec2021.archive.ensembl.org")
mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl", host = "dec2021.archive.ensembl.org")
genesV2 = getLDS(attributes = c("mgi_symbol"), filters = "mgi_symbol", values = x , mart = mouse, attributesL = c("hgnc_symbol"), martL = human, uniqueRows=T)
humanx <- unique(genesV2[, 2])
return(humanx)
}

bulkRNAseq_comparison <- function(file, condition1, condition2, padj_thr_bulk, padj_thr_sc, logFC_thr)
{
  # bulk
  bulk_table <- read.csv(paste0("../Data/", file, collapse = ''))
  table_genes <- bulk_table %>% 
    filter(abs(log2FoldChange) >= logFC_thr) %>% 
    filter(padj <= padj_thr_bulk) 
  
  bulk_pos <- table_genes %>% 
    filter(log2FoldChange >= 0)
  
  bulk_neg <- table_genes %>% 
    filter(log2FoldChange < 0)
  
  table_genes_pos <- bulk_pos %>% 
    pull(GeneSymbol)
  
  table_genes_neg <- bulk_neg %>% 
    pull(GeneSymbol)
  
  humangenes_pos <- convertMouseGeneList(table_genes_pos)
  
  humangenes_neg <- convertMouseGeneList(table_genes_neg)

  
  # scRNAseq
  scRNA_pseudobulk_list <- de_function(condition1 = condition1, 
                                        condition2 = condition2,
                                       padj_thr_sc = padj_thr_sc
                                        #celltype = celltype,
                                        #geneset = table_genes_v
                                       )
  
  dds <- scRNA_pseudobulk_list[[1]]
  sig.genes_table <- scRNA_pseudobulk_list[[2]]
  
  sig.genes_pvalue_pos <- scRNA_pseudobulk_list[[3]] %>% 
    filter(log2FoldChange >= 0) %>% 
    left_join(data.frame(gene = humangenes_pos),.) %>% 
    na.omit() %>% 
    arrange(padj)
  
  sig.genes_pvalue_neg <- scRNA_pseudobulk_list[[3]] %>% 
    filter(log2FoldChange < 0) %>% 
    left_join(data.frame(gene = humangenes_neg),.) %>% 
    na.omit()%>% 
    arrange(padj)
  
  # getting genes common to bulk data
  sig.genes_table_pos <- sig.genes_table %>% 
    as.data.frame() %>% 
    rownames_to_column("Gene") %>% 
    filter(Gene %in% sig.genes_pvalue_pos$gene) %>% 
    column_to_rownames("Gene")
  
  sig.genes_table_neg <- sig.genes_table %>% 
    as.data.frame() %>% 
    rownames_to_column("Gene") %>% 
    filter(Gene %in% sig.genes_pvalue_neg$gene) %>% 
    column_to_rownames("Gene")
  

  vsd <- assay(vst(dds, 
           nsub = sum( rowMeans( counts(dds, normalized=TRUE)) > 5 )))
  z <- t(scale(t(vsd)))
  z_pos <- z[rownames(z) %in% rownames(sig.genes_table_pos),]
  z_neg <- z[rownames(z) %in% rownames(sig.genes_table_neg),]

  #return(list(bulktable_genes = table_genes, z = z, sig.genes_exp = sig.genes_table, sig_genes_pvalue = sig.genes_pvalue))
  
  return(list(bulktable_genes = table_genes, z_pos = z_pos, z_neg = z_neg, sig.genes_exp_pos = sig.genes_table_pos, sig.genes_exp_neg = sig.genes_table_neg, sig_genes_pvalue_pos = sig.genes_pvalue_pos, sig_genes_pvalue_neg = sig.genes_pvalue_neg))
}

heat_colors <- rev(brewer.pal(11, "PuOr"))

gsea <- function(category, deg)
{
  m_df<- msigdbr(species = "Homo sapiens", category = category)
  fgsea_sets<- m_df %>% split(x = .$gene_symbol, f = .$gs_name)

  gene_logFC_rank <- deg[,c("gene", "log2FoldChange")] %>% 
    arrange(-log2FoldChange) %>% 
    deframe(.)
    
  fgseaRes<- fgsea(fgsea_sets, stats = gene_logFC_rank, nperm = 1000)
  
  fgseaResTidy <- fgseaRes %>%
  as_tibble() %>%
  arrange(desc(NES))
  
  return(list(fgsea_sets = fgsea_sets, gene_logFC_rank = gene_logFC_rank, fgseaResTidy = fgseaResTidy))
}
  
```

# All cells

## Sporozoite_infected vs control (base)

```{r}

SPZ_GFPpos_vs_untr <- bulkRNAseq_comparison(file = "SPZ-GFPpos_untr_df_4h.csv",
                                            condition1 = "control",
                                            condition2 = "sporozoite_infected",
                                            #celltype = "Activated monocytes",
                                            padj_thr_bulk = 0.1,
                                            padj_thr_sc = 0.1,
                                            logFC_thr = 2)
DT::datatable(SPZ_GFPpos_vs_untr[["bulktable_genes"]])

DT::datatable(SPZ_GFPpos_vs_untr[["sig_genes_pvalue_pos"]])  

DT::datatable(SPZ_GFPpos_vs_untr[["sig_genes_pvalue_neg"]])  


z_pos <- SPZ_GFPpos_vs_untr[["z_pos"]] %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("gene") %>%
  left_join(data.frame(gene = SPZ_GFPpos_vs_untr[["sig_genes_pvalue_pos"]][,"gene"]),.) %>%
  tibble::column_to_rownames("gene")

z_neg <- SPZ_GFPpos_vs_untr[["z_neg"]] %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("gene") %>%
  left_join(data.frame(gene = SPZ_GFPpos_vs_untr[["sig_genes_pvalue_neg"]][,"gene"]),.) %>%
  tibble::column_to_rownames("gene")

Heatmap(z_pos[1:60,], name = "z-score", 
        width = ncol(z_pos)*unit(5, "mm"), 
        height = 60*unit(2.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = T, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))

Heatmap(z_neg, name = "z-score", 
        width = ncol(z_neg)*unit(5, "mm"), 
        height = nrow(z_neg)*unit(2.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = T, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))

## fgsea

# C2

fgsea_SPZ_GFPpos_vs_untr_C2 <- gsea(category = "C2", deg = rbind(SPZ_GFPpos_vs_untr[["sig_genes_pvalue_pos"]], SPZ_GFPpos_vs_untr[["sig_genes_pvalue_neg"]]))

DT::datatable(fgsea_SPZ_GFPpos_vs_untr_C2[["fgseaResTidy"]])

ggplot(fgsea_SPZ_GFPpos_vs_untr_C2[["fgseaResTidy"]] %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) +
  geom_col(aes(fill= NES)) +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Hallmark pathways NES from GSEA") +
  theme_minimal()

plotEnrichment(fgsea_SPZ_GFPpos_vs_untr_C2[["fgsea_sets"]][["REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN"]],
               fgsea_SPZ_GFPpos_vs_untr_C2[["gene_logFC_rank"]]) + labs(title="REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN")

plotEnrichment(fgsea_SPZ_GFPpos_vs_untr_C2[["fgsea_sets"]][["REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON"]],
               fgsea_SPZ_GFPpos_vs_untr_C2[["gene_logFC_rank"]]) + labs(title="REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON")

# C5

fgsea_SPZ_GFPpos_vs_untr_C5 <- gsea(category = "C5", deg = rbind(SPZ_GFPpos_vs_untr[["sig_genes_pvalue_pos"]], SPZ_GFPpos_vs_untr[["sig_genes_pvalue_neg"]]))

DT::datatable(fgsea_SPZ_GFPpos_vs_untr_C5[["fgseaResTidy"]])

ggplot(fgsea_SPZ_GFPpos_vs_untr_C5[["fgseaResTidy"]] %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) +
  geom_col(aes(fill= NES)) +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Hallmark pathways NES from GSEA") +
  theme_minimal()

plotEnrichment(fgsea_SPZ_GFPpos_vs_untr_C5[["fgsea_sets"]][["GOBP_RESPONSE_TO_WOUNDING"]],
               fgsea_SPZ_GFPpos_vs_untr_C5[["gene_logFC_rank"]]) + labs(title="GOBP_RESPONSE_TO_WOUNDING")


```

# Sporozoite bystander vs untreated

```{r}

SPZ_GFPneg_vs_untr <- bulkRNAseq_comparison(file = "SPZ-GFPneg_untr_df_4h.csv",
                                            condition1 = "control",
                                            condition2 = "sporozoite_bystander",
                                            #celltype = "Activated monocytes",
                                            padj_thr_bulk = 0.1,
                                            padj_thr_sc = 0.1,
                                            logFC_thr = 2)

DT::datatable(SPZ_GFPneg_vs_untr[["bulktable_genes"]])

DT::datatable(SPZ_GFPneg_vs_untr[["sig_genes_pvalue_pos"]])  

DT::datatable(SPZ_GFPneg_vs_untr[["sig_genes_pvalue_neg"]])  


z_pos <- SPZ_GFPneg_vs_untr[["z_pos"]] %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("gene") %>%
  left_join(data.frame(gene = SPZ_GFPneg_vs_untr[["sig_genes_pvalue_pos"]][,"gene"]),.) %>%
  tibble::column_to_rownames("gene")

z_neg <- SPZ_GFPneg_vs_untr[["z_neg"]] %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("gene") %>%
  left_join(data.frame(gene = SPZ_GFPneg_vs_untr[["sig_genes_pvalue_neg"]][,"gene"]),.) %>%
  tibble::column_to_rownames("gene")

Heatmap(z_pos[1:60,], name = "z-score", 
        width = ncol(z_pos)*unit(5, "mm"), 
        height = 60*unit(2.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = T, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))

Heatmap(z_neg, name = "z-score", 
        width = ncol(z_neg)*unit(5, "mm"), 
        height = nrow(z_neg)*unit(2.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = T, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))

## fgsea

# C2

fgsea_SPZ_GFPneg_vs_untr_C2 <- gsea(category = "C2", deg = rbind(SPZ_GFPneg_vs_untr[["sig_genes_pvalue_pos"]], SPZ_GFPneg_vs_untr[["sig_genes_pvalue_neg"]]))

DT::datatable(fgsea_SPZ_GFPneg_vs_untr_C2[["fgseaResTidy"]])

ggplot(fgsea_SPZ_GFPneg_vs_untr_C2[["fgseaResTidy"]] %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) +
  geom_col(aes(fill= NES)) +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Hallmark pathways NES from GSEA") +
  theme_minimal()

plotEnrichment(fgsea_SPZ_GFPneg_vs_untr_C2[["fgsea_sets"]][["REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN"]],
               fgsea_SPZ_GFPneg_vs_untr_C2[["gene_logFC_rank"]]) + labs(title="REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN")

plotEnrichment(fgsea_SPZ_GFPneg_vs_untr_C2[["fgsea_sets"]][["REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON"]],
               fgsea_SPZ_GFPneg_vs_untr_C2[["gene_logFC_rank"]]) + labs(title="REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON")

# C5

fgsea_SPZ_GFPneg_vs_untr_C5 <- gsea(category = "C5", deg = rbind(SPZ_GFPneg_vs_untr[["sig_genes_pvalue_pos"]], SPZ_GFPneg_vs_untr[["sig_genes_pvalue_neg"]]))

DT::datatable(fgsea_SPZ_GFPneg_vs_untr_C5[["fgseaResTidy"]])

ggplot(fgsea_SPZ_GFPneg_vs_untr_C5[["fgseaResTidy"]] %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) +
  geom_col(aes(fill= NES)) +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Hallmark pathways NES from GSEA") +
  theme_minimal()

plotEnrichment(fgsea_SPZ_GFPneg_vs_untr_C5[["fgsea_sets"]][["GOBP_RESPONSE_TO_WOUNDING"]],
               fgsea_SPZ_GFPneg_vs_untr_C5[["gene_logFC_rank"]]) + labs(title="GOBP_RESPONSE_TO_WOUNDING")
```

# SPZ infected vs SPZ bystander

```{r}

SPZ_GFPpos_vs_SPZ_GFPneg <- bulkRNAseq_comparison(file = "SPZ-GFPpos_SPZ-GFPneg_df.csv",
                                            condition1 = "sporozoite_bystander",
                                            condition2 = "sporozoite_infected",
                                            #celltype = "Activated monocytes",
                                            padj_thr_bulk = 0.1,
                                            padj_thr_sc = 0.1,
                                            logFC_thr = 2)

DT::datatable(SPZ_GFPpos_vs_SPZ_GFPneg[["bulktable_genes"]])

DT::datatable(SPZ_GFPpos_vs_SPZ_GFPneg[["sig_genes_pvalue_pos"]])  

DT::datatable(SPZ_GFPpos_vs_SPZ_GFPneg[["sig_genes_pvalue_neg"]])  


# z_pos <- SPZ_GFPpos_vs_SPZ_GFPneg[["z_pos"]] %>% 
#   as.data.frame() %>% 
#   tibble::rownames_to_column("gene") %>%
#   left_join(data.frame(gene = SPZ_GFPpos_vs_SPZ_GFPneg[["sig_genes_pvalue_pos"]][,"gene"]),.) %>%
#   tibble::column_to_rownames("gene")
# 
# z_neg <- SPZ_GFPpos_vs_SPZ_GFPneg[["z_neg"]] %>% 
#   as.data.frame() %>% 
#   tibble::rownames_to_column("gene") %>%
#   left_join(data.frame(gene = SPZ_GFPpos_vs_SPZ_GFPneg[["sig_genes_pvalue_neg"]][,"gene"]),.) %>%
#   tibble::column_to_rownames("gene")

# Heatmap(z_pos[1:60,], name = "z-score", 
#         width = ncol(z_pos)*unit(5, "mm"), 
#         height = 60*unit(2.5, "mm"),
#         col = heat_colors, 
#         cluster_rows= T, cluster_columns = T, 
#         show_column_dend = T, show_row_dend = F, 
#         show_row_names = T, 
#         row_names_gp = gpar(fontsize = 5),
#         column_names_side = "top", column_names_rot = 45, 
#         column_names_gp = gpar(fontsize = 6),
#         #row_km = 2, 
#         column_km = 2, border = TRUE, 
#         column_title = NULL, row_title = NULL, 
#         border_gp = gpar(col = "darkgrey"))
# 
# Heatmap(z_neg, name = "z-score", 
#         width = ncol(z_neg)*unit(5, "mm"), 
#         height = nrow(z_neg)*unit(2.5, "mm"),
#         col = heat_colors, 
#         cluster_rows= T, cluster_columns = T, 
#         show_column_dend = T, show_row_dend = F, 
#         show_row_names = T, 
#         row_names_gp = gpar(fontsize = 5),
#         column_names_side = "top", column_names_rot = 45, 
#         column_names_gp = gpar(fontsize = 6),
#         #row_km = 2, 
#         column_km = 2, border = TRUE, 
#         column_title = NULL, row_title = NULL, 
#         border_gp = gpar(col = "darkgrey"))

```

# RBC bystander vs RBC control

```{r}
# RBC bystander vs untreated
# iRBC_GFPneg_vs_RBC_untr <- bulkRNAseq_comparison(file = "iRBC-GFPneg_RBC_df_4h.csv",
#                                             condition1 = "RBC_control",
#                                             condition2 = "RBC_bystander",
#                                             #celltype = "Activated monocytes",
#                                             padj_thr_bulk = 0.05,
#                                             padj_thr_sc = 0.1,
#                                             logFC_thr = 1.5)
# DT::datatable(iRBC_GFPneg_vs_RBC_untr[[1]])
# 
# z <- iRBC_GFPneg_vs_RBC_untr[[2]] %>% 
#   as.data.frame() %>% 
#   tibble::rownames_to_column("gene") %>% 
#   left_join(iRBC_GFPneg_vs_RBC_untr[[4]][,"gene"],.) %>% 
#   tibble::column_to_rownames("gene")
# 
# DT::datatable(iRBC_GFPneg_vs_RBC_untr[["sig_genes_pvalue"]]) 
# 
# Heatmap(z, name = "z-score", 
#         width = ncol(z)*unit(5, "mm"), 
#         height = nrow(z)*unit(2.5, "mm"),
#         col = heat_colors, 
#         cluster_rows= T, cluster_columns = T, 
#         show_column_dend = T, show_row_dend = F, 
#         show_row_names = T, 
#         row_names_gp = gpar(fontsize = 5),
#         column_names_side = "top", column_names_rot = 45, 
#         column_names_gp = gpar(fontsize = 6),
#         #row_km = 2, 
#         column_km = 2, border = TRUE, 
#         column_title = NULL, row_title = NULL, 
#         border_gp = gpar(col = "darkgrey"))

```

# RBC infected vs RBC control

```{r}
# RBC bystander vs untreated

iRBC_GFPpos_vs_RBC_untr <- bulkRNAseq_comparison(file = "iRBC-GFPpos_RBC_df_4h.csv",
                                            condition1 = "RBC_control",
                                            condition2 = "RBC_infected",
                                           # celltype = "Activated monocytes",
                                            padj_thr_bulk = 0.1,
                                            padj_thr_sc = 0.1,
                                            logFC_thr = 1.5)
DT::datatable(iRBC_GFPpos_vs_RBC_untr[[1]])

# z_pos <- SPZ_GFPpos_vs_SPZ_GFPneg[["z_pos"]] %>% 
#   as.data.frame() %>% 
#   tibble::rownames_to_column("gene") %>%
#   left_join(data.frame(gene = SPZ_GFPpos_vs_SPZ_GFPneg[["sig_genes_pvalue_pos"]][,"gene"]),.) %>%
#   tibble::column_to_rownames("gene")
# 
# z_neg <- SPZ_GFPpos_vs_SPZ_GFPneg[["z_neg"]] %>% 
#   as.data.frame() %>% 
#   tibble::rownames_to_column("gene") %>%
#   left_join(data.frame(gene = SPZ_GFPpos_vs_SPZ_GFPneg[["sig_genes_pvalue_neg"]][,"gene"]),.) %>%
#   tibble::column_to_rownames("gene")

# Heatmap(z_pos[1:60,], name = "z-score", 
#         width = ncol(z_pos)*unit(5, "mm"), 
#         height = 60*unit(2.5, "mm"),
#         col = heat_colors, 
#         cluster_rows= T, cluster_columns = T, 
#         show_column_dend = T, show_row_dend = F, 
#         show_row_names = T, 
#         row_names_gp = gpar(fontsize = 5),
#         column_names_side = "top", column_names_rot = 45, 
#         column_names_gp = gpar(fontsize = 6),
#         #row_km = 2, 
#         column_km = 2, border = TRUE, 
#         column_title = NULL, row_title = NULL, 
#         border_gp = gpar(col = "darkgrey"))
# 
# Heatmap(z_neg, name = "z-score", 
#         width = ncol(z_neg)*unit(5, "mm"), 
#         height = nrow(z_neg)*unit(2.5, "mm"),
#         col = heat_colors, 
#         cluster_rows= T, cluster_columns = T, 
#         show_column_dend = T, show_row_dend = F, 
#         show_row_names = T, 
#         row_names_gp = gpar(fontsize = 5),
#         column_names_side = "top", column_names_rot = 45, 
#         column_names_gp = gpar(fontsize = 6),
#         #row_km = 2, 
#         column_km = 2, border = TRUE, 
#         column_title = NULL, row_title = NULL, 
#         border_gp = gpar(col = "darkgrey"))

```

# RBC infected vs RBC bystander

```{r}

iRBC_GFPpos_vs_iRBC_GFPneg <- bulkRNAseq_comparison(file = "iRBC-GFPpos_iRBC-GFPneg_df_4h.csv",
                                            condition1 = "RBC_bystander",
                                            condition2 = "RBC_infected",
                                            #celltype = "Activated monocytes",
                                            padj_thr_bulk = 0.1,
                                            padj_thr_sc = 0.1,
                                            logFC_thr = 1.5)
DT::datatable(iRBC_GFPpos_vs_iRBC_GFPneg[[1]])

# z <- iRBC_GFPpos_vs_iRBC_GFPneg[[2]] %>% 
#   as.data.frame() %>% 
#   tibble::rownames_to_column("gene") %>% 
#   left_join(iRBC_GFPpos_vs_iRBC_GFPneg[[4]][,"gene"],.) %>% 
#   tibble::column_to_rownames("gene")
# 
# DT::datatable(iRBC_GFPpos_vs_iRBC_GFPneg[["sig_genes_pvalue"]]) 
# 
# Heatmap(z, name = "z-score", 
#         width = ncol(z)*unit(5, "mm"), 
#         height = nrow(z)*unit(2.5, "mm"),
#         col = heat_colors, 
#         cluster_rows= T, cluster_columns = T, 
#         show_column_dend = T, show_row_dend = F, 
#         show_row_names = T, 
#         row_names_gp = gpar(fontsize = 5),
#         column_names_side = "top", column_names_rot = 45, 
#         column_names_gp = gpar(fontsize = 6),
#         #row_km = 2, 
#         column_km = 2, border = TRUE, 
#         column_title = NULL, row_title = NULL, 
#         border_gp = gpar(col = "darkgrey"))

```

# SPZ vs iRBC

```{r}
SPZ_vs_iRBC <- bulkRNAseq_comparison(file = "SPZ-iRBC_df_4h.csv",
                                            condition1 = "RBC_infected",
                                            condition2 = "sporozoite_infected",
                                            #celltype = "Activated monocytes",
                                            padj_thr_bulk = 0.1,
                                            padj_thr_sc = 0.1,
                                            logFC_thr = 1.5)

DT::datatable(SPZ_vs_iRBC[["bulktable_genes"]])

DT::datatable(SPZ_vs_iRBC[["sig_genes_pvalue_pos"]])  

DT::datatable(SPZ_vs_iRBC[["sig_genes_pvalue_neg"]])  


z_pos <- SPZ_vs_iRBC[["z_pos"]] %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("gene") %>%
  left_join(data.frame(gene = SPZ_vs_iRBC[["sig_genes_pvalue_pos"]][,"gene"]),.) %>%
  tibble::column_to_rownames("gene")

z_neg <- SPZ_vs_iRBC[["z_neg"]] %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("gene") %>%
  left_join(data.frame(gene = SPZ_vs_iRBC[["sig_genes_pvalue_neg"]][,"gene"]),.) %>%
  tibble::column_to_rownames("gene")

#png("SPZ_vs_iRBC_heatmap.png", res = 300, width = 15, height = 20, units = "cm")
Heatmap(z_pos, name = "z-score", 
        width = ncol(z_pos)*unit(5, "mm"), 
        height = 60*unit(2.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = T, 
        row_names_gp = gpar(fontsize = 8),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))
#dev.off()

Heatmap(z_neg, name = "z-score", 
        width = ncol(z_neg)*unit(5, "mm"), 
        height = nrow(z_neg)*unit(2.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = T, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))

# C2

fgsea_SPZ_vs_iRBC_C2 <- gsea(category = "C2", deg = rbind(SPZ_vs_iRBC[["sig_genes_pvalue_pos"]], SPZ_vs_iRBC[["sig_genes_pvalue_neg"]]))

DT::datatable(fgsea_SPZ_vs_iRBC_C2[["fgseaResTidy"]])

ggplot(fgsea_SPZ_vs_iRBC_C2[["fgseaResTidy"]] %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) +
  geom_col(aes(fill= NES)) +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Hallmark pathways NES from GSEA") +
  theme_minimal()

plotEnrichment(fgsea_SPZ_vs_iRBC_C2[["fgsea_sets"]][["REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN"]],
               fgsea_SPZ_vs_iRBC_C2[["gene_logFC_rank"]]) + labs(title="REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN")

plotEnrichment(fgsea_SPZ_vs_iRBC_C2[["fgsea_sets"]][["REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON"]],
               fgsea_SPZ_vs_iRBC_C2[["gene_logFC_rank"]]) + labs(title="REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON")

# C5

fgsea_SPZ_vs_iRBC_C5 <- gsea(category = "C5", deg = rbind(SPZ_vs_iRBC[["sig_genes_pvalue_pos"]], SPZ_vs_iRBC[["sig_genes_pvalue_neg"]]))

DT::datatable(fgsea_SPZ_vs_iRBC_C5[["fgseaResTidy"]])

ggplot(fgsea_SPZ_vs_iRBC_C5[["fgseaResTidy"]] %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) +
  geom_col(aes(fill= NES)) +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Hallmark pathways NES from GSEA") +
  theme_minimal()

plotEnrichment(fgsea_SPZ_vs_iRBC_C5[["fgsea_sets"]][["GOBP_RESPONSE_TO_WOUNDING"]],
               fgsea_SPZ_vs_iRBC_C5[["gene_logFC_rank"]]) + labs(title="GOBP_RESPONSE_TO_WOUNDING")

```

```{r}
# topGO
comparison <- SPZ_vs_iRBC

# make gene universe
gene_uni <- rownames(cts)

# get gene list
deg <- c(comparison[["sig_genes_pvalue_pos"]]$gene, comparison[["sig_genes_pvalue_neg"]]$gene)

geneList <- factor(as.integer(gene_uni %in% deg))
names(geneList) <- gene_uni

topDiffGenes <- function(allScore) 
{
  return(allScore == 1)
}
x <- topDiffGenes(geneList)

allGO2genes <- annFUN.org(whichOnto="BP", feasibleGenes=NULL, mapping="org.Hs.eg.db", ID="symbol")

hGOdata <- new("topGOdata",
                   ontology = "BP",
                   allGenes = geneList,
                   nodeSize = 10,
                   annot = annFUN.GO2genes,
               GO2genes = allGO2genes,
                   geneSelectionFun = topDiffGenes)


resultKS=runTest(hGOdata, algorithm='weight01', statistic='KS')
    allGO=usedGO(hGOdata)
    all_res=GenTable(hGOdata, KS=resultKS, orderBy="KS", topNodes=length(allGO), nchar = 1000)
    
  all_res <- all_res %>% 
    filter(Significant != 0) %>% 
    mutate(strength = Significant/Expected)
```