---
title: "Gene sets from bulk RNA-seq"
output:
  html_document:
    df_print: paged
    code_folding: hide
  pdf_document: default
  toc: TRUE
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(fig.width = 10, fig.height = 8) 
```

```{r}
library(Seurat)
library(patchwork)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
library(ggplot2)
library(SeuratData)
#library(celldex)
#install.packages("cowplot")
library(cowplot)
#devtools::install_github('cole-trapnell-lab/monocle3')
library(monocle3)
#remotes::install_github('satijalab/seurat-wrappers')
library(SeuratWrappers)
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(ggrepel)
library(data.table)
library(ComplexHeatmap)
# install.packages("devtools")
# devtools::install_github("saeyslab/nichenetr")
#library(nichenetr)
# mulattoes::install('multtest')
# install.packages('metap')
#library(metap)
#remotes::install_github("satijalab/seurat-data")
```

```{r}
immune.combined <- readRDS("immune.combined_all_libs_preprocessed.rds")
immune.combined@assays[["integrated"]]@counts <- immune.combined@assays[["RNA"]]@counts

immune.combined@meta.data <- immune.combined@meta.data %>% 
  mutate(Donorid = case_when(
    orig.ident %in% c("EXP1_l2", "EXP1_l1") & donor_id == "donor0" ~ "D1",
    orig.ident %in% c("EXP1_l2", "EXP1_l1") & donor_id == "donor1" ~ "D2",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor0" ~ "D3",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor1" ~ "D4",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor2" ~ "D5"
  ))

immune.combined@meta.data <- immune.combined@meta.data %>% 
  mutate(act_inact = case_when(
    str_detect(predicted.celltype, "Monocytes activated") ~ "Activated monocytes",
    .default = predicted.celltype
  ))


table(immune.combined$Donorid, immune.combined$orig.ident)
immune.combined@meta.data$cond_group <- paste(immune.combined@meta.data$Group,
                                               immune.combined@meta.data$Donorid,
                                               sep = "")

cts <- AggregateExpression(immune.combined,
              group.by = c("act_inact", "cond_group"),
              assays = "RNA",
              slot = "counts",
              return.seurat = F)
cts <- cts$RNA

# transpose
cts.t <- as.data.frame(t(cts))

# split.data.frame
splitRows <- gsub('_.*', '', rownames(cts.t))
cts.split <- split.data.frame(cts.t,
                 f = factor(splitRows))

# fix colnames and transpose
cts.modified <- lapply(cts.split, function(x){
  rownames(x) <- gsub("(.+?)(\\_.*)", "\\2", rownames(x))
  rownames(x) <- gsub("^_", "\\1", rownames(x))
  t(x)
})
```

```{r}

# Monocytes activated (type I IFN signature)
# Run DE analysis
# 1. Get counts matrix

de_function <- function(condition1, condition2, celltype, geneset)
{
  counts_classmonocytes <- cts.modified[[celltype]] %>% 
  as.data.frame() %>% 
  dplyr::select(c(starts_with(condition1), starts_with(condition2)))

  # 2 Generate metadata
  colData <- data.frame(sample = colnames(counts_classmonocytes))
  colData$condition = sapply(str_split(colData$sample, "D"), function(x) x[1])
  colData <- colData %>% 
    tibble::column_to_rownames("sample")
  
  # more info for metadata
  
  # DEseq2 object
  dds <- DESeqDataSetFromMatrix(countData = counts_classmonocytes,
                               colData = colData,
                               design = ~condition)
  
  
  # filter dds
  keep <- rowSums(counts(dds)) >= 10
  dds <- dds[keep,]
  dds <- DESeq(dds)
  
  comparison <- resultsNames(dds)[2]

  res <- results(dds, name = comparison, alpha = 0.05)
  
  # Turn the DESeq2 results object into a tibble for use with tidyverse functions
  res_tbl <- res %>%
    data.frame() %>%
    rownames_to_column(var = "gene") %>%
    as_tibble() %>%
    dplyr::arrange(pvalue)
  
  
  ####
  padj_cutoff <- 0.05
  
  # Subset the significant results
  sig_res <- dplyr::filter(res_tbl, pvalue < padj_cutoff) %>%
    dplyr::arrange(padj)
  
  # Check significant genes output
  sig_res
  
  ## Extract normalized counts from dds object
  normalized_counts <- counts(dds, normalized = TRUE)
  
  ## Extract normalized counts for significant genes only
  sig_counts <- normalized_counts[rownames(normalized_counts) %in% sig_res$gene, ]
  
  
  return(list(dds,sig_counts))
  
}

convertMouseGeneList <- function(x){
require("biomaRt")
human = useMart("ensembl", dataset = "hsapiens_gene_ensembl", host = "dec2021.archive.ensembl.org")
mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl", host = "dec2021.archive.ensembl.org")
genesV2 = getLDS(attributes = c("mgi_symbol"), filters = "mgi_symbol", values = x , mart = mouse, attributesL = c("hgnc_symbol"), martL = human, uniqueRows=T)
humanx <- unique(genesV2[, 2])
return(humanx)
}

bulkRNAseq_comparison <- function(file, condition1, condition2, celltype, padj_thr, logFC_thr)
{
  # bulk
  bulk_table <- read.csv(paste0("../Data/", file, collapse = ''))
  table_genes <- bulk_table %>% 
    filter(abs(log2FoldChange) >= logFC_thr) %>% 
    filter(padj <= padj_thr) 
  
  table_genes_v <- table_genes %>% 
    pull(GeneSymbol)
  
  humangenes <- convertMouseGeneList(table_genes_v)
  
  # scRNAseq
  scRNA_pseudobulk_list <- de_function(condition1 = condition1, 
                                        condition2 = condition2,
                                        celltype = celltype,
                                        geneset = table_genes_v)
  
  dds <- scRNA_pseudobulk_list[[1]]
  sig.genes_table <- scRNA_pseudobulk_list[[2]]
  
  # getting genes common to bulk data
  sig.genes_table <- sig.genes_table %>% 
    as.data.frame() %>% 
    rownames_to_column("Gene") %>% 
    filter(Gene %in% humangenes) %>% 
    column_to_rownames("Gene")
  
  vsd <- assay(vst(dds, 
           nsub = sum( rowMeans( counts(dds, normalized=TRUE)) > 5 )))
  z <- t(scale(t(vsd)))
  z <- z[rownames(z) %in% rownames(sig.genes_table),]

  return(list(bulktable_genes = table_genes, z = z, sig.genes_table = sig.genes_table))
}

heat_colors <- rev(brewer.pal(11, "PuOr"))
  
```

# All cells

## Sporozoite_infected vs control

```{r}

SPZ_GFPpos_vs_untr <- bulkRNAseq_comparison(file = "SPZ-GFPpos_untr_df_4h.csv",
                                            condition1 = "control",
                                            condition2 = "sporozoite_infected",
                                            celltype = "Activated monocytes",
                                            padj_thr = 0.01,
                                            logFC_thr = 2)
DT::datatable(SPZ_GFPpos_vs_untr[[1]])

z <- SPZ_GFPpos_vs_untr[[2]]

common_genes <- z[rownames(z) %in% rownames(SPZ_GFPpos_vs_untr[[3]]),]
  
DT::datatable(common_genes)  

Heatmap(z[1:60,], name = "z-score", 
        width = ncol(z)*unit(5, "mm"), 
        height = nrow(z)*unit(2, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = T, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))

```

# Sporozoite bystander vs untreated

```{r}

SPZ_GFPneg_vs_untr <- bulkRNAseq_comparison(file = "SPZ-GFPneg_untr_df_4h.csv",
                                            condition1 = "control",
                                            condition2 = "sporozoite_bystander",
                                            celltype = "Activated monocytes",
                                            padj_thr = 0.01,
                                            logFC_thr = 2)
DT::datatable(SPZ_GFPneg_vs_untr[[1]])

z <- SPZ_GFPneg_vs_untr[[2]]

common_genes <- z[rownames(z) %in% rownames(SPZ_GFPneg_vs_untr[[3]]),]

DT::datatable(common_genes)

Heatmap(z[1:60,], name = "z-score", 
        width = ncol(z)*unit(5, "mm"), 
        height = nrow(z)*unit(1.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = T, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))
```

# SPZ infected vs SPZ bystander

```{r}

SPZ_GFPpos_vs_SPZ_GFPneg <- bulkRNAseq_comparison(file = "SPZ-GFPpos_SPZ-GFPneg_df.csv",
                                            condition1 = "sporozoite_bystander",
                                            condition2 = "sporozoite_infected",
                                            celltype = "Activated monocytes",
                                            padj_thr = 0.1,
                                            logFC_thr = 1.5)
DT::datatable(SPZ_GFPpos_vs_SPZ_GFPneg[[1]])

z <- SPZ_GFPpos_vs_SPZ_GFPneg[[2]]

common_genes <- z[rownames(z) %in% rownames(SPZ_GFPpos_vs_SPZ_GFPneg[[3]]),]

DT::datatable(common_genes)


# pheatmap(SPZ_GFPpos_vs_SPZ_GFPneg[[2]][1:60,], 
#          color = heat_colors, 
#          cluster_rows = TRUE, 
#          show_rownames = T,
#          #annotation = colData, 
#          border_color = NA, 
#          fontsize = 10, 
#          scale = "row", 
#          fontsize_row = 7, 
#          height = 20)  
```

# RBC bystander vs RBC control

```{r}
# RBC bystander vs untreated
iRBC_GFPneg_vs_RBC_untr <- bulkRNAseq_comparison(file = "iRBC-GFPneg_RBC_df_4h.csv",
                                            condition1 = "RBC_control",
                                            condition2 = "RBC_bystander",
                                            celltype = "Activated monocytes",
                                            padj_thr = 0.1,
                                            logFC_thr = 1.5)
DT::datatable(iRBC_GFPneg_vs_RBC_untr[[1]])

z <- iRBC_GFPneg_vs_RBC_untr[[2]]

common_genes <- z[rownames(z) %in% rownames(iRBC_GFPneg_vs_RBC_untr[[3]]),]

DT::datatable(common_genes)

# pheatmap(SPZ_GFPneg_vs_untr[[2]][1:60,], 
#          color = heat_colors, 
#          cluster_rows = TRUE, 
#          show_rownames = T,
#          #annotation = colData, 
#          border_color = NA, 
#          fontsize = 10, 
#          scale = "row", 
#          fontsize_row = 7, 
#          height = 20)  
```

# RBC infected vs RBC control

```{r}
# RBC bystander vs untreated

iRBC_GFPpos_vs_RBC_untr <- bulkRNAseq_comparison(file = "iRBC-GFPpos_RBC_df_4h.csv",
                                            condition1 = "RBC_control",
                                            condition2 = "RBC_infected",
                                            celltype = "Activated monocytes",
                                            padj_thr = 0.1,
                                            logFC_thr = 1.5)
DT::datatable(iRBC_GFPpos_vs_RBC_untr[[1]])

z <- iRBC_GFPpos_vs_RBC_untr[[2]]

common_genes <- z[rownames(z) %in% rownames(iRBC_GFPpos_vs_RBC_untr[[3]]),]

DT::datatable(common_genes)

#
```

# RBC infected vs RBC bystander

```{r}

iRBC_GFPpos_vs_iRBC_GFPneg <- bulkRNAseq_comparison(file = "iRBC-GFPpos_iRBC-GFPneg_df_4h.csv",
                                            condition1 = "RBC_bystander",
                                            condition2 = "RBC_infected",
                                            celltype = "Activated monocytes",
                                            padj_thr = 0.1,
                                            logFC_thr = 1.5)
DT::datatable(iRBC_GFPpos_vs_RBC_untr[[1]])

z <- iRBC_GFPpos_vs_RBC_untr[[2]]

common_genes <- z[rownames(z) %in% rownames(iRBC_GFPpos_vs_RBC_untr[[3]]),]

DT::datatable(common_genes)

```

# SPZ vs iRBC

```{r}
SPZ_vs_iRBC <- bulkRNAseq_comparison(file = "SPZ-iRBC_df_4h.csv",
                                            condition1 = "RBC_infected",
                                            condition2 = "sporozoite_infected",
                                            celltype = "Activated monocytes",
                                            padj_thr = 0.1,
                                            logFC_thr = 1.5)
DT::datatable(SPZ_vs_iRBC[[1]])

z <- SPZ_vs_iRBC[[2]]

common_genes <- z[rownames(z) %in% rownames(SPZ_vs_iRBC[[3]]),]

DT::datatable(common_genes)

Heatmap(z[1:60,], name = "z-score", 
        width = ncol(z)*unit(5, "mm"), 
        height = nrow(z)*unit(1.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = T, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))

```