---
title: "Dual organism analysis - pseudobulk RNA-seq - malaria"
output:
  html_document:
    df_print: paged
    code_folding: hide
  pdf_document: default
  toc: TRUE
---


```{r setup, include=T} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(fig.width = 10, fig.height = 8) 
```

```{r}
library(Seurat)
library(patchwork)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
library(ggplot2)
library(SeuratData)
#library(celldex)
#install.packages("cowplot")
library(cowplot)
#devtools::install_github('cole-trapnell-lab/monocle3')
#library(monocle3)
#remotes::install_github('satijalab/seurat-wrappers')
library(SeuratWrappers)
#BiocManager::install('multtest', force = T)
library(multtest)
library(RColorBrewer)
library(rtracklayer)
library(DESeq2)
library(data.table)
library(MatrixModels)
# library(SingleCellExperiment)
# library(scran)
library(org.Hs.eg.db)
library(clusterProfiler)
library(topGO)
library(ggrepel)
library(igraph)
library(GO.db)
library(DBI)
#library(EnhanceVolcano)
# install.packages('metap')
#library(metap)
#remotes::install_github("satijalab/seurat-data")

```

```{r}
# collect all GO.pairs
GO.pairs.1_10 <- readRDS("robjects/GO.pairs.emp.pvalue1_until_10.rds")
GO.pairs.11_20 <- readRDS("robjects/GO.pairs.emp.pvalue11_until_20.rds")
GO.pairs.21_100 <- readRDS("robjects/GO.pairs.emp.pvalue21_until_100.rds")
GO.pairs.101_250 <- readRDS("robjects/GO.pairs.emp.pvalue101_until_250.rds")
GO.pairs.251_500 <- readRDS("robjects/GO.pairs.emp.pvalue251_until_500.rds")
GO.pairs.501_2000 <- readRDS("robjects/GO.pairs.emp.pvalue501_until_2000.rds")
GO.pairs.2001_3000 <- readRDS("robjects/GO.pairs.emp.pvalue2001_until_3000.rds")
GO.pairs.3001_4000 <- readRDS("robjects/GO.pairs.emp.pvalue3001_until_4000.rds")
GO.pairs.4001_5000 <- readRDS("robjects/GO.pairs.emp.pvalue4001_until_5000.rds")
GO.pairs.5001_6000 <- readRDS("robjects/GO.pairs.emp.pvalue5001_until_6000.rds")
GO.pairs.6001_7350 <- readRDS("robjects/GO.pairs.emp.pvalue6001_until_7350.rds")

```

```{r}
GO.pairs.emp <- rbind(
  GO.pairs.1_10[1:10,],
  GO.pairs.11_20[11:20,],
  GO.pairs.21_100[21:100,],
  GO.pairs.101_250[101:250,],
  GO.pairs.251_500[251:500,],
  GO.pairs.501_2000[501:2000,],
  GO.pairs.2001_3000[2001:3000,],
  GO.pairs.3001_4000[3001:4000,],
  GO.pairs.4001_5000[4001:5000,],
  GO.pairs.5001_6000[5001:6000,],
  GO.pairs.6001_7350[6001:7350,]
)
```

```{r}
# select emp.pval to plot in network 
GO.pairs.emp.select <- GO.pairs.emp %>% 
  filter(emp.pvalue <= 0.05)

# get GO ID for all the terms
GO <- as.list(GOTERM)
GO.df <- data.frame(ID = names(GO),
                    Description = sapply(GO, function(x) x@Term))

host_GO_term <- c()
for(i in 1:nrow(GO.pairs.emp.select))
  host_GO_term[i] = GO.df[grep(pattern = GO.pairs.emp.select$host_GO[i], GO.df$ID), "Description"]

para_GO_term <- c()
for(j in 1:nrow(GO.pairs.emp.select))
  para_GO_term[j] = GO.df[grep(pattern = GO.pairs.emp.select$para_GO[j], GO.df$ID), "Description"]

```

```{r}
# get weights for true number of interactions based on the number of genes in the terms

# load host and plasmo GO enrichment tables
hostGO_tab <- read.csv2("tables/dual_SPZ_vs_RBC_hostGO.csv")
paraGO_tab <- read.csv2("tables/dual_SPZ_vs_RBC_plasmoGO.csv")

host_GO_termsize <- hostGO_tab %>% 
  select(ID, Count) %>% 
  dplyr::rename(host_GO = ID, host_count = Count)

para_GO_termsize <- paraGO_tab %>% 
  select(GO.ID, Significant) %>% 
  dplyr::rename(para_GO = GO.ID, para_count = Significant)
```


```{r}
GO.pairs.emp.select.GOterm <- GO.pairs.emp.select %>% 
  mutate(host_GO_term = host_GO_term) %>% 
  mutate(para_GO_term = para_GO_term) %>%
  mutate(h_host_GO_term = paste("h_", host_GO_term)) %>%
  mutate(p_para_GO_term = paste("p_", para_GO_term)) %>% 
  mutate(scaled_true_n = scale(true_n, center = F)) %>% 
  left_join(., host_GO_termsize) %>% 
  left_join(., para_GO_termsize) %>% 
  mutate(ratio_trueN_termsize = 2*true_n/(host_count+para_count))
```

```{r}
ig <- graph_from_data_frame(GO.pairs.emp.select.GOterm[,c("h_host_GO_term",
                                                          "p_para_GO_term",
                                                          "scaled_true_n")], directed = F)
E(ig)$weight = GO.pairs.emp.select.GOterm$scaled_true_n 
V(ig)$color = c(rep("#FCA636FF", length(unique(GO.pairs.emp.select.GOterm$host_GO))), 
                rep("#6A00A8FF", length(unique(GO.pairs.emp.select.GOterm$para_GO))))
V(ig)$type = c(rep("host", length(unique(GO.pairs.emp.select.GOterm$host_GO))), 
                rep("parasite", length(unique(GO.pairs.emp.select.GOterm$para_GO))))
ig$layout <- layout_with_fr
# layout_with_fr
#com <- cluster_spinglass(ig, spins=5)
# mst <- mst(ig, algorithm="prim")
# com <- edge.betweenness.community(mst, weights=NA, directed=FALSE)
com <- cluster_leading_eigen(ig)
V(ig)$color <- com$membership+1
which.module <- com$membership[which(names(V(ig)) == "p_ antigenic variation")]
module <- subgraph(ig, vids = V(ig)[which(com$membership == 3)])
#V(module)$color <- ""yellow
set.seed(567457)
#pdf("GO_interaction_network_HPnodes.pdf", width = 20, height = 20)
#svg("GO_interaction_network.svg", width = 12, height = 12)
plot(module, 
     vertex.color = V(module)$color,
     #edge.color = E(ig)$color,
     vertex.size = 4, 
     #vertex.label=NA,
     label.cex = 0.1,
     edge.width = E(module)$weight
     #edge.curved=TRUE
     )
#dev.off()
```

