---
title: "Dual organism analysis - integrated libraries - malaria"
output:
  html_document:
    keep_md: true
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    code_folding: hide
  pdf_document:
    keep_md: true
    toc: true
    toc_depth: 3
    number_sections: true
    df_print: kable
always_allow_html: true
---

```{r setup, include=T} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(fig.width = 10, fig.height = 8) 
```

```{r}
library(Seurat)
library(patchwork)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
library(ggplot2)
library(SeuratData)
#library(celldex)
#install.packages("cowplot")
library(cowplot)
#devtools::install_github('cole-trapnell-lab/monocle3')
library(monocle3)
#remotes::install_github('satijalab/seurat-wrappers')
library(SeuratWrappers)
#BiocManager::install('multtest', force = T)
library(multtest)
library(RColorBrewer)
# install.packages('metap')
#library(metap)
#remotes::install_github("satijalab/seurat-data")

```

```{r}
# DotPlot function

myDotPlot <- function(
  object,
  assay = NULL,
  features,
  cols = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  idents = NULL,
  group.by = NULL,
  split.by = NULL,
  cluster.idents = FALSE,
  scale = TRUE,
  scale.by = 'radius',
  scale.min = NA,
  scale.max = NA,
  text.size = 10
) {
  assay <- assay %||% DefaultAssay(object = object)
  DefaultAssay(object = object) <- assay
  split.colors <- !is.null(x = split.by) && !any(cols %in% rownames(x = brewer.pal.info))
  scale.func <- switch(
    EXPR = scale.by,
    'size' = scale_size,
    'radius' = scale_radius,
    stop("'scale.by' must be either 'size' or 'radius'")
  )
  feature.groups <- NULL
  if (is.list(features) | any(!is.na(names(features)))) {
    feature.groups <- unlist(x = sapply(
      X = 1:length(features),
      FUN = function(x) {
        return(rep(x = names(x = features)[x], each = length(features[[x]])))
      }
    ))
    if (any(is.na(x = feature.groups))) {
      warning(
        "Some feature groups are unnamed.",
        call. = FALSE,
        immediate. = TRUE
      )
    }
    features <- unlist(x = features)
    names(x = feature.groups) <- features
  }
  cells <- unlist(x = CellsByIdentities(object = object, idents = idents))

  data.features <- FetchData(object = object, vars = features, cells = cells)
  data.features$id <- if (is.null(x = group.by)) {
    Idents(object = object)[cells, drop = TRUE]
  } else {
    object[[group.by, drop = TRUE]][cells, drop = TRUE]
  }
  if (!is.factor(x = data.features$id)) {
    data.features$id <- factor(x = data.features$id)
  }
  id.levels <- levels(x = data.features$id)
  data.features$id <- as.vector(x = data.features$id)
  if (!is.null(x = split.by)) {
    splits <- object[[split.by, drop = TRUE]][cells, drop = TRUE]
    if (split.colors) {
      if (length(x = unique(x = splits)) > length(x = cols)) {
        stop("Not enough colors for the number of groups")
      }
      cols <- cols[1:length(x = unique(x = splits))]
      names(x = cols) <- unique(x = splits)
    }
    data.features$id <- paste(data.features$id, splits, sep = '_')
    unique.splits <- unique(x = splits)
    id.levels <- paste0(rep(x = id.levels, each = length(x = unique.splits)), "_", rep(x = unique(x = splits), times = length(x = id.levels)))
  }
  data.plot <- lapply(
    X = unique(x = data.features$id),
    FUN = function(ident) {
      data.use <- data.features[data.features$id == ident, 1:(ncol(x = data.features) - 1), drop = FALSE]
      avg.exp <- apply(
        X = data.use,
        MARGIN = 2,
        FUN = function(x) {
          return(mean(x = expm1(x = x)))
        }
      )
      pct.exp <- apply(X = data.use, MARGIN = 2, FUN = PercentAbove, threshold = 0)
      return(list(avg.exp = avg.exp, pct.exp = pct.exp))
    }
  )
  names(x = data.plot) <- unique(x = data.features$id)
  if (cluster.idents) {
    mat <- do.call(
      what = rbind,
      args = lapply(X = data.plot, FUN = unlist)
    )
    mat <- scale(x = mat)
    id.levels <- id.levels[hclust(d = dist(x = mat))$order]
  }
  data.plot <- lapply(
    X = names(x = data.plot),
    FUN = function(x) {
      data.use <- as.data.frame(x = data.plot[[x]])
      data.use$features.plot <- rownames(x = data.use)
      data.use$id <- x
      return(data.use)
    }
  )
  data.plot <- do.call(what = 'rbind', args = data.plot)
  if (!is.null(x = id.levels)) {
    data.plot$id <- factor(x = data.plot$id, levels = id.levels)
  }
  ngroup <- length(x = levels(x = data.plot$id))
  if (ngroup == 1) {
    scale <- FALSE
    warning(
      "Only one identity present, the expression values will be not scaled",
      call. = FALSE,
      immediate. = TRUE
    )
  } else if (ngroup < 5 & scale) {
    warning(
      "Scaling data with a low number of groups may produce misleading results",
      call. = FALSE,
      immediate. = TRUE
    )
  }
  avg.exp.scaled <- sapply(
    X = unique(x = data.plot$features.plot),
    FUN = function(x) {
      data.use <- data.plot[data.plot$features.plot == x, 'avg.exp']
      if (scale) {
        data.use <- scale(x = data.use)
        data.use <- MinMax(data = data.use, min = col.min, max = col.max)
      } else {
        data.use <- log1p(x = data.use)
      }
      return(data.use)
    }
  )
  avg.exp.scaled <- as.vector(x = t(x = avg.exp.scaled))
  if (split.colors) {
    avg.exp.scaled <- as.numeric(x = cut(x = avg.exp.scaled, breaks = 20))
  }
  data.plot$avg.exp.scaled <- avg.exp.scaled
  data.plot$features.plot <- factor(
    x = data.plot$features.plot,
    levels = features
  )
  data.plot$pct.exp[data.plot$pct.exp < dot.min] <- NA
  data.plot$pct.exp <- data.plot$pct.exp * 100
  if (split.colors) {
    splits.use <- vapply(
      X = as.character(x = data.plot$id),
      FUN = gsub,
      FUN.VALUE = character(length = 1L),
      pattern =  paste0(
        '^((',
        paste(sort(x = levels(x = object), decreasing = TRUE), collapse = '|'),
        ')_)'
      ),
      replacement = '',
      USE.NAMES = FALSE
    )
    data.plot$colors <- mapply(
      FUN = function(color, value) {
        return(colorRampPalette(colors = c('grey', color))(20)[value])
      },
      color = cols[splits.use],
      value = avg.exp.scaled
    )
  }
  color.by <- ifelse(test = split.colors, yes = 'colors', no = 'avg.exp.scaled')
  if (!is.na(x = scale.min)) {
    data.plot[data.plot$pct.exp < scale.min, 'pct.exp'] <- scale.min
  }
  if (!is.na(x = scale.max)) {
    data.plot[data.plot$pct.exp > scale.max, 'pct.exp'] <- scale.max
  }
  if (!is.null(x = feature.groups)) {
    data.plot$feature.groups <- factor(
      x = feature.groups[data.plot$features.plot],
      levels = unique(x = feature.groups)
    )
  }
  plot <- ggplot(data = data.plot, mapping = aes_string(x = 'features.plot', y = 'id')) +
    geom_point(mapping = aes_string(size = 'pct.exp', color = color.by)) +
    scale.func(range = c(0, dot.scale), limits = c(scale.min, scale.max)) +
    theme(axis.title.x = element_blank(), axis.title.y = element_blank()) +
    guides(size = guide_legend(title = 'Percent Expressed')) +
    labs(
      x = 'Features',
      y = ifelse(test = is.null(x = split.by), yes = 'Identity', no = 'Split Identity')
    ) +
    theme_cowplot() +
    theme(axis.text.y=element_text(size=text.size)) +
    theme(axis.text.x=element_text(size=text.size, angle = 45, vjust = 1, hjust=1)) +
    coord_flip()
  
  if (!is.null(x = feature.groups)) {
    plot <- plot + facet_grid(
      facets = ~feature.groups,
      scales = "free_x",
      space = "free_x",
      switch = "y"
    ) + theme(
      panel.spacing = unit(x = 1, units = "lines"),
      strip.background = element_blank()
    )
  }
  if (split.colors) {
    plot <- plot + scale_color_identity()
  } else if (length(x = cols) == 1) {
    plot <- plot + scale_color_distiller(palette = cols)
  } else {
    plot <- plot + scale_color_gradient(low = cols[1], high = cols[2])
  }
  if (!split.colors) {
    plot <- plot + guides(color = guide_colorbar(title = 'Average Expression'))
  }
  return(plot)
}

# function to remove plasmo genes from each library
remove_plasmo_bg <- function(lib_name)
{
  # get cells that belong to control and RBC_control
  # seurat.subset <- subset(x = epithelial, subset = (stim == "Healthy" & stim == "Others") & (another_condition == "Ambigious"))
  cells_in_ctrl_conditions <- subset(lib_name, subset = Group == c("control","RBC_control"))
  
  # get the plasmo genes that are expressed in these conditions
  plasmo.genes.id <- grep(pattern = "gene-PF3D7", rownames(cells_in_ctrl_conditions))
  plasmo.obj <- cells_in_ctrl_conditions[plasmo.genes.id,]
  
  which.plasmo.genes.are.exp <- plasmo.obj[which(rowSums(plasmo.obj) > 0),]
  exp.plasmo.genes <- rownames(which.plasmo.genes.are.exp)

  # get 99th percentile of these genes
  pc99 = apply(which.plasmo.genes.are.exp[["RNA"]]@data,1,quantile,0.99)
  
  # remove these from all cells in the main lib + min expr to 0
  for(i in 1:length(pc99))
  {
    exp.plasmo.gene.index <- grep(rownames(lib_name), pattern = names(pc99)[i])
    lib_name[["RNA"]]@data[exp.plasmo.gene.index,] <- lib_name[["RNA"]]@data[exp.plasmo.gene.index,] - pc99[i]
    if(any(lib_name[["RNA"]]@data[exp.plasmo.gene.index,] < 0))
      lib_name[["RNA"]]@data[exp.plasmo.gene.index,
                             which(lib_name[["RNA"]]@data[exp.plasmo.gene.index,] < 0)] <- 0
  }
  
  return(lib_name)
}
```


```{r}

# EXP1_l2 <- readRDS("Jan27analysis/EXP1_l2_res0.9.rds")
# EXP2_l1 <- readRDS("Jan27analysis/EXP2_l1_res0.9.rds")
# EXP2_l2 <- readRDS("Jan27analysis/EXP2_l2_res0.9.rds")
# EXP2_l3 <- readRDS("Jan27analysis/EXP2_l3_res0.9.rds")
file_1_l1 = list.files("robjects/",pattern = "^dual_EXP1_l1.*\\_cellbender.rds$")
file_1_l2 = list.files("robjects/",pattern = "^dual_EXP1_l2.*\\_cellbender.rds$")
file_2_l1 = list.files("robjects/",pattern = "^dual_EXP2_l1.*\\_cellbender.rds$")
file_2_l2 = list.files("robjects/",pattern = "^dual_EXP2_l2_reseq.*\\_cellbender.rds$")
file_2_l3 = list.files("robjects/",pattern = "^dual_EXP2_l3.*\\_cellbender.rds$")

EXP1_l1 <- readRDS(paste0("robjects/",file_1_l1))
EXP1_l2 <- readRDS(paste0("robjects/",file_1_l2))
EXP2_l1 <- readRDS(paste0("robjects/",file_2_l1))
EXP2_l2 <- readRDS(paste0("robjects/",file_2_l2))
EXP2_l3 <- readRDS(paste0("robjects/",file_2_l3))
```

# Before integration {.tabset}

## Included cells
```{r}
DimPlot(EXP1_l1, reduction = "umap", group.by = "donor_id") + plot_annotation(title = "EXP1_l1")
ggplot(EXP1_l1@meta.data, aes(x = nFeature_RNA)) + 
  geom_histogram(binwidth = 50) +
  facet_wrap( ~ donor_id)

DimPlot(EXP1_l2, reduction = "umap", group.by = "donor_id") + plot_annotation(title = "EXP1_l2")
ggplot(EXP1_l2@meta.data, aes(x = nFeature_RNA)) + 
  geom_histogram(binwidth = 50) +
  facet_wrap( ~ donor_id)

DimPlot(EXP2_l1, reduction = "umap", group.by = "donor_id") + plot_annotation(title = "EXP2_l1")
ggplot(EXP2_l1@meta.data, aes(x = nFeature_RNA)) + 
  geom_histogram(binwidth = 50) +
  facet_wrap( ~ donor_id)

DimPlot(EXP2_l2, reduction = "umap", group.by = "donor_id") + plot_annotation(title = "EXP2_l2")
ggplot(EXP2_l2@meta.data, aes(x = nFeature_RNA)) + 
  geom_histogram(binwidth = 50) +
  facet_wrap( ~ donor_id)

DimPlot(EXP2_l3, reduction = "umap", group.by = "donor_id") + plot_annotation(title = "EXP2_l3")
ggplot(EXP2_l3@meta.data, aes(x = nFeature_RNA)) + 
  geom_histogram(binwidth = 50) +
  facet_wrap( ~ donor_id)
```

```{r}
exp.list <- list(EXP1_l1 = EXP1_l1,
  EXP1_l2 = EXP1_l2,
  EXP2_l1 = EXP2_l1,
  EXP2_l2 = EXP2_l2,
  EXP2_l3 = EXP2_l3
            )

# normalize and identify variable features for each dataset independently
exp.list <- lapply(X = exp.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = exp.list)
# retrieve anchors

anchors <- FindIntegrationAnchors(object.list = exp.list, anchor.features = features)

# this command creates an 'integrated' data assay
dual.integrated <- IntegrateData(anchorset = anchors)

```

```{r}
# Let’s set the assay to RNA and visualize the datasets before integration.
dual.integrated.RNA <- dual.integrated
DefaultAssay(dual.integrated.RNA) <- "RNA"

#Let’s do normalization, HVG finding, scaling, PCA, and UMAP on the un-integrated (RNA) assay:

dual.integrated.RNA <- NormalizeData(dual.integrated.RNA, verbose = F)
dual.integrated.RNA <- FindVariableFeatures(dual.integrated.RNA, selection.method = "vst", nfeatures = 2000, verbose = F)
dual.integrated.RNA <- ScaleData(dual.integrated.RNA, verbose = F)
dual.integrated.RNA <- RunPCA(dual.integrated.RNA, npcs = 30, verbose = F)
dual.integrated.RNA <- RunUMAP(dual.integrated.RNA, reduction = "pca", dims = 1:30, verbose = F)
```

```{r}
## Warning: The default method for RunUMAP has changed from calling Python UMAP via reticulate to the R-native UWOT using the cosine metric
## To use Python UMAP via reticulate, set umap.method to 'umap-learn' and metric to 'correlation'
## This message will be shown once per session

# UMAP plot of the datasets before integration shows clear separation. Note that we can use patchwork syntax with Seurat plotting functions:

DimPlot(dual.integrated.RNA,reduction = "umap", group.by = "orig.ident") + ggtitle("Before Integration")
```
# After integration {.tabset}

```{r}
DefaultAssay(dual.integrated) <- "integrated"

# Run the standard workflow for visualization and clustering
dual.integrated <- ScaleData(dual.integrated, verbose = FALSE)
dual.integrated <- RunPCA(dual.integrated, npcs = 30, verbose = FALSE)
dual.integrated <- RunUMAP(dual.integrated, reduction = "pca", dims = 1:30)
dual.integrated <- FindNeighbors(dual.integrated, reduction = "pca", dims = 1:30)
dual.integrated <- FindClusters(dual.integrated, resolution = 0.5)


dual.integrated@meta.data <- dual.integrated@meta.data %>% 
  mutate(Donorid = case_when(
    orig.ident %in% c("EXP1_l2", "EXP1_l1") & donor_id == "donor0" ~ "D1",
    orig.ident %in% c("EXP1_l2", "EXP1_l1") & donor_id == "donor1" ~ "D2",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor0" ~ "D3",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor1" ~ "D4",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor2" ~ "D5"
  ))

#saveRDS(dual.integrated, "dual.integrated_all_libs_preprocessed.rds")

DimPlot(dual.integrated,reduction = "umap", group.by = "orig.ident") + ggtitle("After Integration")

```

```{r}
#DefaultAssay(dual.integrated) <- "RNA"
DimPlot(dual.integrated, group.by = "Donorid",reduction = "umap", label = "F")
```

```{r}
DefaultAssay(dual.integrated) <- "RNA"
FeaturePlot(dual.integrated, features = c("XIST"))

```

```{r}
FeaturePlot(dual.integrated, features = c("CD14", "FCGR3A"))
```

```{r}
DefaultAssay(dual.integrated) <- "integrated"
DimPlot(dual.integrated, group.by = "seurat_clusters",reduction = "umap", label = "T")
```

```{r}
DimPlot(dual.integrated, group.by = "Group",reduction = "umap", label = "T")
```
 
## Plasmodium RNA in samples
```{r}
breaks <- 10^(-10:10)
minor_breaks <- rep(1:9, 21)*(10^rep(-10:10, each=9))

ggplot(dual.integrated@meta.data, aes(x = percent.plasmo)) +
  geom_histogram(bins = 70, fill = "white", colour = "blue") +
  facet_wrap(~ factor(Group, levels = c("control", "sporozoite_bystander", "sporozoite_infected",
                      "RBC_control", "RBC_bystander", "RBC_infected"))) +
  theme_bw() +
  scale_y_log10(minor_breaks = c(5, 50, 500, 5000)) +
  theme(axis.line = element_line(colour = "black"),
      panel.grid.major = element_line(colour = "gray75"),
      panel.grid.minor = element_line(colour = "gray"),
      panel.border = element_blank(),
      panel.background = element_blank()) +
      theme(axis.text = element_text(size = 11)) +
      theme(strip.background =element_rect(fill="aliceblue", colour = "white"),
            strip.text.x = element_text(size = 11))

ggsave("plasmo.percent_by_conditions_cellbender.pdf", width = 6, height = 4)

```

```{r}
plasmo.percent.table <- dual.integrated@meta.data %>% 
  tibble::rownames_to_column("Cell") %>% 
  select(Cell, Group, percent.plasmo, percent.mt) %>% 
  group_by(Group) %>% 
  summarise(plasmo_median = median(percent.plasmo, na.rm = T),
            plasmo_max = max(percent.plasmo, na.rm = T),
            plasmo_min = min(percent.plasmo, na.rm = T),
            mt_median = median(percent.mt, na.rm = T),
            number_of_cells = n())

DT::datatable(plasmo.percent.table)
```
 
## Features in clusters
```{r}
myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
lib_name = "integrated"
# percent.mt on umap

meta <- dual.integrated@meta.data %>% 
  rownames_to_column("Cell") %>% 
  select("Cell", "nFeature_RNA", "percent.mt", "nCount_RNA", "percent.plasmo")

umap_embed <- dual.integrated@reductions[["umap"]]@cell.embeddings %>% 
  as.data.frame() %>% 
  rownames_to_column("Cell") %>%
  left_join(., meta) %>% 
  mutate(lib = lib_name)

# mt.percent on umap
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(0, max(umap_embed$percent.mt)))
ggplot(umap_embed, aes(UMAP_1, UMAP_2, colour = percent.mt)) +
  geom_point(size = 0.3, alpha = 0.8) +
  facet_wrap( ~ lib, ncol = 2, scales = "free") +
  sc +
  theme_bw()

# nF on umap
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(min(umap_embed$nFeature_RNA), max(umap_embed$nFeature_RNA)))
ggplot(umap_embed, aes(UMAP_1, UMAP_2, colour = nFeature_RNA)) +
  geom_point(size = 0.3, alpha = 0.8) +
  facet_wrap( ~ lib, ncol = 2, scales = "free") +
  sc +
  theme_bw()

# nCount on umap
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(min(umap_embed$nCount_RNA), max(umap_embed$nCount_RNA)))
ggplot(umap_embed, aes(UMAP_1, UMAP_2, colour = nCount_RNA)) +
  geom_point(size = 0.3, alpha = 0.8) +
  facet_wrap( ~ lib, ncol = 2, scales = "free") +
  sc +
  theme_bw()

# parasite on umap
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(min(umap_embed$percent.plasmo), max(umap_embed$percent.plasmo)))
ggplot(umap_embed, aes(UMAP_1, UMAP_2, colour = percent.plasmo)) +
  geom_point(size = 0.3, alpha = 0.8) +
  facet_wrap( ~ lib, ncol = 2, scales = "free") +
  sc +
  theme_bw()

ggsave("plasmo.percent_umap.pdf")
```
## Clusters
```{r}
DimPlot(dual.integrated, group.by = "seurat_clusters",reduction = "umap", label = "T")
```
## Plasmo percent in clusters
```{r}
plasmo.percent.clusters.table <- dual.integrated@meta.data %>% 
  tibble::rownames_to_column("Cell") %>% 
  select(Cell, Group, percent.plasmo, percent.mt, seurat_clusters) %>% 
  group_by(seurat_clusters, Group) %>% 
  summarise(plasmo_median = median(percent.plasmo, na.rm = T),
            plasmo_max = max(percent.plasmo, na.rm = T),
            plasmo_min = min(percent.plasmo, na.rm = T),
            mt_median = median(percent.mt, na.rm = T),
            number_of_cells = n())

DT::datatable(plasmo.percent.clusters.table)
```

## Top 10 markers in each cluster
```{r}
imm.comb.markers <- FindAllMarkers(dual.integrated, only.pos = F, min.pct = 0.25, logfc.threshold = 0.25)

imm.comb.markers %>%
    group_by(cluster) %>%
    top_n(n = 15, wt = avg_log2FC) -> top15

DT::datatable(top15)

#write.csv2(top10, "integrated_data_noTBcells_cluster_markers.csv", row.names = F, quote = F)
DefaultAssay(dual.integrated) <- "RNA"
#pdf("Heatmap_gene_expr_integrated_data_noTBcells.pdf")
#DoHeatmap(dual.integrated, label = F) + NoLegend() #+ theme(text = element_text(size = 6.5))
#dev.off()

top15 %>%
    group_by(cluster) %>%
    top_n(n = 5, wt = avg_log2FC) -> top5

DefaultAssay(dual.integrated) <- "RNA"
myDotPlot(dual.integrated, features = unique(top5$gene),  dot.scale = 2) + RotatedAxis()


```


```{r}
#dual.integrated <- subset(dual.integrated, subset = nFeature_RNA >= 1500)
```

# Remove T, B cells
```{r}
# remove T and B cells

# rename clusters
# dual.integrated <- RenameIdents(dual.integrated, 
#                                 `0` = "Classical monocytes I (FOS)", 
#                                 `1` = "Activated monocytes I (IL1B CXCL2/1)", 
#                                 `2` = "Classical monocytes II (STAT1)",
#                                 `3` = "Classical monocytes III (LGMN)",
#                                 `4` = "Activated monocytes II (IFIT2/3, ISG15)", 
#                                 `5` = "Activated monocytes III (IL12 CD40 TNF)",
#                                 `6` = "Plasmo",
#                                 `7` = "Non-classical monocytes (FCGR3A !CD14)",
#                                 `8` = "Classical monocytes IV (CCL24)",
#                                 `9` = "CD8 T-cells",
#                                 `10` = "cDC1", 
#                                 `11` = "B-cells")

# sept 11, 2023:
# rename clusters
dual.integrated <- RenameIdents(dual.integrated,
                                `0` = "Classical monocytes I (FOS)",
                                `1` = "Activated monocytes I (IL1B CXCL2/1)",
                                `2` = "Classical monocytes II (STAT1)",
                                `3` = "Classical monocytes III (LGMN)",
                                `4` = "Activated monocytes II (IFIT2/3, ISG15)",
                                `5` = "Activated monocytes III (IL12 CD40 TNF)",
                                `6` = "Non-classical monocytes (FCGR3A !CD14)",
                                `7` = "Plasmo",
                                `8` = "B/T",
                                `9` = "cDC1",
                                `10` = "Classical monocytes IV (CCL24)",
                                `11` = "B-cells")

dual.integrated$predicted.celltype <- Idents(dual.integrated)

pdf("dimplot_dual.integrated_withTB_cellbender_plasmo.bg.removed.pdf", height = 5, width = 10)
DimPlot(dual.integrated, label = F)
dev.off()

top15 %>%
    group_by(cluster) %>%
    top_n(n = 5, wt = avg_log2FC) -> top5

#pdf("dotplot_dual.integrated_withTB_cellbender_plasmo.bg.removed.pdf", height = 5, width = 10)
myDotPlot(dual.integrated, features = unique(top5$gene),  dot.scale = 2, text.size = 5) #+ RotatedAxis() #, text.size = 10
#dev.off()

# saveRDS(dual.integrated, "dual_integrated_withTB_cellbender.rds")
```

```{r}
# plot plasmo.percent by celltype

breaks <- 10^(-10:10)
minor_breaks <- rep(1:9, 21)*(10^rep(-10:10, each=9))

ggplot(dual.integrated@meta.data, aes(x = percent.plasmo)) +
  geom_histogram(bins = 70, fill = "white", colour = "blue") +
  facet_wrap(~ factor(predicted.celltype)) +
  theme_bw() +
  scale_y_log10(minor_breaks = c(5, 50, 500, 5000)) +
  theme(axis.line = element_line(colour = "black"),
      panel.grid.major = element_line(colour = "gray75"),
      panel.grid.minor = element_line(colour = "gray"),
      panel.border = element_blank(),
      panel.background = element_blank()) +
      theme(axis.text = element_text(size = 11)) +
      theme(strip.background =element_rect(fill="aliceblue", colour = "white"),
            strip.text.x = element_text(size = 11))

#ggsave("plasmo.percent_by_celltype_withTB_cellbender_plasmo.bg.removed.pdf", height = 10, width = 15)
```

```{r}
# remove T and B
#dual.integrated.TBremoved <- subset(dual.integrated, subset = predicted.celltype == "CD8 T-cells", invert = T)
dual.integrated.TBremoved <- subset(dual.integrated, subset = predicted.celltype == "B-cells", invert = T)
dual.integrated.TBremoved <- subset(dual.integrated.TBremoved, subset = predicted.celltype == "B/T", invert = T)

#pdf("dimplot_dual.integrated_noTB_cellbender_plasmo.bg.removed.pdf", height = 5, width = 10)
DimPlot(dual.integrated.TBremoved, label = F)
#dev.off()

#saveRDS(dual.integrated.TBremoved, "dual.integrated.TBremoved.cellbender_plasmo.bg.removed.rds")
```

```{r}

#dual.TBremoved <- readRDS("robjects/dual.integrated.TBremoved.cellbender.rds")
dual.TBremoved <- dual.integrated.TBremoved
dual.integrated.bg.removed <- remove_plasmo_bg(lib_name = dual.integrated)
# remove T and B cells and only cells from human analysis
#dual.TBremoved <- dual.integrated[,colnames(dual.integrated) %in% colnames(immune.combined.TBremoved)]
```

<!-- ```{r} -->
<!-- # copy cell type and cell from only-human analysis (immune.combined.TBremoved) -->
<!-- # add in cell type -->
<!-- human.meta <- immune.combined.TBremoved@meta.data %>%  -->
<!--   rownames_to_column("CellHash") %>%  -->
<!--   select(CellHash, predicted.celltype) -->

<!-- dual.TBremoved@meta.data <- dual.TBremoved@meta.data %>%  -->
<!--   rownames_to_column("CellHash") %>% -->
<!--   left_join(., human.meta) %>%  -->
<!--   column_to_rownames("CellHash") -->
<!-- ``` -->

# Re-analyse after removing T, B cells {.tabset}
```{r}
DefaultAssay(dual.TBremoved) <- "RNA"

dual.TBremoved.list <- SplitObject(dual.TBremoved, split.by = "orig.ident")
dual.TBremoved.list <- lapply(X = dual.TBremoved.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
features <- SelectIntegrationFeatures(object.list = dual.TBremoved.list)
anchors <- FindIntegrationAnchors(object.list = dual.TBremoved.list, anchor.features = features)

# set k.weight so that it is not larger than the number of cells in the smallest dataset
# https://github.com/satijalab/seurat/issues/3936
dual.TBremoved <- IntegrateData(anchorset = anchors, k.weight = 46)
DefaultAssay(dual.TBremoved) <- "integrated"

dual.TBremoved <- ScaleData(dual.TBremoved, verbose = FALSE)
dual.TBremoved <- RunPCA(dual.TBremoved, npcs = 30, verbose = FALSE)
dual.TBremoved <- RunUMAP(dual.TBremoved, reduction = "pca", dims = 1:10)
dual.TBremoved <- FindNeighbors(dual.TBremoved, reduction = "pca", dims = 1:10)
dual.TBremoved <- FindClusters(dual.TBremoved, resolution = 0.5)


```

```{r}
#DefaultAssay(dual.TBremoved) <- "RNA"
DimPlot(dual.TBremoved, group.by = "Donorid",reduction = "umap", label = "F")
```

```{r}
DefaultAssay(dual.TBremoved) <- "RNA"
FeaturePlot(dual.TBremoved, features = c("XIST"))

```

```{r}
FeaturePlot(dual.TBremoved, features = c("CD14", "FCGR3A"))
```

```{r}
DefaultAssay(dual.TBremoved) <- "integrated"
DimPlot(dual.TBremoved, group.by = "seurat_clusters",reduction = "umap", label = "T")
```

```{r}
DimPlot(dual.TBremoved, group.by = "Group",reduction = "umap", label = "T")
```

```{r}
#pdf("dimplot_dual.integrated_noTB_cellbender_plasmo.bg.removed_reintegration.pdf", height = 5, width = 10)
DimPlot(dual.TBremoved, group.by = "predicted.celltype",reduction = "umap", label = F) + ggtitle("After re-integration")
#dev.off()
```

```{r}
dual.plasmo <- subset(dual.TBremoved, subset = percent.plasmo >= 1) # 7014 cells

#pdf("dimplot_dual.integrated_noTB_cellbender_plasmo.bg.removed_reintegration_plasmo_greater1.pdf", height = 5, width = 10)
DimPlot(dual.plasmo, group.by = "predicted.celltype", reduction = "umap") + ggtitle("percent.plasmo > 1")
#dev.off()
```

## Plasmodium RNA in samples
```{r}
breaks <- 10^(-10:10)
minor_breaks <- rep(1:9, 21)*(10^rep(-10:10, each=9))

# remove cells that have plasmo.percent 0


ggplot(dual.plasmo@meta.data, aes(x = percent.plasmo)) +
  geom_histogram(bins = 70, fill = "white", colour = "blue") +
  facet_wrap(~ factor(Group, levels = c("control", "sporozoite_bystander", "sporozoite_infected",
                      "RBC_control", "RBC_bystander", "RBC_infected"))) +
  theme_bw() +
  #scale_y_log10(minor_breaks = c(5, 50, 500, 5000)) +
  theme(axis.line = element_line(colour = "black"),
      panel.grid.major = element_line(colour = "gray75"),
      panel.grid.minor = element_line(colour = "gray"),
      panel.border = element_blank(),
      panel.background = element_blank()) +
      theme(axis.text = element_text(size = 11)) +
      theme(strip.background =element_rect(fill="aliceblue", colour = "white"),
            strip.text.x = element_text(size = 11))

ggplot(dual.TBremoved@meta.data, aes(x = percent.plasmo)) +
  geom_histogram(bins = 70, fill = "white", colour = "blue") +
  facet_wrap(~ factor(Group, levels = c("control", "sporozoite_bystander", "sporozoite_infected",
                      "RBC_control", "RBC_bystander", "RBC_infected"))) +
  theme_bw() +
  scale_y_log10(minor_breaks = c(5, 50, 500, 5000)) +
  theme(axis.line = element_line(colour = "black"),
      panel.grid.major = element_line(colour = "gray75"),
      panel.grid.minor = element_line(colour = "gray"),
      panel.border = element_blank(),
      panel.background = element_blank()) +
      theme(axis.text = element_text(size = 11)) +
      theme(strip.background =element_rect(fill="aliceblue", colour = "white"),
            strip.text.x = element_text(size = 11))

```

```{r}
plasmo.percent.table <- dual.TBremoved@meta.data %>% 
  tibble::rownames_to_column("Cell") %>% 
  select(Cell, Group, percent.plasmo, percent.mt) %>% 
  group_by(Group) %>% 
  summarise(plasmo_median = median(percent.plasmo, na.rm = T),
            plasmo_max = max(percent.plasmo, na.rm = T),
            plasmo_min = min(percent.plasmo, na.rm = T),
            mt_median = median(percent.mt, na.rm = T),
            number_of_cells = n())

DT::datatable(plasmo.percent.table)
```

## Features in clusters
```{r}
myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
lib_name = "integrated"
# percent.mt on umap

meta <- dual.TBremoved@meta.data %>% 
  rownames_to_column("Cell") %>% 
  select("Cell", "nFeature_RNA", "percent.mt", "nCount_RNA", "percent.plasmo")

umap_embed <- dual.TBremoved@reductions[["umap"]]@cell.embeddings %>% 
  as.data.frame() %>% 
  rownames_to_column("Cell") %>%
  left_join(., meta) %>% 
  mutate(lib = lib_name)

# mt.percent on umap
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(0, max(umap_embed$percent.mt)))
ggplot(umap_embed, aes(UMAP_1, UMAP_2, colour = percent.mt)) +
  geom_point(size = 0.3, alpha = 0.8) +
  facet_wrap( ~ lib, ncol = 2, scales = "free") +
  sc +
  theme_bw()

# nF on umap
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(min(umap_embed$nFeature_RNA), max(umap_embed$nFeature_RNA)))
ggplot(umap_embed, aes(UMAP_1, UMAP_2, colour = nFeature_RNA)) +
  geom_point(size = 0.3, alpha = 0.8) +
  facet_wrap( ~ lib, ncol = 2, scales = "free") +
  sc +
  theme_bw()

# nCount on umap
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(min(umap_embed$nCount_RNA), max(umap_embed$nCount_RNA)))
ggplot(umap_embed, aes(UMAP_1, UMAP_2, colour = nCount_RNA)) +
  geom_point(size = 0.3, alpha = 0.8) +
  facet_wrap( ~ lib, ncol = 2, scales = "free") +
  sc +
  theme_bw()

# parasite on umap
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(min(umap_embed$percent.plasmo), max(umap_embed$percent.plasmo)))
ggplot(umap_embed, aes(UMAP_1, UMAP_2, colour = percent.plasmo)) +
  geom_point(size = 0.3, alpha = 0.8) +
  facet_wrap( ~ lib, ncol = 2, scales = "free") +
  sc +
  theme_bw()
```

```{r}
#saveRDS(dual.TBremoved, "dual.integrated.TBremoved.cellbender_plasmo.bg.removed_reintegration.rds")
```


<!-- # Which Plasmodium reads were found in Ctrl? {.tabset} -->

<!-- ## Which Plasmo genes are found in ctrl and stim conditions? -->
<!-- ```{r} -->
<!-- # Collect Plasmo genes in all the conditions -->
<!-- plasmo.genes.id <- grep(pattern = "gene-PF3D7", rownames(dual.TBremoved)) -->
<!-- plasmo.genes <- dual.TBremoved[plasmo.genes.id,] -->

<!-- plasmo.genes.cellcount<- data.frame() -->
<!-- a = 1 -->
<!-- for(i in 1:nrow(plasmo.genes)) -->
<!-- { -->
<!--   for(j in 1:length(unique(plasmo.genes@meta.data$Group))) -->
<!--   { -->
<!--     print(c(i,j)) -->
<!--     gene <- rownames(plasmo.genes[i]) -->
<!--     plasmo.genes.cellcount[i,1] <- gene -->
<!--     #plasmo.genes.cellcount[a,2] <- unique(plasmo.genes@meta.data$Group)[j] -->
<!--     choose.cells.in.group <- plasmo.genes@meta.data %>%  -->
<!--       filter(Group == unique(plasmo.genes@meta.data$Group)[j]) %>%  -->
<!--       tibble::rownames_to_column("Cell") %>%  -->
<!--       pull(Cell) -->
<!--     plasmo.genes.cellcount[i,unique(plasmo.genes@meta.data$Group)[j]] <- sum(plasmo.genes[['RNA']]@counts[gene,choose.cells.in.group] > 0) -->
<!--     #a = a+1 -->
<!--   }  -->
<!-- } -->
<!-- colnames(plasmo.genes.cellcount)[1] <- "gene" -->
<!-- saveRDS(plasmo.genes.cellcount, "plasmo.genes.cellcount.rds") -->

<!-- plasmo.genes.cellcount.long <- plasmo.genes.cellcount %>%  -->
<!--   pivot_longer( -->
<!--     cols = RBC_bystander:sporozoite_bystander, -->
<!--     names_to = "Group", -->
<!--     values_to = "Number_of_cells" -->
<!--   ) -->

<!-- ``` -->
```{r}
# plot plasmo cells in human analysis
host <- readRDS("robjects/immune.combined.TBremoved.rds")

# get cell names from plasmo cluster
plasmo.cluster.cells <- dual.TBremoved@meta.data %>% 
  rownames_to_column("Cell") %>% 
  filter(predicted.celltype == "Plasmo") # 539 cells

# make meta data column in host to say yes plasmo or no: # 513 cells
host@meta.data <- host@meta.data %>% 
  rownames_to_column("Cell") %>% 
  mutate(plasmo_cluster = case_when(
    Cell %in% plasmo.cluster.cells$Cell ~ "yes",
    .default = "no"
  )) %>% 
  column_to_rownames("Cell")

# dimplot umap of host with new column
DimPlot(host, reduction = "umap", group.by = "plasmo_cluster")

# group_cols = c('control' = '#e6af2e', 'RBC_bystander' = '#f7a78d', 'RBC_control' = '#ef4f1a', 'RBC_infected' = '#6b0504', 'sporozoite_bystander' = '#c2fff0', 'sporozoite_infected' = '#00a39b')

group_cols = c('yes' = '#6b0504', 'no' = '#e6af2e')

#pdf("dimplot_plasmo.cluster_in_host_cellbender_plasmo.bg.removed_reintegration.pdf", width = 5, height = 5)
DimPlot(host, group.by = "plasmo_cluster",reduction = "umap", label = "F", cols = group_cols) + ggtitle("plasmo cluster")
#dev.off()
```

```{r}
plasmo.genes <- de$gene[grep(pattern = "PF3D7", de$gene)]
de.plasmo <- de %>% 
  filter(!grepl(pattern = "PF3D7", gene)) %>% 
  filter(padj <= 0.01) %>% 
  filter(abs(log2FoldChange) >= 2) %>% 
  filter(log2FoldChange < 0)
```

