---
title: "pseudobulk RNA-seq DE analysis - Act. Monocytes"
output:
  html_document:
    df_print: paged
    code_folding: hide
  pdf_document: default
  toc: TRUE
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
library(Seurat)
library(patchwork)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
library(ggplot2)
library(SeuratData)
#library(celldex)
#install.packages("cowplot")
library(cowplot)
#devtools::install_github('cole-trapnell-lab/monocle3')
library(monocle3)
#remotes::install_github('satijalab/seurat-wrappers')
library(SeuratWrappers)
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(ggrepel)
library(data.table)
library(ComplexHeatmap)
library(viridis)
# mulattoes::install('multtest')
# install.packages('metap')
#library(metap)
#remotes::install_github("satijalab/seurat-data")
```

```{r}
immune.combined <- readRDS("immune.combined_all_libs_preprocessed.rds")
immune.combined@assays[["integrated"]]@counts <- immune.combined@assays[["RNA"]]@counts

immune.combined@meta.data <- immune.combined@meta.data %>% 
  mutate(Donorid = case_when(
    orig.ident %in% c("EXP1_l2", "EXP1_l1") & donor_id == "donor0" ~ "D1",
    orig.ident %in% c("EXP1_l2", "EXP1_l1") & donor_id == "donor1" ~ "D2",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor0" ~ "D3",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor1" ~ "D4",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor2" ~ "D5"
  ))

immune.combined@meta.data <- immune.combined@meta.data %>% 
  mutate(act_inact = case_when(
    str_detect(predicted.celltype, "Monocytes activated") ~ "Activated monocytes",
    .default = predicted.celltype
  ))

table(immune.combined$Donorid, immune.combined$orig.ident)
immune.combined@meta.data$cond_group <- paste(immune.combined@meta.data$Group,
                                               immune.combined@meta.data$Donorid,
                                               sep = "")

cts <- AggregateExpression(immune.combined,
              group.by = c("act_inact", "cond_group"),
              assays = "RNA",
              slot = "counts",
              return.seurat = F)
cts <- cts$RNA

# transpose
cts.t <- as.data.frame(t(cts))

# split.data.frame
splitRows <- gsub('_.*', '', rownames(cts.t))
cts.split <- split.data.frame(cts.t,
                 f = factor(splitRows))

# fix colnames and transpose
cts.modified <- lapply(cts.split, function(x){
  rownames(x) <- gsub("(.+?)(\\_.*)", "\\2", rownames(x))
  rownames(x) <- gsub("^_", "\\1", rownames(x))
  t(x)
})

act.mono <- cts.t %>% 
  rownames_to_column("condition") %>% 
  filter(str_detect(condition, "Activated monocytes")) %>% 
  column_to_rownames("condition") %>% 
  t()

colnames(act.mono) = gsub(x = colnames(act.mono), pattern = "Activated monocytes_", replacement = "")
```

<!-- ```{r} -->
<!-- pcs <- function(object, intgroup = "condition", ntop = 500) -->
<!-- { -->
<!--   rv <- rowVars(assay(object)) -->
<!--   select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, -->
<!--       length(rv)))] -->
<!--   pca <- prcomp(t(assay(object)[select, ])) -->
<!--   percentVar <- pca$sdev^2/sum(pca$sdev^2) -->
<!--   if (!all(intgroup %in% names(colData(object)))) { -->
<!--       stop("the argument 'intgroup' should specify columns of colData(dds)") -->
<!--   } -->
<!--   intgroup.df <- as.data.frame(colData(object)[, intgroup, -->
<!--       drop = FALSE]) -->
<!--   group <- if (length(intgroup) > 1) { -->
<!--       factor(apply(intgroup.df, 1, paste, collapse = " : ")) -->
<!--   } -->
<!--   else { -->
<!--       colData(object)[[intgroup]] -->
<!--   } -->
<!--   d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2], group = group, -->
<!--       intgroup.df, name = colnames(object)) -->

<!--   return(d) -->
<!-- } -->

<!-- ``` -->


<!-- ```{r} -->
<!-- # add all activated celltypes -->

<!-- act.mono.nfkb <- cts.modified$`Monocytes activated (Nfkb)` -->
<!-- act.mono.nfkb.ifn <- cts.modified$`Monocytes activated (Nfkb + type I IFN)` -->
<!-- act.mono.ifn <- cts.modified$`Monocytes activated (type I IFN signature)` -->

<!-- common_conditions <- intersect(intersect(colnames(act.mono.nfkb), colnames(act.mono.nfkb.ifn)), colnames(act.mono.ifn)) -->

<!-- conditions <- unique(c(colnames(act.mono.ifn), colnames(act.mono.nfkb), colnames(act.mono.nfkb.ifn))) -->

<!-- act.mono <- data.frame() -->

<!-- for(i in 1:length(conditions)) -->
<!-- { -->
<!--   column <- conditions[i] -->

<!--   act.mono[1:24472,column] <- act.mono.ifn[,which(colnames(act.mono.ifn)==column)] + -->
<!--     act.mono.nfkb[,which(colnames(act.mono.nfkb)==column)] + -->
<!--     act.mono.nfkb.ifn[,which(colnames(act.mono.nfkb.ifn)==column)] -->
<!-- } -->
<!-- rownames(act.mono) <- rownames(act.mono.ifn) -->

<!-- ``` -->

# RBC_infected (base) vs SPZ_infected

```{r}
# Monocytes activated (type I IFN signature)
# Run DE analysis


# 1. Get counts matrix

condition1 <- "RBC_infected"
condition2 <- "sporozoite_infected"
#celltype <- "Monocytes activated (Nfkb + type I IFN)"

counts <- act.mono %>% 
  data.frame() %>% 
  dplyr::select(c(contains(condition1), contains(condition2)))


# 2 Generate metadata
colData <- data.frame(sample = colnames(counts))
colData$condition = sapply(str_split(colData$sample, "D"), function(x) x[1])
colData <- colData %>% 
  column_to_rownames("sample")

# more info for metadata

# DEseq2 object
dds <- DESeqDataSetFromMatrix(countData = counts,
                             colData = colData,
                             design = ~condition)

# filter dds
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]

dds$condition <- relevel(dds$condition, ref = "RBC_infected") #otherwise, alphabetical
dds <- DESeq(dds)

# Transform counts for data visualization
rld <- rlog(dds, blind=F)

# Plot PCA
DESeq2::plotPCA(rld, ntop = 500, intgroup = "condition")

# Extract the rlog matrix from the object and compute pairwise correlation values
rld_mat <- assay(rld)
rld_cor <- cor(rld_mat)

# Plot heatmap
pheatmap(rld_cor, annotation = colData[, c("condition"), drop=F])

# check the coefficients
resultsNames(dds)
comparison <- resultsNames(dds)[2]

res <- results(dds, name = comparison, alpha = 0.1)
# res <- res <- lfcShrink(dds, 
#                  coef =  comparison,
#                  res=res)
#res


# Turn the DESeq2 results object into a tibble for use with tidyverse functions
res_tbl <- res %>%
  data.frame() %>%
  rownames_to_column(var = "gene") %>%
  as_tibble() %>%
  arrange(pvalue)

# Check results output
#res_tbl 

# Write all results to file
# write.csv(res_tbl,
#           paste0(comparison,".csv"),
#           quote = FALSE, 
#           row.names = FALSE)

####
padj_cutoff <- 0.1

# Subset the significant results
sig_res <- dplyr::filter(res_tbl, padj <= padj_cutoff) %>%
  dplyr::arrange(padj)

# Check significant genes output
sig_res_pos <- sig_res %>%
  filter(log2FoldChange >= 0)

DT::datatable(sig_res_pos)


sig_res_neg <- sig_res %>%
  filter(log2FoldChange < 0)

DT::datatable(sig_res_neg)

# Write all results to file
# write.csv(sig_res,
#           paste0(comparison,".csv"),
#           quote = FALSE, 
#           row.names = FALSE)

## Extract normalized counts from dds object
normalized_counts <- counts(dds, normalized = TRUE)

## Extract normalized counts for significant genes only
sig_counts <- normalized_counts[rownames(normalized_counts) %in% sig_res$gene, ]

## Set a color-blind friendly palette
heat_colors <- rev(brewer.pal(11, "PuOr"))


```


```{r, fig.height = 12}

vsd <- assay(vst(dds))
z <- t(scale(t(vsd)))
z <- z[rownames(z) %in% sig_res$gene,] %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("gene") %>% 
  left_join(sig_res[,"gene"],.) %>% 
  tibble::column_to_rownames("gene")

## Run pheatmap using the metadata data frame for the annotation
# pheatmap(sig_counts, 
#          color = heat_colors, 
#          cluster_rows = TRUE, 
#          show_rownames = F,
#          annotation = colData, 
#          border_color = NA, 
#          fontsize = 10, 
#          scale = "row", 
#          fontsize_row = 3, 
#          height = 20)  

Heatmap(z, name = "z-score", 
        width = ncol(z)*unit(5, "mm"), 
        height = nrow(z)*unit(0.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = F, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))
```


```{r, fig.height = 12}

#png("pheatmap_SPZ_infected_vs_bystander.png", width = 40, height = 30, units = "cm", res = 300)
Heatmap(z[1:60,], name = "z-score", 
        width = ncol(z)*unit(5, "mm"), 
        height = 60*unit(1.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = T, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))
#dev.off()


```

# control (base) vs SPZ_infected

```{r}
# Monocytes activated (type I IFN signature)
# Run DE analysis


# 1. Get counts matrix

condition1 <- "control"
condition2 <- "sporozoite_infected"
#celltype <- "Monocytes activated (Nfkb + type I IFN)"

counts <- act.mono %>% 
  data.frame() %>% 
  dplyr::select(c(contains(condition1), contains(condition2))) %>% 
  dplyr::select(-c(contains("RBC_")))

# 2 Generate metadata
colData <- data.frame(sample = colnames(counts))
colData$condition = sapply(str_split(colData$sample, "D"), function(x) x[1])
colData <- colData %>% 
  column_to_rownames("sample")

# more info for metadata

# DEseq2 object
dds <- DESeqDataSetFromMatrix(countData = counts,
                             colData = colData,
                             design = ~condition)

# filter dds
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]

dds$condition <- relevel(dds$condition, ref = "control")

dds <- DESeq(dds)

# Transform counts for data visualization
rld <- rlog(dds, blind=F)

# Plot PCA
DESeq2::plotPCA(rld, ntop = 500, intgroup = "condition")

# Extract the rlog matrix from the object and compute pairwise correlation values
rld_mat <- assay(rld)
rld_cor <- cor(rld_mat)

# Plot heatmap
pheatmap(rld_cor, annotation = colData[, c("condition"), drop=F])

# check the coefficients
resultsNames(dds)
comparison <- resultsNames(dds)[2]

res <- results(dds, name = comparison, alpha = 0.1)
# res <- res <- lfcShrink(dds, 
#                  coef =  comparison,
#                  res=res)
#res


# Turn the DESeq2 results object into a tibble for use with tidyverse functions
res_tbl <- res %>%
  data.frame() %>%
  rownames_to_column(var = "gene") %>%
  as_tibble() %>%
  arrange(pvalue)

# Check results output
#res_tbl 

# Write all results to file
# write.csv(res_tbl,
#           paste0(comparison,".csv"),
#           quote = FALSE, 
#           row.names = FALSE)

####
padj_cutoff <- 0.1

# Subset the significant results
sig_res <- dplyr::filter(res_tbl, padj <= padj_cutoff) %>%
  dplyr::arrange(padj)

# Check significant genes output
sig_res_pos <- sig_res %>%
  filter(log2FoldChange >= 0)

DT::datatable(sig_res_pos)


sig_res_neg <- sig_res %>%
  filter(log2FoldChange < 0)

DT::datatable(sig_res_neg)

# Write all results to file
# write.csv(sig_res,
#           paste0(comparison,".csv"),
#           quote = FALSE, 
#           row.names = FALSE)

## Extract normalized counts from dds object
normalized_counts <- counts(dds, normalized = TRUE)

## Extract normalized counts for significant genes only
sig_counts <- normalized_counts[rownames(normalized_counts) %in% sig_res$gene, ]

## Set a color-blind friendly palette
heat_colors <- rev(brewer.pal(11, "PuOr"))


```


```{r, fig.height = 12}

vsd <- assay(vst(dds, nsub = sum( rowMeans( counts(dds, normalized=TRUE)) > 5 )))
z <- t(scale(t(vsd)))
z <- z[rownames(z) %in% sig_res$gene,] %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("gene") %>% 
  left_join(sig_res[,"gene"],.) %>% 
  tibble::column_to_rownames("gene")
## Run pheatmap using the metadata data frame for the annotation
# pheatmap(sig_counts, 
#          color = heat_colors, 
#          cluster_rows = TRUE, 
#          show_rownames = F,
#          annotation = colData, 
#          border_color = NA, 
#          fontsize = 10, 
#          scale = "row", 
#          fontsize_row = 3, 
#          height = 20)  

Heatmap(z, name = "z-score", 
        width = ncol(z)*unit(5, "mm"), 
        height = nrow(z)*unit(0.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = F, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))
```


```{r, fig.height=12}

#png("pheatmap_SPZ_infected_vs_bystander.png", width = 40, height = 30, units = "cm", res = 300)
Heatmap(z[1:60,], name = "z-score", 
        width = ncol(z)*unit(5, "mm"), 
        height = 80*unit(1.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = T, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))
#dev.off()


```

# RBC_bystander (base) vs RBC_infected

```{r}
# Monocytes activated (type I IFN signature)
# Run DE analysis
# 1. Get counts matrix

condition1 <- "RBC_infected"
condition2 <- "RBC_bystander"

counts <- act.mono %>% 
  data.frame() %>% 
  select(c(starts_with(condition1), starts_with(condition2)))


# 2 Generate metadata
colData <- data.frame(sample = colnames(counts))
colData$condition = sapply(str_split(colData$sample, "D"), function(x) x[1])
colData <- colData %>% 
  column_to_rownames("sample")

# more info for metadata

# DEseq2 object
dds <- DESeqDataSetFromMatrix(countData = counts,
                             colData = colData,
                             design = ~condition)

# filter dds
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]

dds$condition <- relevel(dds$condition, ref = "RBC_bystander")

dds <- DESeq(dds)

# Transform counts for data visualization
rld <- rlog(dds, blind=F)

# Plot PCA
DESeq2::plotPCA(rld, ntop = 500, intgroup = "condition")

# Extract the rlog matrix from the object and compute pairwise correlation values
rld_mat <- assay(rld)
rld_cor <- cor(rld_mat)

# Plot heatmap
pheatmap(rld_cor, annotation = colData[, c("condition"), drop=F])

# check the coefficients
resultsNames(dds)
comparison <- resultsNames(dds)[2]

res <- results(dds, name = comparison, alpha = 0.1)
# res <- res <- lfcShrink(dds, 
#                  coef =  comparison,
#                  res=res)
#res


# Turn the DESeq2 results object into a tibble for use with tidyverse functions
res_tbl <- res %>%
  data.frame() %>%
  rownames_to_column(var = "gene") %>%
  as_tibble() %>%
  arrange(pvalue)

# Check results output
#res_tbl 

# Write all results to file
# write.csv(res_tbl,
#           paste0(comparison,".csv"),
#           quote = FALSE, 
#           row.names = FALSE)

####
padj_cutoff <- 0.1

# Subset the significant results
sig_res <- dplyr::filter(res_tbl, padj <= padj_cutoff) %>%
  #filter(abs(log2FoldChange) > 1) %>% 
  dplyr::arrange(padj)

# Check significant genes output

sig_res_pos <- sig_res %>%
  filter(log2FoldChange >= 0)

DT::datatable(sig_res_pos)


sig_res_neg <- sig_res %>%
  filter(log2FoldChange < 0)

DT::datatable(sig_res_neg)


# Write all results to file
# write.csv(sig_res,
#           paste0(comparison,".csv"),
#           quote = FALSE, 
#           row.names = FALSE)

## Extract normalized counts from dds object
normalized_counts <- counts(dds, normalized = TRUE)

## Extract normalized counts for significant genes only
sig_counts <- normalized_counts[rownames(normalized_counts) %in% sig_res$gene, ]

## Set a color-blind friendly palette
heat_colors <- rev(brewer.pal(11, "PuOr"))
```

```{r, fig.height = 12}
vsd <- assay(vst(dds))
z <- t(scale(t(vsd)))
z <- z[rownames(z) %in% sig_res$gene,] %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("gene") %>% 
  left_join(sig_res[,"gene"],.) %>% 
  tibble::column_to_rownames("gene")
## Run pheatmap using the metadata data frame for the annotation
# pheatmap(sig_counts, 
#          color = heat_colors, 
#          cluster_rows = TRUE, 
#          show_rownames = F,
#          annotation = colData, 
#          border_color = NA, 
#          fontsize = 10, 
#          scale = "row", 
#          fontsize_row = 3, 
#          height = 20)  

Heatmap(z, name = "z-score", 
        width = ncol(z)*unit(5, "mm"), 
        height = nrow(z)*unit(1.5, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = F, 
        row_names_gp = gpar(fontsize = 4),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))

#png("pheatmap_SPZ_infected_vs_bystander.png", width = 40, height = 30, units = "cm", res = 300)
# Heatmap(z, name = "z-score", 
#         width = ncol(z)*unit(5, "mm"), 
#         height = 80*unit(1.5, "mm"),
#         col = heat_colors, 
#         cluster_rows= T, cluster_columns = T, 
#         show_column_dend = T, show_row_dend = F, 
#         show_row_names = T, 
#         row_names_gp = gpar(fontsize = 5),
#         column_names_side = "top", column_names_rot = 45, 
#         column_names_gp = gpar(fontsize = 6),
#         #row_km = 2, 
#         column_km = 2, border = TRUE, 
#         column_title = NULL, row_title = NULL, 
#         border_gp = gpar(col = "darkgrey"))
#dev.off()


```

# SPZ_bystander (base) vs SPZ_infected

```{r}
# Monocytes activated (type I IFN signature)
# Run DE analysis
# 1. Get counts matrix

condition1 <- "sporozoite_infected"
condition2 <- "sporozoite_bystander"

counts <- act.mono %>% 
  data.frame() %>% 
  select(c(starts_with(condition1), starts_with(condition2)))


# 2 Generate metadata
colData <- data.frame(sample = colnames(counts))
colData$condition = sapply(str_split(colData$sample, "D"), function(x) x[1])
colData <- colData %>% 
  column_to_rownames("sample")

# more info for metadata

# DEseq2 object
dds <- DESeqDataSetFromMatrix(countData = counts,
                             colData = colData,
                             design = ~condition)

# filter dds
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]

dds$condition <- relevel(dds$condition, ref = "sporozoite_bystander")

dds <- DESeq(dds)

# Transform counts for data visualization
rld <- rlog(dds, blind=F)

# Plot PCA
DESeq2::plotPCA(rld, ntop = 500, intgroup = "condition")

# Extract the rlog matrix from the object and compute pairwise correlation values
rld_mat <- assay(rld)
rld_cor <- cor(rld_mat)

# Plot heatmap
pheatmap(rld_cor, annotation = colData[, c("condition"), drop=F])

# check the coefficients
resultsNames(dds)
comparison <- resultsNames(dds)[2]

res <- results(dds, name = comparison, alpha = 0.1)
# res <- res <- lfcShrink(dds, 
#                  coef =  comparison,
#                  res=res)
#res


# Turn the DESeq2 results object into a tibble for use with tidyverse functions
res_tbl <- res %>%
  data.frame() %>%
  rownames_to_column(var = "gene") %>%
  as_tibble() %>%
  arrange(pvalue)

# Check results output
#res_tbl 

# Write all results to file
# write.csv(res_tbl,
#           paste0(comparison,".csv"),
#           quote = FALSE, 
#           row.names = FALSE)

####
padj_cutoff <- 0.1

# Subset the significant results
sig_res <- dplyr::filter(res_tbl, padj <= padj_cutoff) %>%
  dplyr::arrange(padj)

# Check significant genes output

sig_res_pos <- sig_res %>%
  filter(log2FoldChange >= 0)

DT::datatable(sig_res_pos)


sig_res_neg <- sig_res %>%
  filter(log2FoldChange < 0)

DT::datatable(sig_res_neg)

# Write all results to file
# write.csv(sig_res,
#           paste0(comparison,".csv"),
#           quote = FALSE, 
#           row.names = FALSE)

## Extract normalized counts from dds object
normalized_counts <- counts(dds, normalized = TRUE)

## Extract normalized counts for significant genes only
sig_counts <- normalized_counts[rownames(normalized_counts) %in% sig_res$gene, ]

## Set a color-blind friendly palette
heat_colors <- rev(brewer.pal(11, "PuOr"))
```

```{r, fig.height = 12}
vsd <- assay(vst(dds))
z <- t(scale(t(vsd)))
z <- z[rownames(z) %in% sig_res$gene,] %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("gene") %>% 
  left_join(sig_res[,"gene"],.) %>% 
  tibble::column_to_rownames("gene")

Heatmap(z, name = "z-score", 
        width = ncol(z)*unit(5, "mm"), 
        height = nrow(z)*unit(2, "mm"),
        col = heat_colors, 
        cluster_rows= T, cluster_columns = T, 
        show_column_dend = T, show_row_dend = F, 
        show_row_names = T, 
        row_names_gp = gpar(fontsize = 5),
        column_names_side = "top", column_names_rot = 45, 
        column_names_gp = gpar(fontsize = 6),
        #row_km = 2, 
        column_km = 2, border = TRUE, 
        column_title = NULL, row_title = NULL, 
        border_gp = gpar(col = "darkgrey"))

#png("pheatmap_SPZ_infected_vs_bystander.png", width = 40, height = 30, units = "cm", res = 300)
# Heatmap(z[1:60,], name = "z-score", 
#         width = ncol(z)*unit(5, "mm"), 
#         height = 60*unit(1.5, "mm"),
#         col = heat_colors, 
#         cluster_rows= T, cluster_columns = T, 
#         show_column_dend = T, show_row_dend = F, 
#         show_row_names = T, 
#         row_names_gp = gpar(fontsize = 4),
#         column_names_side = "top", column_names_rot = 45, 
#         column_names_gp = gpar(fontsize = 6),
#         #row_km = 2, 
#         column_km = 2, border = TRUE, 
#         column_title = NULL, row_title = NULL, 
#         border_gp = gpar(col = "darkgrey"))
#dev.off()

```

