---
title: "Reactome pathway enrichment heatmap"
output:
  html_document:
    df_print: paged
    code_folding: hide
  pdf_document: default
  toc: TRUE
---


```{r}
library(Seurat)
library(patchwork)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
library(ggplot2)
library(SeuratData)
#library(celldex)
#install.packages("cowplot")
library(cowplot)
#devtools::install_github('cole-trapnell-lab/monocle3')
library(monocle3)
#remotes::install_github('satijalab/seurat-wrappers')
library(SeuratWrappers)
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(ggrepel)
library(data.table)
library(ComplexHeatmap)
library(msigdbr)
library(heatmap3)
library(presto)
library(fgsea)
library(httr)
library(jsonlite)
library(scales)
library(viridis)
library(rtracklayer)
library(circlize)
```

```{r}
iRBC_vs_RBC_hs_enrichment.RCTM <- read.delim("iRBC_vs_RBC_hs_enrichment.RCTM.tsv") %>% 
  dplyr::rename(iRBC_vs_RBC_hs = strength) %>% 
  dplyr::select(term.description, iRBC_vs_RBC_hs)
SPZ_vs_iRBC_hs_enrichment.RCTM <- read.delim("SPZ_vs_iRBC_hs_enrichment.RCTM.tsv") %>% 
  dplyr::rename(SPZ_vs_iRBC_hs = strength)  %>% 
  dplyr::select(term.description, SPZ_vs_iRBC_hs)
SPZ_vs_untr_hs_enrichment.RCTM <- read.delim("SPZ_vs_untr_hs_enrichment.RCTM.tsv") %>% 
  dplyr::rename(SPZ_vs_untr_hs = strength)  %>% 
  dplyr::select(term.description, SPZ_vs_untr_hs)

SPZ_vs_untr_mm_enrichment.RCTM <- read.delim("SPZ_vs_untr_mm_enrichment.RCTM.tsv") %>% 
  dplyr::rename(SPZ_vs_untr_mm = strength)  %>% 
  dplyr::select(term.description, SPZ_vs_untr_mm)
SPZ_vs_iRBC_mm_enrichment.RCTM <- read.delim("SPZ_vs_iRBC_mm_enrichment.RCTM.tsv") %>% 
  dplyr::rename(SPZ_vs_iRBC_mm = strength) %>% 
  dplyr::select(term.description, SPZ_vs_iRBC_mm)

```

```{r}

SPZ_vs_untr_RCTM <- SPZ_vs_untr_hs_enrichment.RCTM %>% 
  left_join(., SPZ_vs_untr_mm_enrichment.RCTM) %>% 
  select(-c(contains("mm")))

SPZ_vs_iRBC_RCTM <- SPZ_vs_iRBC_hs_enrichment.RCTM %>% 
  left_join(., SPZ_vs_iRBC_mm_enrichment.RCTM) %>% 
  select(-c(contains("mm")))

iRBC_vs_RBC_RCTM <- iRBC_vs_RBC_hs_enrichment.RCTM

RCTM_all_comparisons <- list(SPZ_vs_untr_RCTM, SPZ_vs_iRBC_RCTM, iRBC_vs_RBC_RCTM) %>% 
  purrr::reduce(full_join, by = "term.description") %>% 
  column_to_rownames("term.description") %>% 
  #filter(!(is.na(SPZ_vs_untr_logfc) & is.na(SPZ_vs_iRBC_logfc) & is.na(iRBC_vs_RBC_logfc))) %>% 
  dplyr::rename(SPZ_vs_untr = SPZ_vs_untr_hs,
                SPZ_vs_iRBC = SPZ_vs_iRBC_hs,
                iRBC_vs_RBC = iRBC_vs_RBC_hs)

RCTM_all_comparisons[is.na(RCTM_all_comparisons)] <- 0

genes_to_show <- RCTM_all_comparisons %>% 
  dplyr::select(SPZ_vs_iRBC) %>% 
  filter(SPZ_vs_iRBC > 0)
  
mark_at = which(rownames(RCTM_all_comparisons) %in% rownames(genes_to_show))
genes_on_heatmap <- rownames(RCTM_all_comparisons[mark_at,])
ha = rowAnnotation(gene = anno_mark(at = mark_at, labels = genes_on_heatmap, labels_gp = gpar(fontsize = 7)))


p <- Heatmap(RCTM_all_comparisons, 
        right_annotation = ha,
        #col = viridis_pal(option = "B")(8),
        #col = colorRampPalette(rev(brewer.pal(n = 5, name ="Spectral")))(50),
        col = colorRamp2(c(0,  1.5), c("white", "red")),
        rect_gp = gpar(col = "white", lwd = 0.5),
        width = ncol(RCTM_all_comparisons)*unit(7, "mm"),
        #height = nrow(DEG_all_comparisons)*unit(0.3, "mm"),
        name = "Log10(Obs/Exp)",
        na_col = "gray",
        heatmap_legend_param = list(legend_gp = gpar(fontsize = 1)),
        cluster_rows = T, 
        cluster_columns = F,
        show_row_dend = F, 
        show_row_names = F,
        column_title = "Enriched pathways",
        column_title_gp = gpar(fontsize = 12),
        column_names_gp = gpar(fontsize = 8),
        column_names_rot = 45,
        row_names_gp = gpar(fontsize = 1))

pdf("Heatmap_RCTM_pathways_overlap_mouse_human.pdf")
draw(p)
dev.off()

```