---
title: "Sporozoite classification"
output:
  html_document:
    df_print: paged
    code_folding: hide
  pdf_document: default
  toc: TRUE
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
#knitr::opts_chunk$set(fig.width = 10, fig.height = 8) 
```

```{r}
library(Seurat)
library(patchwork)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
library(ggplot2)
library(SeuratData)
#library(celldex)
#install.packages("cowplot")
library(cowplot)
#devtools::install_github('cole-trapnell-lab/monocle3')
library(monocle3)
#remotes::install_github('satijalab/seurat-wrappers')
library(SeuratWrappers)
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(ggrepel)
library(data.table)
library(ComplexHeatmap)
library(msigdbr)
library(heatmap3)
library(presto)
library(fgsea)
library(topGO)
# install.packages("devtools")
# devtools::install_github("saeyslab/nichenetr")
#library(nichenetr)
# mulattoes::install('multtest')
# install.packages('metap')
#library(metap)
#remotes::install_github("satijalab/seurat-data")
```

```{r}
immune.combined <- readRDS("immune.combined_all_libs_preprocessed.rds")

immune.combined@meta.data <- immune.combined@meta.data %>% 
  mutate(Donorid = case_when(
    orig.ident %in% c("EXP1_l2", "EXP1_l1") & donor_id == "donor0" ~ "D1",
    orig.ident %in% c("EXP1_l2", "EXP1_l1") & donor_id == "donor1" ~ "D2",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor0" ~ "D3",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor1" ~ "D4",
    orig.ident %in% c("EXP2_l1", "EXP2_l2", "EXP2_l3") & donor_id == "donor2" ~ "D5"
  ))

```

```{r}

immune.combined@meta.data <- immune.combined@meta.data %>% 
mutate(SPZ = case_when(
  str_detect(Group, "^sporozoite_*") ~ "SPZ",
  .default = "notSPZ"
))

spz_cells <- subset(immune.combined, subset = SPZ == "SPZ")

```

# Step 3: Normalisation
```{r}
# After removing unwanted cells from the dataset, the next step is to normalize the data. By default, we employ a global-scaling normalization method “LogNormalize” that normalizes the feature expression measurements for each cell by the total expression, multiplies this by a scale factor (10,000 by default), and log-transforms the result. Normalized values are stored in pbmc[["RNA"]]@data.

DefaultAssay(spz_cells) <- "RNA"

spz_cells <- NormalizeData(spz_cells, normalization.method = "LogNormalize", scale.factor = 10000)

spz_cells <- FindVariableFeatures(spz_cells, selection.method = "vst", nfeatures = 2000)

```


```{r}

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(spz_cells), 10)
top10

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(spz_cells)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)

plot2

```

```{r}
all.genes <- rownames(spz_cells)
spz_cells <- ScaleData(spz_cells, features = all.genes)

```

```{r}
# dim reduction
spz_cells <- RunPCA(spz_cells, features = VariableFeatures(object = spz_cells))
#DimPlot(mono,reduction="pca")
#DimPlot(mono,reduction="pca", group.by = "largest_gene", label = TRUE, label.size = 3)# + NoLegend()
#DimPlot(mono,reduction="pca", dims=c(3,4))
# Examine and visualize PCA results a few different ways
print(spz_cells[["pca"]], dims = 1:5, nfeatures = 5)

VizDimLoadings(spz_cells, dims = 1:2, reduction = "pca")

spz_cells <- JackStraw(spz_cells, num.replicate = 70)
spz_cells <- ScoreJackStraw(spz_cells, dims = 1:20)

# The JackStrawPlot() function provides a visualization tool for comparing the distribution of p-values for each PC with a uniform distribution (dashed line). ‘Significant’ PCs will show a strong enrichment of features with low p-values (solid curve above the dashed line). In this case it appears that there is a sharp drop-off in significance after the first 10-12 PCs.

JackStrawPlot(spz_cells, dims = 1:20)

ElbowPlot(spz_cells)

dims_to_use = 20

RunTSNE(
  spz_cells,
  dims=1:dims_to_use,
  seed.use = 123, 
  perplexity=100
) -> spz_cells

DimPlot(spz_cells, group.by = "HTO_classification",reduction = "tsne", pt.size = 1) + ggtitle("tSNE with Perplexity 100")
DimPlot(spz_cells, group.by = "Group", reduction = "tsne", pt.size = 1) + ggtitle("tSNE with Perplexity 100")

```

```{r}
spz_cells <- FindNeighbors(spz_cells, dims = 1:dims_to_use)
spz_cells@graphs$RNA_snn[1:20,1:20]

spz_cells <- FindClusters(spz_cells, resolution = 1.0)
spz_cells <- RunUMAP(spz_cells, dims = 1:dims_to_use)

DimPlot(spz_cells, group.by = "HTO_classification", reduction = "umap", label = "T")
DimPlot(spz_cells, group.by = "donor_id", reduction = "umap", label = "F")
DimPlot(spz_cells, group.by = "Group", reduction = "umap", label = "T")

spz_cells <- FindClusters(spz_cells, resolution = 0.9)
spz_cells <- RunUMAP(spz_cells, dims = 1:dims_to_use)

# note that you can set `label = TRUE` or use the LabelClusters function to help label
# individual clusters
DimPlot(spz_cells,group.by = "HTO_classification", reduction = "umap", label = "T")#
DimPlot(spz_cells, group.by = "donor_id",reduction = "umap", label = "F")
DimPlot(spz_cells, group.by = "Group",reduction = "umap", label = "F")
DimPlot(spz_cells, group.by = "seurat_clusters",reduction = "umap", label = "T")
DimPlot(spz_cells, group.by = "predicted.celltype",reduction = "umap", label = "T")

```

```{r}
spz_cells.markers <- FindAllMarkers(spz_cells, only.pos = F, min.pct = 0.25, logfc.threshold = 0.25)
spz_cells.markers.top2 <- spz_cells.markers %>%
    group_by(cluster) %>%
    slice_max(n = 10, order_by = abs(avg_log2FC))
spz_cells.markers.top2
FeaturePlot(spz_cells, features = sample(spz_cells.markers.top2$gene, 15))

DotPlot(
  spz_cells,
  assay = "RNA",
  features = unique(spz_cells.markers.top2$gene),
  cols=  c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 2,
  idents = NULL,
  group.by = NULL,
  split.by = NULL,
  cluster.idents = TRUE,
  scale = TRUE,
  scale.by = "radius",
  scale.min = NA,
  scale.max = NA
) + coord_flip()
```