---
title: "Transcription factor enrichment analysis"
output:
  html_document:
    df_print: paged
    code_folding: hide
  pdf_document: default
  toc: TRUE
---

```{r}
library(Seurat)
library(patchwork)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
library(ggplot2)
library(SeuratData)
#library(celldex)
#install.packages("cowplot")
library(cowplot)
#devtools::install_github('cole-trapnell-lab/monocle3')
library(monocle3)
#remotes::install_github('satijalab/seurat-wrappers')
library(SeuratWrappers)
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(ggrepel)
library(data.table)
library(ComplexHeatmap)
library(msigdbr)
library(heatmap3)
library(presto)
library(fgsea)
library(httr)
library(jsonlite)
library(scales)
library(viridis)
library(rtracklayer)
library(circlize)
# install.packages("devtools")
# devtools::install_github("saeyslab/nichenetr")
#library(nichenetr)
# mulattoes::install('multtest')
# install.packages('metap')
#library(metap)
#remotes::install_github("satijalab/seurat-data")
```

```{r}

my_chea3 <- function(tr.object, name)
{
  #.rowNamesDF(DE_tab, make.names = T) <- tr.object$genes$Symbol
  DE_tab_ord <- tr.object[order(tr.object$padj),]
  
  #Add genes to Input_Genes list
  genes <- DE_tab_ord %>%
    #mutate(FDR = p.adjust(PValue, method = "BH")) %>% 
    dplyr::filter(padj <= 0.1 & abs(log2FoldChange) >= 1) %>% 
    pull(GeneSymbol)
  #rownames(DE_tab_ord)[1:200]
  
  # Assign variables for ChEA3
  url = "https://amp.pharm.mssm.edu/chea3/api/enrich/"
  encode = "json"
  payload = list(query_name = name, gene_set = genes)
  
  #POST to ChEA3 server
  response = POST(url = url, body = payload, encode = encode)
  json = content(response, "text")
  
  #select mean rank table from results 
  results = fromJSON(json)
  
  mean_rank_tb <- results$`Integrated--meanRank` %>% as_tibble()
  mean_rank_tb[[paste(name)]] = as.numeric(mean_rank_tb$Score)
  mean_rank_tb[[paste(name, "rank", collapse = "_")]] = as.numeric(mean_rank_tb$Rank)
  mean_rank_clean = mean_rank_tb %>%
    dplyr::select(TF,name, ends_with("rank")) %>%
    dplyr::select(-Rank)

  return(mean_rank_clean)
  #return(results)
}

# load TFEA from both orgs

convertMouseGeneList_df <- function(x){
require("biomaRt")
human = useMart("ensembl", dataset = "hsapiens_gene_ensembl", host = "dec2021.archive.ensembl.org")
mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl", host = "dec2021.archive.ensembl.org")
genesV2 = getLDS(attributes = c("mgi_symbol"), filters = "mgi_symbol", values = x , mart = mouse, attributesL = c("hgnc_symbol"), martL = human, uniqueRows=T)
humanx <- unique(genesV2[, 2])
return(genesV2)
}
```

```{r overlap_with_bulk, child = 'GeneRepresentation_bulkRNAseq_allcells.Rmd', echo = T, result = 'asis'}

```

```{r}

SPZ_GFPpos_vs_untr_TFEA <- my_chea3(tr.object = rbind(SPZ_GFPpos_vs_untr[["sig_genes_pvalue_pos"]],
                                                      SPZ_GFPpos_vs_untr[["sig_genes_pvalue_neg"]]), 
                                    name = "SPZ_GFPpos_vs_untr")

SPZ_GFPneg_vs_untr_TFEA <- my_chea3(tr.object = rbind(SPZ_GFPneg_vs_untr[["sig_genes_pvalue_pos"]],
                                                      SPZ_GFPneg_vs_untr[["sig_genes_pvalue_neg"]]), 
                                    name = "SPZ_GFPneg_vs_untr")

SPZ_vs_iRBC_TFEA <- my_chea3(tr.object = rbind(SPZ_vs_iRBC[["sig_genes_pvalue_pos"]],
                                               SPZ_vs_iRBC[["sig_genes_pvalue_neg"]]), 
                                    name = "SPZ_vs_iRBC")

combined_TFs <- inner_join(SPZ_GFPpos_vs_untr_TFEA[1:200,], SPZ_GFPneg_vs_untr_TFEA[1:200,]) %>% 
  inner_join(., SPZ_vs_iRBC_TFEA[1:200,]) %>% 
  column_to_rownames("TF") %>% 
  arrange("SPZ_GFPpos_vs_untr rank", "SPZ_vs_iRBC rank") %>% 
  dplyr::select(-c(SPZ_GFPpos_vs_untr, SPZ_GFPneg_vs_untr, SPZ_vs_iRBC)) %>% 
  mutate(SPZ_GFPpos_vs_untr = `SPZ_GFPpos_vs_untr rank`,
         SPZ_GFPneg_vs_untr = `SPZ_GFPneg_vs_untr rank`,
         SPZ_vs_iRBC = `SPZ_vs_iRBC rank`) %>% 
  dplyr::select(-c(contains("rank")))

mat = combined_TFs

p <- Heatmap(mat,
             col = viridis_pal(option = "B")(8),
        rect_gp = gpar(col = "white", lwd = 0.5),
        width = ncol(mat)*unit(7, "mm"),
        height = nrow(mat)*unit(2, "mm"),
        name = "TFEA rank",
        heatmap_legend_param = list(legend_gp = gpar(fontsize = 5)),
        cluster_rows = T, cluster_columns = F,
        show_row_dend = T, show_row_names = T,
        column_title = "Enriched TF rank",
        column_title_gp = gpar(fontsize = 12),
        column_names_gp = gpar(fontsize = 8),
        column_names_rot = 45,
        row_names_gp = gpar(fontsize = 5))

png("TFEA_heatmap.png", res = 300, width = 15, height = 25, units = "cm")
draw(p)
dev.off()
```

```{r}

# with overlapped genes

SPZ_vs_untr_TFEA <- my_chea3(tr.object = rbind(SPZ_vs_untr[["sig_genes_pvalue_pos"]],
                                                      SPZ_vs_untr[["sig_genes_pvalue_neg"]]), 
                                    name = "SPZ_vs_untr")

iRBC_vs_SPZ_TFEA <- my_chea3(tr.object = rbind(iRBC_vs_SPZ[["sig_genes_pvalue_pos"]],
                                                      iRBC_vs_SPZ[["sig_genes_pvalue_neg"]]), 
                                    name = "SPZ_GFPneg_vs_untr")

iRBC_vs_RBC_TFEA <- my_chea3(tr.object = rbind(iRBC_vs_RBC[["sig_genes_pvalue_pos"]],
                                               iRBC_vs_RBC[["sig_genes_pvalue_neg"]]), 
                                    name = "SPZ_vs_iRBC")

combined_TFs <- inner_join(SPZ_GFPpos_vs_untr_TFEA[1:200,], SPZ_GFPneg_vs_untr_TFEA[1:200,]) %>% 
  inner_join(., SPZ_vs_iRBC_TFEA[1:200,]) %>% 
  column_to_rownames("TF") %>% 
  arrange("SPZ_GFPpos_vs_untr rank", "SPZ_vs_iRBC rank") %>% 
  dplyr::select(-c(SPZ_GFPpos_vs_untr, SPZ_GFPneg_vs_untr, SPZ_vs_iRBC)) %>% 
  mutate(SPZ_GFPpos_vs_untr = `SPZ_GFPpos_vs_untr rank`,
         SPZ_GFPneg_vs_untr = `SPZ_GFPneg_vs_untr rank`,
         SPZ_vs_iRBC = `SPZ_vs_iRBC rank`) %>% 
  dplyr::select(-c(contains("rank")))

mat = combined_TFs

p <- Heatmap(mat,
             col = viridis_pal(option = "B")(8),
        rect_gp = gpar(col = "white", lwd = 0.5),
        width = ncol(mat)*unit(7, "mm"),
        height = nrow(mat)*unit(2, "mm"),
        name = "TFEA rank",
        heatmap_legend_param = list(legend_gp = gpar(fontsize = 5)),
        cluster_rows = T, cluster_columns = F,
        show_row_dend = T, show_row_names = T,
        column_title = "Enriched TF rank",
        column_title_gp = gpar(fontsize = 12),
        column_names_gp = gpar(fontsize = 8),
        column_names_rot = 45,
        row_names_gp = gpar(fontsize = 5))

png("TFEA_heatmap.png", res = 300, width = 15, height = 25, units = "cm")
draw(p)
dev.off()

```


```{r}

# not with overlapped genes
# separately for mouse and human

# for human

SPZ_vs_untr_TFEA_hs <- my_chea3(tr.object = SPZ_vs_untr[["human_sig_res"]] %>% 
                               filter(log2FoldChange > 0) %>% 
                               mutate(GeneSymbol = gene), 
                                    name = "hs_SPZ_vs_untr")

write.csv2(SPZ_vs_untr_TFEA_hs, "SPZ_vs_untr_hsTFEA_Integrated_meanRank.csv", row.names = F, quote = F)

SPZ_vs_iRBC_TFEA_hs <- my_chea3(tr.object = iRBC_vs_SPZ[["human_sig_res"]] %>% 
                               filter(log2FoldChange < 0)%>% 
                               mutate(log2FoldChange = -1*log2FoldChange) %>% 
                               mutate(GeneSymbol = gene), 
                                    name = "hs_SPZ_vs_iRBC")

write.csv2(SPZ_vs_iRBC_TFEA_hs, "SPZ_vs_iRBC_hsTFEA_Integrated_meanRank.csv", row.names = F, quote = F)

iRBC_vs_RBC_TFEA_hs <- my_chea3(tr.object = iRBC_vs_RBC[["human_sig_res"]] %>% 
                               filter(log2FoldChange > 0) %>% 
                               mutate(GeneSymbol = gene), 
                                    name = "hs_iRBC_vs_RBC")
write.csv2(iRBC_vs_RBC_TFEA_hs, "iRBC_vs_RBC_hsTFEA_Integrated_meanRank.csv", row.names = F, quote = F)

```

```{r}

## mouse TFEA
tr.object = SPZ_vs_untr[["bulktable_genes"]] %>% 
                               filter(log2FoldChange > 0) %>% 
                               filter(GeneSymbol %in% mm_use_genes)

SPZ_vs_untr_mm_to_hs <- convertMouseGeneList_df(tr.object$GeneSymbol) 

SPZ_vs_untr_mm_to_hs <- SPZ_vs_untr_mm_to_hs %>% 
  dplyr::rename(GeneSymbol = "MGI.symbol") %>% 
  left_join(tr.object, .) %>% 
  distinct(GeneSymbol, .keep_all = T) %>% 
  column_to_rownames("GeneSymbol") %>% 
  na.omit() %>% 
  mutate(GeneSymbol = HGNC.symbol) 

SPZ_vs_untr_TFEA_mm <- my_chea3(SPZ_vs_untr_mm_to_hs, 
                                    name = "mm_SPZ_vs_untr")

write.csv2(SPZ_vs_untr_TFEA_mm, "SPZ_vs_untr_mmTFEA_rank.csv", row.names = F, quote = F)
##
tr.object = iRBC_vs_SPZ[["bulktable_genes"]] %>% 
                               filter(log2FoldChange < 0) %>% 
                               mutate(log2FoldChange = -1*log2FoldChange) %>% 
                               filter(GeneSymbol %in% mm_use_genes)

SPZ_vs_iRBC_mm_to_hs <- convertMouseGeneList_df(tr.object$GeneSymbol) 

SPZ_vs_iRBC_mm_to_hs <- SPZ_vs_iRBC_mm_to_hs %>% 
  dplyr::rename(GeneSymbol = "MGI.symbol") %>% 
  left_join(tr.object, .) %>% 
  distinct(GeneSymbol, .keep_all = T) %>% 
  column_to_rownames("GeneSymbol") %>% 
  na.omit() %>% 
  mutate(GeneSymbol = HGNC.symbol) 

SPZ_vs_iRBC_TFEA_mm <- my_chea3(SPZ_vs_iRBC_mm_to_hs, 
                                    name = "mm_SPZ_vs_iRBC")

write.csv2(SPZ_vs_iRBC_TFEA_mm, "SPZ_vs_iRBC_mmTFEA_rank.csv", row.names = F, quote = F)

####
```

```{r}

#Chea3 can't work with mouse genes, so first change to human symbols
TFselectionrank = 100

SPZ_vs_untr_mmTFEA <- read.csv("tables/SPZ_vs_untr_mmTFEA_rank.csv", sep = ";") %>% 
  dplyr::rename(mm_Rank = contains("rank")) %>% 
  dplyr::select(c(TF, mm_Rank)) %>% 
  filter(mm_Rank <= TFselectionrank)
SPZ_vs_iRBC_mmTFEA <- read.csv("tables/SPZ_vs_iRBC_mmTFEA_rank.csv", sep = ";")%>% 
  dplyr::rename(mm_Rank = contains("rank")) %>% 
  dplyr::select(c(TF, mm_Rank)) %>% 
  filter(mm_Rank <= TFselectionrank)

SPZ_vs_untr_hsTFEA <- read.csv("tables/SPZ_vs_untr_hsTFEA_Integrated_meanRank.csv", sep = ";") %>% 
  dplyr::rename(hs_Rank = contains("rank")) %>% 
  dplyr::select(c(TF, hs_Rank)) %>% 
  filter(hs_Rank <= TFselectionrank)
SPZ_vs_iRBC_hsTFEA <- read.csv("tables/SPZ_vs_iRBC_hsTFEA_Integrated_meanRank.csv", sep = ";") %>% 
  dplyr::rename(hs_Rank = contains("rank")) %>% 
  dplyr::select(c(TF, hs_Rank)) %>% 
  filter(hs_Rank <= TFselectionrank)
iRBC_vs_RBC_hsTFEA <- read.csv("tables/iRBC_vs_RBC_hsTFEA_Integrated_meanRank.csv", sep = ";") %>% 
  dplyr::rename(hs_Rank = contains("rank")) %>% 
  dplyr::select(c(TF, hs_Rank)) %>% 
  filter(hs_Rank <= TFselectionrank)

# join human and mouse results
SPZ_vs_untr_TFEA <- SPZ_vs_untr_hsTFEA %>% 
  inner_join(., SPZ_vs_untr_mmTFEA) %>% 
  dplyr::rename(gene = TF) %>% 
  left_join(., SPZ_vs_untr$human_sig_res) %>% 
  na.omit() %>% 
  dplyr::rename(SPZ_vs_untr_logfc = log2FoldChange)


SPZ_vs_iRBC_TFEA <- SPZ_vs_iRBC_hsTFEA %>% 
  left_join(., SPZ_vs_iRBC_mmTFEA) %>% 
  dplyr::rename(gene = TF) %>% 
  left_join(., iRBC_vs_SPZ$human_sig_res) %>% 
  mutate(log2FoldChange = -1*log2FoldChange) %>% 
  na.omit() %>% 
  dplyr::rename(SPZ_vs_iRBC_logfc = log2FoldChange)

iRBC_vs_RBC_TFEA <- iRBC_vs_RBC_hsTFEA %>% 
  dplyr::rename(gene = TF) %>% 
  left_join(., iRBC_vs_RBC$human_sig_res) %>% 
  na.omit() %>% 
  dplyr::rename(iRBC_vs_RBC_logfc = log2FoldChange)

allTFs <- unique(c(SPZ_vs_untr_TFEA$gene, SPZ_vs_iRBC_TFEA$gene, iRBC_vs_RBC_TFEA$gene))

TF_all_comparisons <- data.frame(gene = allTFs) %>% 
  left_join(., SPZ_vs_untr$human_sig_res) %>% 
  dplyr::select(gene, log2FoldChange) %>% 
  dplyr::rename(SPZ_vs_untr = log2FoldChange) %>% 
  left_join(., iRBC_vs_SPZ$human_sig_res) %>% 
  dplyr::select(gene, SPZ_vs_untr, log2FoldChange) %>% 
  dplyr::rename(SPZ_vs_iRBC = log2FoldChange) %>%
  mutate(SPZ_vs_iRBC = -1*SPZ_vs_iRBC) %>% 
  left_join(., iRBC_vs_RBC$human_sig_res) %>% 
  dplyr::select(gene, SPZ_vs_untr, SPZ_vs_iRBC, log2FoldChange) %>% 
  dplyr::rename(iRBC_vs_RBC = log2FoldChange) %>% 
  column_to_rownames("gene") %>% 
  arrange(SPZ_vs_untr)

# TF_all_comparisons <- list(SPZ_vs_untr_TFEA, SPZ_vs_iRBC_TFEA, iRBC_vs_RBC_TFEA) %>% 
#   purrr::reduce(full_join, by = "gene") %>% 
#   dplyr::select(gene, contains("logfc")) %>% 
#   column_to_rownames("gene") %>% 
#   filter(!(is.na(SPZ_vs_untr_logfc) & is.na(SPZ_vs_iRBC_logfc) & is.na(iRBC_vs_RBC_logfc))) %>% 
#   dplyr::rename(SPZ_vs_untr = SPZ_vs_untr_logfc,
#                 SPZ_vs_iRBC = SPZ_vs_iRBC_logfc,
#                 iRBC_vs_RBC = iRBC_vs_RBC_logfc)

#TF_all_comparisons[is.na(TF_all_comparisons)] <- 0
```

```{r}
# genes_to_show <- SPZ_vs_iRBC_TFEA %>% 
#   dplyr::filter(!is.na(mm_Rank)) %>% 
#   filter(gene %in% rownames(TF_all_comparisons))
#   pull(gene)
  
# genes_to_show <- TF_all_comparisons %>% 
#   dplyr::select(SPZ_vs_iRBC) %>% 
#   filter(SPZ_vs_iRBC > 0)
#   
# mark_at = which(rownames(TF_all_comparisons) %in% rownames(genes_to_show))
# genes_on_heatmap <- rownames(TF_all_comparisons[mark_at,])
# ha = rowAnnotation(gene = anno_mark(at = mark_at, labels = genes_on_heatmap, labels_gp = gpar(fontsize = 7)))

p <- Heatmap(TF_all_comparisons, 
        #right_annotation = ha,
        #col = viridis_pal(option = "B")(8),
        #col = colorRampPalette(rev(brewer.pal(n = 5, name ="Spectral")))(50),
        col = colorRamp2(c(-10, 0, 10), c("blue", "white", "red")),
        rect_gp = gpar(col = "white", lwd = 0.5),
        width = ncol(TF_all_comparisons)*unit(7, "mm"),
        height = nrow(TF_all_comparisons)*unit(1.5, "mm"),
        name = "log2FC",
        na_col = "gray",
        heatmap_legend_param = list(legend_gp = gpar(fontsize = 1)),
        cluster_rows = F, 
        cluster_columns = F,
        show_row_dend = F, 
        show_row_names = T,
        column_title = "Enriched TFs",
        column_title_gp = gpar(fontsize = 12),
        column_names_gp = gpar(fontsize = 8),
        column_names_rot = 45,
        row_names_gp = gpar(fontsize = 4.5))

pdf("Heatmap_TFs_overlap_mouse_human_top100inAllContrasts.pdf")
draw(p)
dev.off()
```