---
title: "UpSet plots for upregulated genes in human and mouse"
output:
  html_document:
    df_print: paged
    code_folding: hide
  pdf_document: default
  toc: TRUE
---

```{r}
library(UpSetR)
library(tidyverse)
library(biomaRt)
library(clusterProfiler)
library(org.Hs.eg.db)
library(fgsea)
library(msigdb)
```

```{r}
# read tables
# untr_vs_SPZ_GFPpos_human <- read.csv("tables/SPZ_GFPpos_vs_untr_human.csv")
# untr_vs_SPZ_GFPpos_mouse <- read.csv("../Data/SPZ-GFPpos_untr_df_4h.csv") %>% 
#   filter(log2FoldChange > 0 & padj < 0.1)

untr_vs_SPZ_human <- read.csv("tables/SPZ_vs_untr_human_nothr.csv") %>%
  filter(log2FoldChange > 1 & padj < 0.1)
untr_vs_SPZ_mouse <- read.csv("../Data/SPZ-GFPpos_untr_df_4h.csv") %>%
  filter(log2FoldChange > 1 & padj < 0.1)

RBC_vs_iRBC_human <- read.csv("tables/iRBC_vs_RBC_human_nothr.csv") %>% 
  filter(log2FoldChange > 1 & padj < 0.1)
RBC_vs_iRBC_mouse <- read.csv("../Data/iRBC_RBC_4h.csv") %>% 
  filter(log2FoldChange > 0 & padj < 0.1)

SPZ_vs_iRBC_human <- read.csv("tables/SPZ_vs_iRBC_human_nothr.csv") %>%
  filter(log2FoldChange > 1 & padj < 0.1)
SPZ_vs_iRBC_mouse <- read.csv("../Data/SPZ-iRBC_df_4h.csv") %>%
  filter(log2FoldChange > 1 & padj < 0.1)
```

```{r}
convertMouseGeneList <- function(x){
human = useMart("ensembl", dataset = "hsapiens_gene_ensembl", host = "https://dec2021.archive.ensembl.org")
mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl", host = "https://dec2021.archive.ensembl.org")
genesV2 = getLDS(attributes = c("mgi_symbol"), filters = "mgi_symbol", values = x , mart = mouse, attributesL = c("hgnc_symbol"), martL = human, uniqueRows=T)
humanx <- unique(genesV2[, 2])
return(humanx)
}
```


```{r}
# Upset

genelist <- list(
  SPZ_human = untr_vs_SPZ_human$gene,
  SPZ_mouse = convertMouseGeneList(untr_vs_SPZ_mouse$GeneSymbol),
  iRBC_human = RBC_vs_iRBC_human$gene,
  iRBC_mouse = convertMouseGeneList(RBC_vs_iRBC_mouse$GeneSymbol),
  #SPZ_iRBC_human = SPZ_vs_iRBC_human$gene,
  #SPZ_iRBC_mouse = convertMouseGeneList(SPZ_vs_iRBC_mouse$GeneSymbol)
)


pdf("upset_plot_common_genes_human_mouse.pdf",  width = 9, height = 5)
upset(fromList(genelist),
      order.by = "freq",
      point.size = 3.5,
      mb.ratio = c(0.55, 0.45),
      text.scale = c(1.5, 1.5, 1.5, 1.15, 1.5, 1.5),
      #shade.color = "darkgreen", #darkgreen
      shade.alpha = 0.4
      #matrix.color = "darkslategray", #darkslategray
      #main.bar.color = "darkseagreen4", #darkseagreen4
      #sets.bar.color = "lightskyblue4" #lightskyblue4
      )
dev.off()
```

```{r}
# gsea for common genes between human and mouse SPZ and iRBC comditions, except iRBC_mouse
genelist.1 <- list(
  SPZ_human = untr_vs_SPZ_human$gene,
  SPZ_mouse = convertMouseGeneList(untr_vs_SPZ_mouse$GeneSymbol),
  iRBC_human = RBC_vs_iRBC_human$gene
  #iRBC_mouse = convertMouseGeneList(RBC_vs_iRBC_mouse$GeneSymbol)
)
#list of genes
SPZ.human_iRBC.human_SPZ.mouse <- Reduce(intersect, genelist.1)

# gsea
spz_irbc_go <- enrichGO(
  gene = SPZ.human_iRBC.human_SPZ.mouse, 
  OrgDb = org.Hs.eg.db, 
  keyType = "SYMBOL", 
  ont = "BP", 
  pvalueCutoff = 0.05, 
  pAdjustMethod = "BH", 
  universe = unique(c(genelist.1[["SPZ_human"]],genelist.1[["SPZ_mouse"]],genelist.1[["iRBC_human"]])),
  qvalueCutoff = 0.2, 
  minGSSize = 10, 
  maxGSSize = 500
  )

write.csv2(spz_irbc_go@result, "GO.enrichment_intersection_SPZ.human_iRBC.human_SPZ.mouse.csv", row.names = F, quote = F)

# msigdb
# m_df<- msigdbr(species = "Homo sapiens", category = "C7")
# fgsea_sets<- m_df %>% split(x = .$gene_symbol, f = .$gs_name)
# 
# 
# 
# ranks<- deframe(SPZ.human_iRBC.human_SPZ.mouse)
# 
# #head(ranks)
# 
# fgseaRes<- fgsea(fgsea_sets, stats = SPZ.human_iRBC.human_SPZ.mouse)
# 
# fgseaResTidy <- fgseaRes %>%
#   as_tibble() %>%
#   arrange(desc(NES))
# 
# 
# fgseaResTidy %>% 
#   dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>% 
#   arrange(padj) 
# 
# ggplot(fgseaResTidy %>% filter(pval < 0.008) %>% head(n= 20), aes(reorder(pathway, NES), NES)) +
#   geom_col(aes(fill= NES)) +
#   coord_flip() +
#   labs(x="Pathway", y="Normalized Enrichment Score",
#        title="Hallmark pathways NES from GSEA") + 
#   theme_minimal()
# 
# png("IRF3.png", res = 300, height = 15, width = 25, units = "cm")
# plotEnrichment(fgsea_sets[["REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN"]],
#                ranks) + labs(title="REACTOME_IRF3_MEDIATED_INDUCTION_OF_TYPE_I_IFN")
# dev.off()
# 
# png("IRF3_IRF7.png", res = 300, height = 15, width = 25, units = "cm")
# plotEnrichment(fgsea_sets[["REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON"]],
#                ranks) + labs(title="REACTOME_ACTIVATION_OF_IRF3_IRF7_MEDIATED_BY_TBK1_IKK_EPSILON")
# dev.off()

```

```{r}
# gsea for common genes between human and mouse SPZ comditions
genelist.2 <- list(
  SPZ_human = untr_vs_SPZ_human$gene,
  SPZ_mouse = convertMouseGeneList(untr_vs_SPZ_mouse$GeneSymbol)
  #iRBC_human = RBC_vs_iRBC_human$gene
  #iRBC_mouse = convertMouseGeneList(RBC_vs_iRBC_mouse$GeneSymbol)
)
#list of genes
SPZ.human_SPZ.mouse <- setdiff(intersect(genelist.1[["SPZ_human"]], genelist.1[["SPZ_mouse"]]), SPZ.human_iRBC.human_SPZ.mouse)

# gsea
spz_go <- enrichGO(
  gene = SPZ.human_SPZ.mouse, 
  OrgDb = org.Hs.eg.db, 
  keyType = "SYMBOL", 
  ont = "BP", 
  pvalueCutoff = 0.05, 
  pAdjustMethod = "BH", 
  universe = unique(c(genelist.1[["SPZ_human"]],genelist.1[["SPZ_mouse"]])),
  qvalueCutoff = 0.2, 
  minGSSize = 10, 
  maxGSSize = 500
  )

write.csv2(spz_go@result, "GO.enrichment_intersection_SPZ.human_SPZ.mouse.csv", row.names = F, quote = F)

```

```{r}
# get upset gene lists
intersect_SPZ_human_iRBC_human <- setdiff(intersect(genelist[["SPZ_human"]], genelist[["iRBC_human"]]), union(genelist[["SPZ_mouse"]], genelist[["iRBC_mouse"]]))

write.table(as.data.frame(intersect_SPZ_human_iRBC_human), "intersect_SPZ_human_iRBC_human.txt", row.names = F, quote = F)

intersect_SPZ_human <- setdiff(genelist[["SPZ_human"]], union(genelist[["iRBC_human"]], union(genelist[["SPZ_mouse"]], genelist[["iRBC_mouse"]])))

write.table(as.data.frame(intersect_SPZ_human), "intersect_SPZ_human.txt", row.names = F, quote = F)

intersect_SPZ_mouse <- setdiff(genelist[["SPZ_mouse"]], union(genelist[["iRBC_human"]], union(genelist[["SPZ_human"]], genelist[["iRBC_mouse"]])))

write.table(as.data.frame(intersect_SPZ_mouse), "intersect_SPZ_mouse.txt", row.names = F, quote = F)

intersect_SPZ_mouse_iRBC_human_SPZ_human <- setdiff(intersect(genelist[["SPZ_mouse"]], intersect(genelist[["iRBC_human"]], genelist[["SPZ_human"]])),  genelist[["iRBC_mouse"]])

write.table(as.data.frame(intersect_SPZ_mouse_iRBC_human_SPZ_human), "intersect_SPZ_mouse_iRBC_human_SPZ_human.txt", row.names = F, quote = F)

intersect_iRBC_human <- setdiff(genelist[["iRBC_human"]], union(genelist[["SPZ_human"]], union(genelist[["SPZ_mouse"]], genelist[["iRBC_mouse"]])))

write.table(as.data.frame(intersect_iRBC_human), "intersect_iRBC_human.txt", row.names = F, quote = F)

intersect_SPZ_human_SPZ_mouse <- setdiff(intersect(genelist[["SPZ_human"]], genelist[["SPZ_mouse"]]), union(genelist[["iRBC_human"]], genelist[["iRBC_mouse"]]))

write.table(as.data.frame(intersect_SPZ_human_SPZ_mouse), "intersect_SPZ_human_SPZ_mouse.txt", row.names = F, quote = F)

intersect_iRBC_human_SPZ_mouse <- setdiff(intersect(genelist[["iRBC_human"]], genelist[["SPZ_mouse"]]), union(genelist[["SPZ_human"]], genelist[["iRBC_mouse"]]))

write.table(as.data.frame(intersect_iRBC_human_SPZ_mouse), "intersect_iRBC_human_SPZ_mouse.txt", row.names = F, quote = F)

intersect_iRBC_mouse <- setdiff(genelist[["iRBC_mouse"]], union(genelist[["SPZ_human"]], union(genelist[["SPZ_mouse"]], genelist[["iRBC_human"]])))

write.table(as.data.frame(intersect_iRBC_mouse), "intersect_iRBC_mouse.txt", row.names = F, quote = F)

```

